// web-common/src/components/chip/core/Chip.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { Writable } from "svelte/store";
  import { slideRight } from "../../../lib/transitions";
  import CancelCircle from "../../icons/CancelCircle.svelte";
  import CaretDownIcon from "../../icons/CaretDownIcon.svelte";
  import Tooltip from "../../tooltip/Tooltip.svelte";
  import TooltipContent from "../../tooltip/TooltipContent.svelte";
  import { PinIcon } from "lucide-svelte";

  export let removable = false;
  export let active = false;
  export let readOnly = false;
  export let type: "measure" | "dimension" | "time" | "special" | "amber" =
    "dimension";
  export let gray = false;
  export let error = false;
  export let exclude = false;
  export let grab = false;
  export let compact = false;
  export let fullWidth = false;
  export let caret = false;
  export let slideDuration = 150;
  export let supressTooltip = false;
  export let label: string | undefined = undefined;
  export let removeTooltipText: string | undefined = undefined;
  export let allowPointerEvents = false;
  export let theme = false;
  export let showPinnedIcon = false;
  export let onRemove: () => void = () => {};
  export let onclick: ((e: MouseEvent) => void) | undefined = undefined;
  export let onmousedown: ((e: MouseEvent) => void) | undefined = undefined;

  const tooltipSuppression = getContext<Writable<boolean>>(
    "statsparrot:app:childRequestedTooltipSuppression",
  );

  function focusOnRemove() {
    if ($tooltipSuppression) tooltipSuppression.set(true);
  }
  function blurOnRemove() {
    if ($tooltipSuppression) tooltipSuppression.set(false);
  }
</script>

<div in:slideRight={{ duration: slideDuration }}>
  <div
    {...$$restProps}
    class="chip {type}"
    class:theme
    class:active
    class:grab
    class:gray
    class:error
    class:exclude
    class:compact
    class:fullWidth
    class:pointer-events-none={readOnly && !allowPointerEvents}
    aria-label={label}
  >
    {#if removable && !readOnly}
      <Tooltip
        alignment="start"
        distance={12}
        suppress={supressTooltip || !removeTooltipText}
      >
        <button
          class="text-inherit mr-0.5"
          aria-label="Remove"
          onmouseover={focusOnRemove}
          onfocus={focusOnRemove}
          onmouseleave={blurOnRemove}
          onblur={blurOnRemove}
          onpointerdown={(e) => e.stopPropagation()}
          onclick={(e) => {
            e.stopPropagation();
            onRemove();
          }}
          type="button"
        >
          <CancelCircle size="16px" />
        </button>

        <TooltipContent maxWidth="300px" slot="tooltip-content">
          {removeTooltipText}
        </TooltipContent>
      </Tooltip>
    {:else if showPinnedIcon}
      <div class="flex-none">
        <PinIcon size="16px" />
      </div>
    {/if}

    {#if $$slots.body}
      {#if readOnly && !allowPointerEvents}
        <!-- A read-only chip has nothing to activate, so it must stay out of the tab order. -->
        <span
          class="text-inherit w-full select-none truncate flex items-center justify-between gap-x-1 px-0.5"
        >
          <slot name="body" />

          {#if caret}
            <span
              class="transition-transform -mr-0.5"
              class:-rotate-180={active}
            >
              <CaretDownIcon size="10px" />
            </span>
          {/if}
        </span>
      {:else}
        <button
          {onclick}
          {onmousedown}
          aria-label={`Open ${label}`}
          class="text-inherit w-full select-none truncate flex items-center justify-between gap-x-1 px-0.5"
          type="button"
        >
          <slot name="body" />

          {#if caret}
            <span
              class="transition-transform -mr-0.5"
              class:-rotate-180={active}
            >
              <CaretDownIcon size="10px" />
            </span>
          {/if}
        </button>
      {/if}
    {/if}
  </div>
</div>

<style lang="postcss">
  .grab {
    @apply cursor-grab;
  }

  .chip {
    @apply flex gap-x-1;
    @apply items-center justify-center;
    @apply px-2 py-[3px] border w-full max-w-fit truncate;
  }

  .dimension {
    @apply rounded-2xl;
    @apply bg-primary-50 border-primary-200 text-primary-800;
  }

  .dimension:hover,
  .dimension:active,
  .dimension.active {
    @apply bg-primary-100;
  }

  .dimension:hover,
  .dimension:active,
  .dimension.active {
    @apply bg-primary-200;
  }

  .dimension.theme {
    @apply bg-theme-50 border-theme-200 text-theme-800;
  }

  .dimension.theme:active,
  .dimension.theme.active {
    @apply border-theme-400;
  }

  .dimension.theme:active,
  .dimension.theme.active {
    @apply border-theme-400;
  }

  .measure {
    @apply rounded-sm;
    @apply bg-secondary-50 border-secondary-200 text-secondary-800;
  }

  .measure:hover,
  .measure:active,
  .measure.active {
    @apply bg-secondary-100;
  }

  .measure:active,
  .measure.active {
    @apply border-secondary-400;
  }

  .measure.theme {
    @apply rounded-sm;
    @apply bg-theme-secondary-50 border-theme-secondary-200 text-theme-secondary-800;
  }

  .measure.theme:hover,
  .measure.theme:active,
  .measure.theme.active {
    @apply bg-theme-secondary-100;
  }

  .measure.theme:active,
  .measure.theme.active {
    @apply border-theme-secondary-400;
  }

  .exclude {
    @apply bg-surface-background text-fg-secondary;
  }

  .exclude:hover,
  .exclude:active,
  .exclude.active {
    @apply bg-gray-100;
  }

  .exclude:active,
  .exclude.active {
    @apply border-gray-400;
  }

  .time {
    @apply rounded-2xl;
    @apply bg-transparent border-gray-200 text-fg-primary;
  }

  .time:hover,
  .time.active,
  .time:active {
    @apply bg-surface-hover;
  }

  .time.active,
  .time:active {
    @apply border-surface-active;
  }

  .amber {
    @apply rounded-2xl h-[18px] text-xs;
    @apply bg-amber-50 border-amber-300 text-amber-600;
    @apply font-normal;
  }

  .amber:hover,
  .amber:active,
  .amber.active {
    @apply bg-amber-100;
  }

  .gray,
  .gray.theme {
    @apply bg-gray-100 border-gray-300 text-fg-secondary;
  }

  .gray:hover,
  .gray:active,
  .gray.active,
  .gray.theme:hover,
  .gray.theme:active,
  .gray.theme.active {
    @apply bg-gray-200 border-gray-400;
  }

  .error,
  .error.theme,
  .error.gray {
    @apply bg-red-50 border-red-400 text-red-700;
  }

  .error:hover,
  .error:active,
  .error.active,
  .error.theme:hover,
  .error.theme:active,
  .error.theme.active {
    @apply bg-red-100 border-red-500;
  }

  .compact {
    @apply py-0;
  }

  .fullWidth {
    @apply w-full max-w-full;
  }
</style>

// web-common/src/features/dashboards/filters/measure-filters/react/Chip.tsx
import type { ReactNode } from "react";
import { CancelCircleIcon, PinIcon } from "./icons";

export interface MeasureChipProps {
  /** Whether the associated popover is open (highlights the chip). */
  active?: boolean;
  /** Muted "no value set" styling. */
  gray?: boolean;
  /** Required-but-missing error styling. */
  error?: boolean;
  /** Apply the `theme` (secondary) color variant. */
  theme?: boolean;
  /** Read-only chips render a static span instead of a clickable button. */
  readOnly?: boolean;
  /** Show the pinned indicator instead of the remove affordance. */
  showPinnedIcon?: boolean;
  removable?: boolean;
  label?: string;
  removeTooltipText?: string;
  title?: string;
  onRemove?: () => void;
  onToggleOpen?: () => void;
  children?: ReactNode;
}

const base =
  "flex gap-x-1 items-center justify-center px-2 py-[3px] border w-full max-w-fit truncate rounded-sm";

/**
 * React stand-in for `Chip.svelte` restricted to the `measure` type variant used by
 * `MeasureFilter`. Renders the remove affordance (or pinned icon) plus the slot body;
 * the body is a `button` in the interactive case and a static `span` when read-only.
 */
export default function MeasureChip({
  active = false,
  gray = false,
  error = false,
  readOnly = false,
  showPinnedIcon = false,
  removable = false,
  label,
  removeTooltipText,
  title,
  onRemove,
  onToggleOpen,
  children,
}: MeasureChipProps) {
  // Priority order mirrors `Chip.svelte` CSS cascade: error > gray > active > base.
  const stateClass = error
    ? "bg-red-50 border-red-400 text-red-700"
    : gray
      ? "bg-gray-100 border-gray-300 text-fg-secondary"
      : active
        ? "bg-theme-secondary-100 border-theme-secondary-400 text-theme-secondary-800"
        : "bg-theme-secondary-50 border-theme-secondary-200 text-theme-secondary-800";

  return (
    <div
      className={`${base} ${stateClass} ${readOnly ? "pointer-events-none" : ""} theme`}
      aria-label={label}
      title={title}
    >
      {removable && !readOnly ? (
        <button
          type="button"
          className="text-inherit mr-0.5"
          aria-label="Remove"
          title={removeTooltipText}
          onPointerDown={(e) => e.stopPropagation()}
          onClick={(e) => {
            e.stopPropagation();
            onRemove?.();
          }}
        >
          <CancelCircleIcon size="16px" />
        </button>
      ) : showPinnedIcon ? (
        <div className="flex-none">
          <PinIcon size="16px" pinned />
        </div>
      ) : null}

      {readOnly ? (
        <span className="text-inherit w-full select-none truncate flex items-center justify-between gap-x-1 px-0.5">
          {children}
        </span>
      ) : (
        <button
          type="button"
          className="text-inherit w-full select-none truncate flex items-center justify-between gap-x-1 px-0.5"
          aria-label={`Open ${label}`}
          onClick={onToggleOpen}
        >
          {children}
        </button>
      )}
    </div>
  );
}
