// web-common/src/features/workspaces/react/WorkspaceHeader.tsx
// React translation of `layout/workspace/WorkspaceHeader.svelte`. The runtime
// bindings (getIconComponent, ConnectorRefresh/AddModel buttons, WorkspaceBreadcrumbs,
// ExplainAndFix) are exposed as `icon` / `breadcrumbs` / `workspaceControls` /
// `cta` props; the inspector & table visibility toggles are driven by the
// framework-agnostic `workspaces` store (bridged via `useReadable`).
import { useState, type ReactNode } from "react";
import { navigationOpen } from "@statsparrot/web-common/layout/react/store";
import { useReadable } from "@statsparrot/web-common/features/components/charts/react/useReadable";
import { HideSidebarIcon } from "@statsparrot/web-common/layout/react/icons";
import { workspaces } from "@statsparrot/web-common/layout/workspace/workspace-stores";

export default function WorkspaceHeader({
  resourceKind,
  titleInput,
  editable = true,
  showInspectorToggle = true,
  showTableToggle = false,
  hasUnsavedChanges = false,
  filePath,
  showBreadcrumbs = true,
  onTitleChange,
  icon,
  breadcrumbs,
  workspaceControls,
  cta,
}: {
  resourceKind?: string;
  titleInput: string;
  editable?: boolean;
  showInspectorToggle?: boolean;
  showTableToggle?: boolean;
  hasUnsavedChanges?: boolean;
  filePath: string;
  showBreadcrumbs?: boolean;
  onTitleChange?: (title: string) => void;
  icon?: ReactNode;
  breadcrumbs?: ReactNode;
  workspaceControls?: ReactNode;
  cta?: ReactNode;
}) {
  const navOpen = useReadable(navigationOpen) ?? true;
  const [editing, setEditing] = useState(false);
  const [value, setValue] = useState(titleInput);

  const workspaceLayout = workspaces.get<string>(filePath);
  const inspectorVisible =
    useReadable(workspaceLayout.inspector.visible) ?? true;
  const tableVisible = useReadable(workspaceLayout.table.visible) ?? true;

  function handleTitleChange() {
    setEditing(false);
    if (onTitleChange) onTitleChange(value);
  }

  return (
    <header className="flex flex-col py-2 gap-y-2">
      {showBreadcrumbs ? (
        <div
          className={`slide pl-3.5 h-7 flex items-center ${navOpen ? "" : "!pl-10"}`}
        >
          {breadcrumbs ?? <span className="text-fg-muted text-xs">{filePath}</span>}
        </div>
      ) : null}

      <div className="second-level-wrapper px-4 py-2 w-full h-7 flex justify-between gap-x-2 items-center">
        <div
          className={`flex gap-x-1 items-center w-full ${editing ? "" : "truncate"}`}
        >
          <span className="flex-none">{icon}</span>
          {editing || editable === false ? (
            <input
              id="model-title-input"
              className="text-xl font-semibold bg-transparent outline-none w-full"
              value={value}
              disabled={!editable}
              onChange={(e) => setValue(e.target.value)}
              onBlur={handleTitleChange}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleTitleChange();
                if (e.key === "Escape") {
                  setValue(titleInput);
                  setEditing(false);
                }
              }}
              data-testid="workspace-title-input"
            />
          ) : (
            <button
              type="button"
              className="text-xl font-semibold truncate flex items-center gap-x-2"
              onClick={() => setEditing(true)}
              data-testid="workspace-title"
            >
              {titleInput}
              {hasUnsavedChanges ? (
                <span className="size-1.5 rounded-full bg-amber-500" />
              ) : null}
            </button>
          )}
        </div>

        <div className="flex items-center gap-x-2 w-fit flex-none">
          {workspaceControls}
          {cta}

          {showTableToggle ? (
            <button
              type="button"
              className="flex flex-none items-center justify-center p-0 aspect-square h-7 w-7 rounded-[2px] align-middle select-none cursor-pointer"
              aria-label="Toggle table visibility"
              aria-pressed={tableVisible}
              onClick={() => workspaceLayout.table.toggle()}
            >
              <HideBottomPaneIcon size="18px" open={tableVisible} />
            </button>
          ) : null}

          {showInspectorToggle ? (
            <button
              type="button"
              className="flex flex-none items-center justify-center p-0 aspect-square h-7 w-7 rounded-[2px]"
              aria-label="Toggle inspector visibility"
              aria-pressed={inspectorVisible}
              onClick={() => workspaceLayout.inspector.toggle()}
            >
              <HideSidebarIcon size="18px" open={inspectorVisible} />
            </button>
          ) : null}
        </div>
      </div>
    </header>
  );
}

function HideBottomPaneIcon({
  size = "1em",
  open = false,
}: {
  size?: string;
  open?: boolean;
}) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <rect x="3" y="4" width="18" height="14" rx="2" />
      {open ? <path d="M3 12h18" /> : <path d="M3 14h18" />}
    </svg>
  );
}

// web-common/src/layout/workspace/WorkspaceHeader.svelte
<script lang="ts">
  import Button from "@statsparrot/web-common/components/button/Button.svelte";
  import InputWithConfirm from "@statsparrot/web-common/components/forms/InputWithConfirm.svelte";
  import HideBottomPane from "@statsparrot/web-common/components/icons/HideBottomPane.svelte";
  import HideSidebar from "@statsparrot/web-common/components/icons/HideSidebar.svelte";
  import SlidingWords from "@statsparrot/web-common/components/tooltip/SlidingWords.svelte";
  import Tooltip from "@statsparrot/web-common/components/tooltip/Tooltip.svelte";
  import TooltipContent from "@statsparrot/web-common/components/tooltip/TooltipContent.svelte";
  import { getIconComponent } from "@statsparrot/web-common/features/entity-management/resource-icon-mapping";
  import { ResourceKind } from "@statsparrot/web-common/features/entity-management/resource-selectors";
  import CodeToggle, {
    type ViewOption,
  } from "@statsparrot/web-common/features/visual-editing/CodeToggle.svelte";
  import WorkspaceBreadcrumbs from "@statsparrot/web-common/features/workspaces/WorkspaceBreadcrumbs.svelte";
  import type { V1Resource } from "@statsparrot/web-common/runtime-client";
  import { navigationOpen } from "../navigation/Navigation.svelte";
  import { workspaces } from "./workspace-stores";
  import ConnectorRefreshButton from "@statsparrot/web-common/features/connectors/ConnectorRefreshButton.svelte";
  import ConnectorAddModelButton from "@statsparrot/web-common/features/connectors/ConnectorAddModelButton.svelte";
  import type { Snippet } from "svelte";

  let {
    resourceKind,
    resource = undefined,
    titleInput,
    editable = true,
    showInspectorToggle = true,
    showTableToggle = false,
    hasUnsavedChanges,
    filePath,
    codeToggle = false,
    codeToggleViews = undefined,
    showBreadcrumbs = true,
    onTitleChange,
    workspaceControls,
    cta,
  }: {
    resourceKind: ResourceKind | undefined;
    resource?: V1Resource | undefined;
    titleInput: string;
    editable?: boolean;
    showInspectorToggle?: boolean;
    showTableToggle?: boolean;
    hasUnsavedChanges: boolean;
    filePath: string;
    codeToggle?: boolean;
    codeToggleViews?: ViewOption[] | undefined;
    showBreadcrumbs?: boolean;
    onTitleChange?: (title: string) => void;
    workspaceControls?: Snippet<[number]>;
    cta?: Snippet<[number]>;
  } = $props();

  let width: number = $state(0);
  let editing = $state(false);

  let value = $derived(titleInput);
  // Typed as string since some workspaces extend the base view union (e.g. "explore").
  let workspaceLayout = $derived(workspaces.get<string>(filePath));
  let inspectorVisible = $derived(workspaceLayout.inspector.visible);
  let tableVisible = $derived(workspaceLayout.table.visible);
  let view = $derived(workspaceLayout.view);

  // Check if it's a connector by resourceKind or by file path.
  // File path fallback is needed when reconcile fails and resourceKind is unavailable.
  let isConnector = $derived(
    resourceKind === ResourceKind.Connector ||
      (filePath && filePath.startsWith("/connectors/")),
  );

  let IconComponent = $derived(getIconComponent(resourceKind, filePath));
</script>

<header bind:clientWidth={width}>
  {#if showBreadcrumbs}
    <div
      class="slide pl-3.5 h-7 flex items-center"
      class:!pl-10={!$navigationOpen}
    >
      <WorkspaceBreadcrumbs {resource} {filePath} />
    </div>
  {/if}

  <div class="second-level-wrapper">
    <div class="flex gap-x-1 items-center w-full" class:truncate={!editing}>
      {#if codeToggle && resourceKind}
        <CodeToggle
          bind:selectedView={$view}
          {resourceKind}
          views={codeToggleViews}
        />
      {:else}
        <span class="flex-none">
          <IconComponent size="19px" />
        </span>
      {/if}

      <InputWithConfirm
        bind:editing
        size="md"
        {editable}
        id="model-title-input"
        textClass="text-xl font-semibold"
        {value}
        onConfirm={onTitleChange}
        showIndicator={hasUnsavedChanges}
      />
    </div>

    <div class="flex items-center gap-x-2 w-fit flex-none">
      {#if isConnector}
        <ConnectorRefreshButton {resource} {hasUnsavedChanges} />
        <ConnectorAddModelButton {resource} {hasUnsavedChanges} />
      {/if}

      {@render workspaceControls?.(width)}
      <div class="flex-none">
        {@render cta?.(width)}
      </div>

      {#if showTableToggle}
        <Tooltip distance={8}>
          <Button
            type="secondary"
            square
            selected={$tableVisible}
            label="Toggle table visibility"
            onClick={workspaceLayout.table.toggle}
          >
            <HideBottomPane size="18px" open={$tableVisible} />
          </Button>
          <TooltipContent slot="tooltip-content">
            <SlidingWords active={$tableVisible} reverse>
              results preview
            </SlidingWords>
          </TooltipContent>
        </Tooltip>
      {/if}

      {#if showInspectorToggle}
        <Tooltip distance={8}>
          <Button
            type="secondary"
            square
            selected={$inspectorVisible}
            label="Toggle inspector visibility"
            onClick={workspaceLayout.inspector.toggle}
          >
            <HideSidebar open={$inspectorVisible} size="18px" />
          </Button>

          <TooltipContent slot="tooltip-content">
            <SlidingWords
              active={$inspectorVisible}
              direction="horizontal"
              reverse
            >
              inspector
            </SlidingWords>
          </TooltipContent>
        </Tooltip>
      {/if}
    </div>
  </div>
</header>

<style lang="postcss">
  .second-level-wrapper {
    @apply px-4 py-2 w-full h-7;
    @apply flex justify-between gap-x-2;
    @apply items-center;
  }

  header {
    @apply flex flex-col py-2 gap-y-2;
  }
</style>
