// web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
<script lang="ts">
  import FormattedDataType from "@statsparrot/web-common/components/data-types/FormattedDataType.svelte";
  import PercentageChange from "@statsparrot/web-common/components/data-types/PercentageChange.svelte";
  import ExternalLink from "@statsparrot/web-common/components/icons/ExternalLink.svelte";
  import LeaderboardCell from "@statsparrot/web-common/features/dashboards/leaderboard/LeaderboardCell.svelte";
  import { clamp } from "@statsparrot/web-common/lib/clamp";
  import { formatMeasurePercentageDifference } from "@statsparrot/web-common/lib/number-formatting/percentage-formatter";
  import { numberPartsToString } from "@statsparrot/web-common/lib/number-formatting/utils/number-parts-utils";
  import { slide } from "svelte/transition";
  import { makeHref } from "@statsparrot/web-common/features/dashboards/dashboard-utils";
  import { type LeaderboardItemData } from "./leaderboard-utils";
  import {
    COMPARISON_COLUMN_WIDTH,
    DEFAULT_COLUMN_WIDTH,
    deltaColumn,
    MEASURES_PADDING,
    valueColumn,
  } from "./leaderboard-widths";
  import LeaderboardItemFilterIcon from "./LeaderboardItemFilterIcon.svelte";
  import LongBarZigZag from "./LongBarZigZag.svelte";

  export let itemData: LeaderboardItemData;
  export let dimensionName: string;
  export let borderTop = false;
  export let borderBottom = false;
  export let isBeingCompared: boolean;
  export let filterExcludeMode: boolean;
  export let atLeastOneActive: boolean;
  export let isTimeComparisonActive: boolean;
  export let leaderboardMeasureNames: string[] = [];
  // Measures that render context columns; see Leaderboard.svelte.
  export let measuresWithContext: Set<string>;
  export let isValidPercentOfTotal: (measureName: string) => boolean;
  export let dimensionColumnWidth: number;
  export let maxValues: Record<string, number> = {};
  export let toggleDimensionValueSelection: (
    dimensionName: string,
    dimensionValue: string,
    keepPillVisible?: boolean | undefined,
    isExclusiveFilter?: boolean | undefined,
  ) => void;
  export let formatters: Record<
    string,
    (value: number | string | null | undefined) => string | null | undefined
  >;
  export let tooltipFormatters: Record<
    string,
    (value: number | string | null | undefined) => string | null | undefined
  >;
  export let lowerIsBetterMap: Record<string, boolean> = {};

  let hovered = false;
  let valueRect = new DOMRect(0, 0, DEFAULT_COLUMN_WIDTH);
  let deltaRect = new DOMRect(0, 0, COMPARISON_COLUMN_WIDTH);
  let parent: HTMLTableRowElement;

  $: ({
    dimensionValue,
    selectedIndex,
    values,
    pctOfTotals,
    prevValues,
    deltaRels,
    deltaAbs: deltaAbsMap,
    uri,
  } = itemData);

  $: selected = selectedIndex >= 0;

  // Super important special case: if there is not at least one "active" (selected) value,
  // we need to set *all* items to be included, because by default if a user has not
  // selected any values, we assume they want all values included in all calculations.
  $: excluded = atLeastOneActive
    ? (filterExcludeMode && selected) || (!filterExcludeMode && !selected)
    : false;

  $: previousValueString =
    leaderboardMeasureNames.length === 1 &&
    prevValues[leaderboardMeasureNames[0]] !== undefined &&
    prevValues[leaderboardMeasureNames[0]] !== null
      ? formatters[leaderboardMeasureNames[0]]?.(
          prevValues[leaderboardMeasureNames[0]] as number,
        )
      : undefined;

  $: href = makeHref(uri, dimensionValue);

  $: deltaElementWidth = deltaRect?.width;
  $: valueElementWith = valueRect?.width;

  $: valueColumn.update(valueElementWith);
  $: deltaColumn.update(deltaElementWidth);

  $: barColor = excluded
    ? "var(--surface-active)"
    : selected || hovered
      ? "var(--color-theme-200)"
      : "var(--color-theme-100)";

  // Calculate bar width excluding dimension column
  $: barWidth =
    $valueColumn +
    (leaderboardMeasureNames.length === 1
      ? dimensionColumnWidth
      : -MEASURES_PADDING);
  // Calculate bar lengths based on max value. For percent-of-total measure, this will be the total.
  $: barLengths = Object.fromEntries(
    Object.entries(values).map(([name, value]) => {
      const maxValue = maxValues[name];
      if (!value || !maxValue || maxValue <= 0) return [name, 0];
      // Calculate relative magnitude: current value / max value * available bar width
      return [name, (Math.abs(value) / maxValue) * barWidth];
    }),
  );

  $: totalBarLength = Object.values(barLengths).reduce(
    (sum, length) => sum + length,
    0,
  );

  $: showZigZags = Object.fromEntries(
    Object.entries(barLengths).map(([name, length]) => [
      name,
      length > barWidth,
    ]),
  );

  $: measureCellBarLengths = Object.fromEntries(
    Object.entries(barLengths).map(([name, length]) => [
      name,
      clamp(0, length, $valueColumn),
    ]),
  );

  $: dimensionGradients =
    leaderboardMeasureNames.length === 1
      ? `linear-gradient(to right, ${barColor} ${Math.min(dimensionColumnWidth, totalBarLength)}px, transparent ${Math.min(dimensionColumnWidth, totalBarLength)}px)`
      : undefined;

  $: measureGradients =
    leaderboardMeasureNames.length === 1
      ? `linear-gradient(to right, ${barColor} ${Math.max(0, totalBarLength - dimensionColumnWidth)}px, transparent ${Math.max(0, totalBarLength - dimensionColumnWidth)}px)`
      : undefined;

  $: measureGradientMap =
    leaderboardMeasureNames.length === 1
      ? undefined
      : Object.fromEntries(
          leaderboardMeasureNames.map((name) => {
            const length = measureCellBarLengths[name];
            return [
              name,
              length
                ? `linear-gradient(to right, transparent ${MEASURES_PADDING}px, ${barColor} ${MEASURES_PADDING}px, ${barColor} ${length + MEASURES_PADDING}px, transparent ${length + MEASURES_PADDING}px)`
                : undefined,
            ];
          }),
        );

  $: dimensionCellClass = `relative size-full flex flex-none justify-between items-center leaderboard-label ${
    atLeastOneActive ? "cursor-pointer" : ""
  } ${excluded ? "text-fg-disabled" : ""} ${!excluded && selected ? "text-fg-primary font-semibold" : ""}`;

  function onDimensionCellClick(e: MouseEvent) {
    // Check if user has selected text
    const selection = window.getSelection();
    if (selection && selection.toString().length > 0) {
      // User has selected text, don't trigger row selection
      return;
    }

    // If no text is selected, proceed with normal click behavior
    toggleDimensionValueSelection(
      dimensionName,
      dimensionValue,
      false,
      e.ctrlKey || e.metaKey,
    );
  }
</script>

<tr
  bind:this={parent}
  class:border-b={borderBottom}
  class:border-t={borderTop}
  class="relative"
  onpointerover={() => (hovered = true)}
  onpointerout={() => (hovered = false)}
  onclick={(e) => {
    if (e.shiftKey) return;
    onDimensionCellClick(e);
  }}
>
  <td data-comparison-cell>
    <LeaderboardItemFilterIcon
      {excluded}
      {isBeingCompared}
      selectionIndex={itemData?.selectedIndex}
    />
  </td>
  <LeaderboardCell
    value={dimensionValue}
    cellType="dimension"
    className={dimensionCellClass}
    background={dimensionGradients}
  >
    <span class="truncate select-text">
      <FormattedDataType value={dimensionValue} truncate />
    </span>

    {#if previousValueString && hovered}
      <span
        class="opacity-50 whitespace-nowrap font-normal"
        transition:slide={{ axis: "x", duration: 200 }}
      >
        {previousValueString} →
      </span>
    {/if}

    {#if href}
      <span class="external-link-wrapper">
        <a
          target="_blank"
          rel="noopener noreferrer"
          {href}
          title={href}
          onclick={(e) => {
            e.stopPropagation();
          }}
          class:hovered
        >
          <ExternalLink className="fill-primary-600" />
        </a>
      </span>
    {/if}
  </LeaderboardCell>

  {#each leaderboardMeasureNames as measureName, i (i)}
    <LeaderboardCell
      value={values[measureName]?.toString() || ""}
      tooltipValue={values[measureName] != null
        ? (tooltipFormatters[measureName]?.(values[measureName]) ??
          values[measureName]?.toString() ??
          "")
        : ""}
      cellType="measure"
      background={leaderboardMeasureNames.length === 1
        ? measureGradients
        : measureGradientMap?.[measureName]}
    >
      <div class="w-fit ml-auto bg-transparent" bind:contentRect={valueRect}>
        <FormattedDataType
          type="INTEGER"
          value={values[measureName]
            ? formatters[measureName]?.(values[measureName])
            : null}
        />
      </div>

      {#if showZigZags[measureName] && !isTimeComparisonActive && !isValidPercentOfTotal(measureName)}
        <LongBarZigZag />
      {/if}
    </LeaderboardCell>

    {#if isValidPercentOfTotal(measureName) && measuresWithContext.has(measureName)}
      <LeaderboardCell
        value={pctOfTotals[measureName]?.toString() || ""}
        tooltipValue={pctOfTotals[measureName] != null
          ? numberPartsToString(
              formatMeasurePercentageDifference(pctOfTotals[measureName]),
            )
          : ""}
        cellType="comparison"
      >
        <PercentageChange
          value={pctOfTotals[measureName]}
          color="text-fg-secondary"
        />
        {#if showZigZags[measureName]}
          <LongBarZigZag />
        {/if}
      </LeaderboardCell>
    {/if}

    {#if isTimeComparisonActive && measuresWithContext.has(measureName)}
      <LeaderboardCell
        value={deltaAbsMap[measureName]?.toString() || ""}
        tooltipValue={deltaAbsMap[measureName] != null
          ? (tooltipFormatters[measureName]?.(deltaAbsMap[measureName]) ??
            deltaAbsMap[measureName]?.toString() ??
            "")
          : ""}
        cellType="comparison"
      >
        <div class="w-fit ml-auto bg-transparent" bind:contentRect={deltaRect}>
          <FormattedDataType
            color="text-fg-secondary"
            type="INTEGER"
            value={deltaAbsMap[measureName]
              ? formatters[measureName]?.(deltaAbsMap[measureName])
              : null}
            customStyle={deltaAbsMap[measureName] !== null &&
            (lowerIsBetterMap[measureName]
              ? deltaAbsMap[measureName] > 0
              : deltaAbsMap[measureName] < 0)
              ? "text-kpi-negative"
              : deltaAbsMap[measureName] !== null &&
                  (lowerIsBetterMap[measureName]
                    ? deltaAbsMap[measureName] < 0
                    : deltaAbsMap[measureName] > 0)
                ? "text-kpi-positive"
                : ""}
            truncate={true}
          />
        </div>
      </LeaderboardCell>
    {/if}

    {#if isTimeComparisonActive && measuresWithContext.has(measureName)}
      <LeaderboardCell
        value={deltaRels[measureName]?.toString() || ""}
        tooltipValue={deltaRels[measureName] != null
          ? numberPartsToString(
              formatMeasurePercentageDifference(deltaRels[measureName]),
            )
          : ""}
        cellType="comparison"
      >
        <PercentageChange
          value={deltaRels[measureName]
            ? formatMeasurePercentageDifference(deltaRels[measureName])
            : null}
          color="text-fg-secondary"
          lowerIsBetter={lowerIsBetterMap[measureName] ?? false}
        />
        {#if showZigZags[measureName]}
          <LongBarZigZag />
        {/if}
      </LeaderboardCell>
    {/if}
  {/each}
</tr>

<style lang="postcss">
  td {
    @apply h-[22px] p-0 px-1 truncate text-right;
  }

  tr {
    @apply cursor-pointer;
    max-height: 22px;
  }

  tr:hover {
    @apply bg-popover-accent;
  }

  td[data-comparison-cell] {
    @apply bg-transparent px-1 truncate;
  }

  tr:hover td[data-comparison-cell] {
    @apply bg-popover-accent;
  }

  .external-link-wrapper a {
    opacity: 0;
    position: absolute;
    right: 0;
    top: 0;
    height: 20px;
    width: 20px;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .external-link-wrapper a.hovered {
    opacity: 0.7;
    pointer-events: auto;
    backdrop-filter: blur(2px);
    -webkit-backdrop-filter: blur(2px);
  }
</style>

// web-common/src/features/dashboards/leaderboard/react/LeaderboardRow.tsx
/**
 * React translation of `features/dashboards/leaderboard/LeaderboardRow.svelte`.
 *
 * Renders a single leaderboard row: the comparison gutter cell, the dimension
 * cell (with its relative-magnitude gradient bar / external-link), and one cell
 * per measure (value, percent-of-total, delta absolute, delta percent) with the
 * matching gradient bars and zig-zag overflow indicators.
 *
 * The Svelte `bind:contentRect` measurements that drive the shared
 * `valueColumn` / `deltaColumn` width stores are reproduced with `ResizeObserver`
 * so the row communicates the actual width of its value/delta cells just as the
 * Svelte version does.
 */
import { useEffect, useRef, useState } from "react";
import type { MouseEvent } from "react";
import { clamp } from "@statsparrot/web-common/lib/clamp";
import { makeHref } from "@statsparrot/web-common/features/dashboards/dashboard-utils";
import { formatMeasurePercentageDifference } from "@statsparrot/web-common/lib/number-formatting/percentage-formatter";
import { numberPartsToString } from "@statsparrot/web-common/lib/number-formatting/utils/number-parts-utils";
import { useReadable } from "@statsparrot/web-common/features/components/charts/react/useReadable";
import type { LeaderboardItemData } from "../leaderboard-utils";
import {
  COMPARISON_COLUMN_WIDTH,
  DEFAULT_COLUMN_WIDTH,
  deltaColumn,
  MEASURES_PADDING,
  valueColumn,
} from "../leaderboard-widths";
import { ExternalLinkIcon } from "./icons";
import {
  FormattedDataType,
  LongBarZigZag,
  PercentageChange,
} from "./primitives";
import LeaderboardCell from "./LeaderboardCell";
import LeaderboardItemFilterIcon from "./LeaderboardItemFilterIcon";

export interface LeaderboardRowProps {
  itemData: LeaderboardItemData;
  dimensionName: string;
  borderTop?: boolean;
  borderBottom?: boolean;
  isBeingCompared: boolean;
  filterExcludeMode: boolean;
  atLeastOneActive: boolean;
  isTimeComparisonActive: boolean;
  leaderboardMeasureNames?: string[];
  // Measures that render context columns; see Leaderboard.tsx.
  measuresWithContext: Set<string>;
  isValidPercentOfTotal: (measureName: string) => boolean;
  dimensionColumnWidth: number;
  maxValues?: Record<string, number>;
  toggleDimensionValueSelection: (
    dimensionName: string,
    dimensionValue: string,
    keepPillVisible?: boolean | undefined,
    isExclusiveFilter?: boolean | undefined,
  ) => void;
  formatters: Record<
    string,
    (value: number | string | null | undefined) => string | null | undefined
  >;
  tooltipFormatters: Record<
    string,
    (value: number | string | null | undefined) => string | null | undefined
  >;
  lowerIsBetterMap?: Record<string, boolean>;
}

export default function LeaderboardRow({
  itemData,
  dimensionName,
  borderTop = false,
  borderBottom = false,
  isBeingCompared,
  filterExcludeMode,
  atLeastOneActive,
  isTimeComparisonActive,
  leaderboardMeasureNames = [],
  measuresWithContext,
  isValidPercentOfTotal,
  dimensionColumnWidth,
  maxValues = {},
  toggleDimensionValueSelection,
  formatters,
  tooltipFormatters,
  lowerIsBetterMap = {},
}: LeaderboardRowProps) {
  const [hovered, setHovered] = useState(false);
  const valueRef = useRef<HTMLDivElement>(null);
  const deltaRef = useRef<HTMLDivElement>(null);

  const valueColumnWidth = useReadable(valueColumn) ?? DEFAULT_COLUMN_WIDTH;
  const deltaColumnWidth = useReadable(deltaColumn) ?? COMPARISON_COLUMN_WIDTH;

  const {
    dimensionValue,
    selectedIndex,
    values,
    pctOfTotals,
    prevValues,
    deltaRels,
    deltaAbs: deltaAbsMap,
    uri,
  } = itemData;

  const selected = selectedIndex >= 0;

  // If there is not at least one "active" (selected) value, all items are
  // included (default behavior when no values are selected).
  const excluded = atLeastOneActive
    ? (filterExcludeMode && selected) || (!filterExcludeMode && !selected)
    : false;

  const previousValueString =
    leaderboardMeasureNames.length === 1 &&
    prevValues[leaderboardMeasureNames[0]] !== undefined &&
    prevValues[leaderboardMeasureNames[0]] !== null
      ? formatters[leaderboardMeasureNames[0]]?.(
          prevValues[leaderboardMeasureNames[0]] as number,
        )
      : undefined;

  const href = makeHref(uri, dimensionValue);

  // Report the width of this row's value / delta cells to the shared stores.
  useEffect(() => {
    const el = valueRef.current;
    if (!el) return;
    const update = () => valueColumn.update(el.getBoundingClientRect().width);
    update();
    const ro = new ResizeObserver(update);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  useEffect(() => {
    const el = deltaRef.current;
    if (!el) return;
    const update = () => deltaColumn.update(el.getBoundingClientRect().width);
    update();
    const ro = new ResizeObserver(update);
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const barColor = excluded
    ? "var(--surface-active)"
    : selected || hovered
      ? "var(--color-theme-200)"
      : "var(--color-theme-100)";

  // Bar width excluding the dimension column.
  const barWidth =
    valueColumnWidth +
    (leaderboardMeasureNames.length === 1
      ? dimensionColumnWidth
      : -MEASURES_PADDING);

  const barLengths = Object.fromEntries(
    Object.entries(values).map(([name, value]) => {
      const maxValue = maxValues[name];
      if (!value || !maxValue || maxValue <= 0) return [name, 0];
      return [name, (Math.abs(value) / maxValue) * barWidth];
    }),
  );

  const totalBarLength = Object.values(barLengths).reduce(
    (sum, length) => sum + (length as number),
    0,
  );

  const showZigZags = Object.fromEntries(
    Object.entries(barLengths).map(([name, length]) => [
      name,
      (length as number) > barWidth,
    ]),
  );

  const measureCellBarLengths = Object.fromEntries(
    Object.entries(barLengths).map(([name, length]) => [
      name,
      clamp(0, length as number, valueColumnWidth),
    ]),
  );

  const singleMeasure = leaderboardMeasureNames.length === 1;

  const dimensionGradients = singleMeasure
    ? `linear-gradient(to right, ${barColor} ${Math.min(dimensionColumnWidth, totalBarLength)}px, transparent ${Math.min(dimensionColumnWidth, totalBarLength)}px)`
    : undefined;

  const measureGradients = singleMeasure
    ? `linear-gradient(to right, ${barColor} ${Math.max(0, totalBarLength - dimensionColumnWidth)}px, transparent ${Math.max(0, totalBarLength - dimensionColumnWidth)}px)`
    : undefined;

  const measureGradientMap = singleMeasure
    ? undefined
    : Object.fromEntries(
        leaderboardMeasureNames.map((name) => {
          const length = measureCellBarLengths[name] as number;
          return [
            name,
            length
              ? `linear-gradient(to right, transparent ${MEASURES_PADDING}px, ${barColor} ${MEASURES_PADDING}px, ${barColor} ${length + MEASURES_PADDING}px, transparent ${length + MEASURES_PADDING}px)`
              : undefined,
          ];
        }),
      );

  const dimensionCellClass = `relative size-full flex flex-none justify-between items-center leaderboard-label ${
    atLeastOneActive ? "cursor-pointer" : ""
  } ${excluded ? "text-fg-disabled" : ""} ${
    !excluded && selected ? "text-fg-primary font-semibold" : ""
  }`;

  function onDimensionCellClick(e: MouseEvent) {
    // Check if user has selected text.
    const selection = window.getSelection();
    if (selection && selection.toString().length > 0) {
      // User has selected text, don't trigger row selection.
      return;
    }
    toggleDimensionValueSelection(
      dimensionName,
      dimensionValue,
      false,
      e.ctrlKey || e.metaKey,
    );
  }

  return (
    <tr
      className={`relative ${borderBottom ? "border-b" : ""} ${borderTop ? "border-t" : ""}`}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
      onClick={(e) => {
        if (e.shiftKey) return;
        onDimensionCellClick(e);
      }}
    >
      <td data-comparison-cell>
        <LeaderboardItemFilterIcon
          excluded={excluded}
          isBeingCompared={isBeingCompared}
          selectionIndex={itemData?.selectedIndex}
        />
      </td>
      <LeaderboardCell
        value={dimensionValue}
        cellType="dimension"
        className={dimensionCellClass}
        background={dimensionGradients}
      >
        <span className="truncate select-text">
          <FormattedDataType value={dimensionValue} truncate />
        </span>

        {previousValueString && hovered ? (
          <span className="opacity-50 whitespace-nowrap font-normal">
            {previousValueString} →
          </span>
        ) : null}

        {href ? (
          <span className="external-link-wrapper relative">
            <a
              target="_blank"
              rel="noopener noreferrer"
              href={href}
              title={href}
              onClick={(e) => {
                e.stopPropagation();
              }}
              className={hovered ? "hovered" : ""}
            >
              <ExternalLinkIcon className="fill-primary-600" />
            </a>
          </span>
        ) : null}
      </LeaderboardCell>

      {leaderboardMeasureNames.map((measureName) => (
        <LeaderboardCell
          key={measureName}
          value={values[measureName]?.toString() || ""}
          tooltipValue={
            values[measureName] != null
              ? (tooltipFormatters[measureName]?.(values[measureName]) ??
                values[measureName]?.toString() ??
                "")
              : ""
          }
          cellType="measure"
          background={
            singleMeasure
              ? measureGradients
              : measureGradientMap?.[measureName]
          }
        >
          <div className="w-fit ml-auto bg-transparent" ref={valueRef}>
            <FormattedDataType
              type="INTEGER"
              value={values[measureName] ? formatters[measureName]?.(values[measureName]) : null}
            />
          </div>

          {showZigZags[measureName] &&
          !isTimeComparisonActive &&
          !isValidPercentOfTotal(measureName) ? (
            <LongBarZigZag />
          ) : null}
        </LeaderboardCell>
      ))}

      {leaderboardMeasureNames.map((measureName) => {
        if (
          !isValidPercentOfTotal(measureName) ||
          !measuresWithContext.has(measureName)
        ) {
          return null;
        }
        return (
          <LeaderboardCell
            key={`pct-${measureName}`}
            value={pctOfTotals[measureName]?.toString() || ""}
            tooltipValue={
              pctOfTotals[measureName] != null
                ? numberPartsToString(
                    formatMeasurePercentageDifference(pctOfTotals[measureName]),
                  )
                : ""
            }
            cellType="comparison"
          >
            <PercentageChange
              value={pctOfTotals[measureName]}
              color="text-fg-secondary"
            />
            {showZigZags[measureName] ? <LongBarZigZag /> : null}
          </LeaderboardCell>
        );
      })}

      {leaderboardMeasureNames.map((measureName) => {
        if (
          !isTimeComparisonActive ||
          !measuresWithContext.has(measureName)
        ) {
          return null;
        }
        return (
          <LeaderboardCell
            key={`deltaAbs-${measureName}`}
            value={deltaAbsMap[measureName]?.toString() || ""}
            tooltipValue={
              deltaAbsMap[measureName] != null
                ? (tooltipFormatters[measureName]?.(deltaAbsMap[measureName]) ??
                  deltaAbsMap[measureName]?.toString() ??
                  "")
                : ""
            }
            cellType="comparison"
          >
            <div className="w-fit ml-auto bg-transparent" ref={deltaRef}>
              <FormattedDataType
                color="text-fg-secondary"
                type="INTEGER"
                value={
                  deltaAbsMap[measureName]
                    ? formatters[measureName]?.(deltaAbsMap[measureName])
                    : null
                }
                customStyle={
                  deltaAbsMap[measureName] !== null &&
                  (lowerIsBetterMap[measureName]
                    ? deltaAbsMap[measureName] > 0
                    : deltaAbsMap[measureName] < 0)
                    ? "text-kpi-negative"
                    : deltaAbsMap[measureName] !== null &&
                        (lowerIsBetterMap[measureName]
                          ? deltaAbsMap[measureName] < 0
                          : deltaAbsMap[measureName] > 0)
                      ? "text-kpi-positive"
                      : ""
                }
                truncate={true}
              />
            </div>
          </LeaderboardCell>
        );
      })}

      {leaderboardMeasureNames.map((measureName) => {
        if (
          !isTimeComparisonActive ||
          !measuresWithContext.has(measureName)
        ) {
          return null;
        }
        return (
          <LeaderboardCell
            key={`deltaRel-${measureName}`}
            value={deltaRels[measureName]?.toString() || ""}
            tooltipValue={
              deltaRels[measureName] != null
                ? numberPartsToString(
                    formatMeasurePercentageDifference(deltaRels[measureName]),
                  )
                : ""
            }
            cellType="comparison"
          >
            <PercentageChange
              value={
                deltaRels[measureName]
                  ? formatMeasurePercentageDifference(deltaRels[measureName])
                  : null
              }
              color="text-fg-secondary"
              lowerIsBetter={lowerIsBetterMap[measureName] ?? false}
            />
            {showZigZags[measureName] ? <LongBarZigZag /> : null}
          </LeaderboardCell>
        );
      })}
    </tr>
  );
}
