// web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte
<script lang="ts">
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
  import ArrowDown from "@statsparrot/web-common/components/icons/ArrowDown.svelte";
  import Spacer from "@statsparrot/web-common/components/icons/Spacer.svelte";
  import Tooltip from "@statsparrot/web-common/components/tooltip/Tooltip.svelte";
  import TooltipContent from "@statsparrot/web-common/components/tooltip/TooltipContent.svelte";
  import DelayedSpinner from "@statsparrot/web-common/features/entity-management/DelayedSpinner.svelte";
  import Resizer from "@statsparrot/web-common/layout/Resizer.svelte";
  import { fly } from "svelte/transition";
  import DeltaChange from "../dimension-table/DeltaChange.svelte";
  import DeltaChangePercentage from "../dimension-table/DeltaChangePercentage.svelte";
  import PercentOfTotal from "../dimension-table/PercentOfTotal.svelte";
  import { SortType } from "../proto-state/derived-types";
  import DimensionCompareMenu from "./DimensionCompareMenu.svelte";
  import {
    DEFAULT_DIMENSION_COLUMN_WIDTH,
    MAX_DIMENSION_COLUMN_WIDTH,
    MIN_DIMENSION_COLUMN_WIDTH,
  } from "./leaderboard-widths";

  export let dimensionName: string;
  export let isFetching: boolean;
  export let isValidPercentOfTotal: (measureName: string) => boolean;
  export let isTimeComparisonActive: boolean;
  export let isBeingCompared: boolean;
  export let sortedAscending: boolean;
  export let displayName: string;
  export let dimensionDescription: string;
  export let hovered: boolean;
  export let sortType: SortType;
  export let allowDimensionComparison: boolean;
  export let allowExpandTable: boolean;
  export let leaderboardMeasureNames: string[] = [];
  export let leaderboardSortByMeasureName: string | null;
  // Measures that render context columns; see Leaderboard.svelte.
  export let measuresWithContext: Set<string>;
  export let toggleSort: (sortType: SortType, measureName?: string) => void;
  export let setPrimaryDimension: (dimensionName: string) => void;
  export let toggleComparisonDimension: (
    dimensionName: string | undefined,
  ) => void;
  export let measureLabel: (measureName: string) => string;
  export let dimensionColumnWidth: number;
  export let onDimensionColumnResize: ((width: number) => void) | null = null;
  // Height of the whole leaderboard table, so the resize handle can span all
  // rows instead of just the header cell.
  export let tableHeight = 0;
</script>

<thead>
  <tr>
    <th
      aria-label={m.dashboard_comparison_column_aria()}
      class="grid place-content-center"
    >
      {#if isFetching}
        <DelayedSpinner isLoading={isFetching} size="16px" />
      {:else if allowDimensionComparison && (hovered || isBeingCompared)}
        <DimensionCompareMenu
          {dimensionName}
          {isBeingCompared}
          {toggleComparisonDimension}
        />
      {:else}
        <Spacer size="14px" />
      {/if}
    </th>

    <th data-dimension-header class:resizable={!!onDimensionColumnResize}>
      <Tooltip location="top">
        <button
          disabled={!allowExpandTable}
          class="text-fg-muted text-left {allowExpandTable
            ? 'hover:text-theme-700'
            : ''}"
          aria-label={m.dashboard_open_dimension_details_aria()}
          onclick={() => setPrimaryDimension(dimensionName)}
        >
          <span class="line-clamp-2">{displayName}</span>
        </button>
        <TooltipContent slot="tooltip-content" maxWidth="280px">
          <div
            class="pointer-events-none items-baseline"
            aria-label="tooltip-name"
          >
            {displayName}
          </div>
          {#if dimensionDescription}
            <div
              class="grid gap-x-2 pointer-events-none pt-1 pb-1 items-baseline"
              style="grid-template-columns: auto max-content"
              style:min-width="200px"
            >
              <div
                class="text-fg-inverse/70 justify-self-start"
                style:max-width="280px"
                aria-label="tooltip-name-description"
              >
                {dimensionDescription}
              </div>
            </div>
          {/if}
        </TooltipContent>
      </Tooltip>

      {#if onDimensionColumnResize}
        <div class="resizer-container" style:height="{tableHeight}px">
          <Resizer
            side="right"
            direction="EW"
            min={MIN_DIMENSION_COLUMN_WIDTH}
            max={MAX_DIMENSION_COLUMN_WIDTH}
            basis={DEFAULT_DIMENSION_COLUMN_WIDTH}
            dimension={dimensionColumnWidth}
            onUpdate={onDimensionColumnResize}
          >
            <div class="resize-bar"></div>
          </Resizer>
        </div>
      {/if}
    </th>

    {#each leaderboardMeasureNames as measureName, index (index)}
      <th data-measure-header>
        <button
          aria-label={m.dashboard_sort_by_value_aria()}
          onclick={() => {
            toggleSort(SortType.VALUE, measureName);
          }}
          class="font-normal text-right"
        >
          <span
            class="measure-label line-clamp-2 text-fg-muted"
            title={measureLabel(measureName)}
          >
            {#if leaderboardMeasureNames.length > 1}
              {measureLabel(measureName)}
            {:else}
              #
            {/if}
          </span>
          {#if measureName === leaderboardSortByMeasureName && sortType === SortType.VALUE}
            <div class="text-fg-muted">
              {#if sortedAscending}
                <div in:fly|global={{ duration: 200, y: 8 }} style:opacity={1}>
                  <ArrowDown flip />
                </div>
              {:else}
                <div in:fly|global={{ duration: 200, y: -8 }} style:opacity={1}>
                  <ArrowDown />
                </div>
              {/if}
            </div>
          {/if}
        </button>
      </th>

      {#if isValidPercentOfTotal(measureName) && measuresWithContext.has(measureName)}
        <th data-percent-of-total-header>
          <button
            aria-label={m.dashboard_sort_by_percent_total_aria()}
            onclick={() => toggleSort(SortType.PERCENT, measureName)}
          >
            <PercentOfTotal />
            {#if sortType === SortType.PERCENT && measureName === leaderboardSortByMeasureName}
              <div class="text-fg-muted">
                {#if sortedAscending}
                  <div
                    in:fly|global={{ duration: 200, y: 8 }}
                    style:opacity={1}
                  >
                    <ArrowDown flip />
                  </div>
                {:else}
                  <div
                    in:fly|global={{ duration: 200, y: -8 }}
                    style:opacity={1}
                  >
                    <ArrowDown />
                  </div>
                {/if}
              </div>
            {/if}
          </button>
        </th>
      {/if}

      {#if isTimeComparisonActive && measuresWithContext.has(measureName)}
        <th data-absolute-change-header>
          <button
            aria-label={m.dashboard_sort_by_absolute_change_aria()}
            onclick={() => toggleSort(SortType.DELTA_ABSOLUTE, measureName)}
          >
            <DeltaChange />
            {#if sortType === SortType.DELTA_ABSOLUTE && measureName === leaderboardSortByMeasureName}
              <div class="text-fg-muted">
                {#if sortedAscending}
                  <div
                    in:fly|global={{ duration: 200, y: 8 }}
                    style:opacity={1}
                  >
                    <ArrowDown flip />
                  </div>
                {:else}
                  <div
                    in:fly|global={{ duration: 200, y: -8 }}
                    style:opacity={1}
                  >
                    <ArrowDown />
                  </div>
                {/if}
              </div>
            {/if}
          </button>
        </th>
      {/if}

      {#if isTimeComparisonActive && measuresWithContext.has(measureName)}
        <th data-percent-change-header>
          <button
            aria-label={m.dashboard_sort_by_percent_change_aria()}
            onclick={() => toggleSort(SortType.DELTA_PERCENT, measureName)}
          >
            <DeltaChangePercentage />
            {#if sortType === SortType.DELTA_PERCENT && measureName === leaderboardSortByMeasureName}
              <div class="text-fg-muted">
                {#if sortedAscending}
                  <div
                    in:fly|global={{ duration: 200, y: 8 }}
                    style:opacity={1}
                  >
                    <ArrowDown flip />
                  </div>
                {:else}
                  <div
                    in:fly|global={{ duration: 200, y: -8 }}
                    style:opacity={1}
                  >
                    <ArrowDown />
                  </div>
                {/if}
              </div>
            {/if}
          </button>
        </th>
      {/if}
    {/each}
  </tr>
</thead>

<style lang="postcss">
  button {
    @apply px-2 flex items-center justify-start size-full;
  }

  th {
    @apply p-0 text-right h-8;
  }

  th[data-dimension-header] {
    /* z-40 keeps the resize handle (which hangs below the header, down the
       whole column) above the rows' sticky dimension cells (z-30). */
    @apply sticky left-0 z-40 bg-surface-background text-left;
  }

  /* Visible separator at the column boundary, marking where to pick up the
     resize handle (same as the expanded dimension table). */
  th[data-dimension-header].resizable {
    @apply border-r;
  }

  .resizer-container {
    @apply absolute top-0 right-0 w-0 z-50;
  }

  .resize-bar {
    @apply bg-primary-500 w-1 h-full;
  }

  th:not(:first-of-type) {
    @apply border-b;
  }

  th:not(:nth-of-type(2)) button {
    @apply justify-end;
  }
</style>

// web-common/src/features/dashboards/leaderboard/react/LeaderboardHeader.tsx
/**
 * React translation of `features/dashboards/leaderboard/LeaderboardHeader.svelte`.
 *
 * Renders the leaderboard `<thead>`: the comparison gutter (spinner / compare
 * menu / spacer), the sticky dimension header (with tooltip + optional resize
 * handle), and one sortable header column per measure (value, percent-of-total,
 * delta absolute, delta percent). The Svelte `in:fly` entrance transitions are
 * dropped (the arrows render statically); the scoped `<style>` blocks are folded
 * into `className`.
 */
import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
import { SortType } from "../../proto-state/derived-types";
import {
  DEFAULT_DIMENSION_COLUMN_WIDTH,
  MAX_DIMENSION_COLUMN_WIDTH,
  MIN_DIMENSION_COLUMN_WIDTH,
} from "../leaderboard-widths";
import {
  ArrowDownIcon,
  CompareIcon,
  DeltaChangeIcon,
  DeltaChangePercentageIcon,
  PercentOfTotalIcon,
  SpacerIcon,
} from "./icons";
import { DelayedSpinner, Resizer, Tooltip } from "./primitives";

export interface LeaderboardHeaderProps {
  dimensionName: string;
  isFetching: boolean;
  isValidPercentOfTotal: (measureName: string) => boolean;
  isTimeComparisonActive: boolean;
  isBeingCompared: boolean;
  sortedAscending: boolean;
  displayName: string;
  dimensionDescription: string;
  hovered: boolean;
  sortType: SortType;
  allowDimensionComparison: boolean;
  allowExpandTable: boolean;
  leaderboardMeasureNames: string[];
  leaderboardSortByMeasureName: string | null;
  // Measures that render context columns; see Leaderboard.tsx.
  measuresWithContext: Set<string>;
  toggleSort: (sortType: SortType, measureName?: string) => void;
  setPrimaryDimension: (dimensionName: string) => void;
  toggleComparisonDimension: (dimensionName: string | undefined) => void;
  measureLabel: (measureName: string) => string;
  dimensionColumnWidth: number;
  onDimensionColumnResize?: ((width: number) => void) | null;
  // Height of the whole leaderboard table, so the resize handle can span all
  // rows instead of just the header cell.
  tableHeight?: number;
}

export default function LeaderboardHeader({
  dimensionName,
  isFetching,
  isValidPercentOfTotal,
  isTimeComparisonActive,
  isBeingCompared,
  sortedAscending,
  displayName,
  dimensionDescription,
  hovered,
  sortType,
  allowDimensionComparison,
  allowExpandTable,
  leaderboardMeasureNames,
  leaderboardSortByMeasureName,
  measuresWithContext,
  toggleSort,
  setPrimaryDimension,
  toggleComparisonDimension,
  measureLabel,
  dimensionColumnWidth,
  onDimensionColumnResize = null,
  tableHeight = 0,
}: LeaderboardHeaderProps) {
  return (
    <thead>
      <tr>
        <th
          aria-label={m.dashboard_comparison_column_aria()}
          className="grid place-content-center"
        >
          {isFetching ? (
            <DelayedSpinner isLoading={isFetching} size="16px" />
          ) : allowDimensionComparison && (hovered || isBeingCompared) ? (
            <DimensionCompareMenu
              dimensionName={dimensionName}
              isBeingCompared={isBeingCompared}
              toggleComparisonDimension={toggleComparisonDimension}
            />
          ) : (
            <SpacerIcon size="14px" />
          )}
        </th>

        <th
          data-dimension-header
          className={`${onDimensionColumnResize ? "resizable" : ""}`}
        >
          <Tooltip
            location="top"
            content={
              <div style={{ maxWidth: "280px" }}>
                <div
                  className="pointer-events-none items-baseline"
                  aria-label="tooltip-name"
                >
                  {displayName}
                </div>
                {dimensionDescription ? (
                  <div
                    className="grid gap-x-2 pointer-events-none pt-1 pb-1 items-baseline"
                    style={{
                      gridTemplateColumns: "auto max-content",
                      minWidth: "200px",
                    }}
                  >
                    <div
                      className="text-fg-inverse/70 justify-self-start"
                      style={{ maxWidth: "280px" }}
                      aria-label="tooltip-name-description"
                    >
                      {dimensionDescription}
                    </div>
                  </div>
                ) : null}
              </div>
            }
          >
            <button
              disabled={!allowExpandTable}
              className={`text-fg-muted text-left ${allowExpandTable ? "hover:text-theme-700" : ""}`}
              aria-label={m.dashboard_open_dimension_details_aria()}
              onClick={() => setPrimaryDimension(dimensionName)}
            >
              <span className="line-clamp-2">{displayName}</span>
            </button>
          </Tooltip>

          {onDimensionColumnResize ? (
            <div className="resizer-container" style={{ height: `${tableHeight}px` }}>
              <Resizer
                side="right"
                direction="EW"
                min={MIN_DIMENSION_COLUMN_WIDTH}
                max={MAX_DIMENSION_COLUMN_WIDTH}
                basis={DEFAULT_DIMENSION_COLUMN_WIDTH}
                dimension={dimensionColumnWidth}
                onUpdate={onDimensionColumnResize}
              >
                <div className="resize-bar" />
              </Resizer>
            </div>
          ) : null}
        </th>

        {leaderboardMeasureNames.map((measureName) => (
          <HeaderCellGroup
            key={measureName}
            measureName={measureName}
            {...{
              isValidPercentOfTotal,
              isTimeComparisonActive,
              sortedAscending,
              sortType,
              leaderboardMeasureNames,
              leaderboardSortByMeasureName,
              measuresWithContext,
              toggleSort,
              measureLabel,
            }}
          />
        ))}
      </tr>
    </thead>
  );
}

/**
 * Renders the label cell + sort arrows for one measure, plus (when the measure
 * has context columns) the percent-of-total, delta-absolute and delta-percent
 * sort headers. This mirrors the `{#each leaderboardMeasureNames ...}` block in
 * the Svelte `<thead>`.
 */
function HeaderCellGroup({
  measureName,
  isValidPercentOfTotal,
  isTimeComparisonActive,
  sortedAscending,
  sortType,
  leaderboardMeasureNames,
  leaderboardSortByMeasureName,
  measuresWithContext,
  toggleSort,
  measureLabel,
}: {
  measureName: string;
  isValidPercentOfTotal: (measureName: string) => boolean;
  isTimeComparisonActive: boolean;
  sortedAscending: boolean;
  sortType: SortType;
  leaderboardMeasureNames: string[];
  leaderboardSortByMeasureName: string | null;
  measuresWithContext: Set<string>;
  toggleSort: (sortType: SortType, measureName?: string) => void;
  measureLabel: (measureName: string) => string;
}) {
  const showSortArrow =
    measureName === leaderboardSortByMeasureName && sortType === SortType.VALUE;

  const isSortingThis =
    measureName === leaderboardSortByMeasureName;

  return (
    <>
      <th data-measure-header key={`value-${measureName}`}>
        <button
          aria-label={m.dashboard_sort_by_value_aria()}
          onClick={() => {
            toggleSort(SortType.VALUE, measureName);
          }}
          className="font-normal text-right"
        >
          <span
            className="measure-label line-clamp-2 text-fg-muted"
            title={measureLabel(measureName)}
          >
            {leaderboardMeasureNames.length > 1
              ? measureLabel(measureName)
              : "#"}
          </span>
          {showSortArrow ? (
            <div className="text-fg-muted">
              {sortedAscending ? (
                <ArrowDownIcon flip />
              ) : (
                <ArrowDownIcon />
              )}
            </div>
          ) : null}
        </button>
      </th>

      {isValidPercentOfTotal(measureName) && measuresWithContext.has(measureName) ? (
        <th data-percent-of-total-header key={`pct-${measureName}`}>
          <button
            aria-label={m.dashboard_sort_by_percent_total_aria()}
            onClick={() => toggleSort(SortType.PERCENT, measureName)}
          >
            <PercentOfTotalIcon />
            {sortType === SortType.PERCENT && isSortingThis ? (
              <div className="text-fg-muted">
                {sortedAscending ? <ArrowDownIcon flip /> : <ArrowDownIcon />}
              </div>
            ) : null}
          </button>
        </th>
      ) : null}

      {isTimeComparisonActive && measuresWithContext.has(measureName) ? (
        <th data-absolute-change-header key={`deltaAbs-${measureName}`}>
          <button
            aria-label={m.dashboard_sort_by_absolute_change_aria()}
            onClick={() => toggleSort(SortType.DELTA_ABSOLUTE, measureName)}
          >
            <DeltaChangeIcon />
            {sortType === SortType.DELTA_ABSOLUTE &&
            isSortingThis ? (
              <div className="text-fg-muted">
                {sortedAscending ? (
                  <ArrowDownIcon flip />
                ) : (
                  <ArrowDownIcon />
                )}
              </div>
            ) : null}
          </button>
        </th>
      ) : null}

      {isTimeComparisonActive && measuresWithContext.has(measureName) ? (
        <th data-percent-change-header key={`deltaRel-${measureName}`}>
          <button
            aria-label={m.dashboard_sort_by_percent_change_aria()}
            onClick={() => toggleSort(SortType.DELTA_PERCENT, measureName)}
          >
            <DeltaChangePercentageIcon />
            {sortType === SortType.DELTA_PERCENT &&
            isSortingThis ? (
              <div className="text-fg-muted">
                {sortedAscending ? (
                  <ArrowDownIcon flip />
                ) : (
                  <ArrowDownIcon />
                )}
              </div>
            ) : null}
          </button>
        </th>
      ) : null}
    </>
  );
}

/**
 * React translation of
 * `features/dashboards/leaderboard/DimensionCompareMenu.svelte` — the
 * icon-button that toggles the comparison breakdown for the dimension.
 */
function DimensionCompareMenu({
  dimensionName,
  isBeingCompared,
  toggleComparisonDimension,
}: {
  dimensionName: string;
  isBeingCompared: boolean;
  toggleComparisonDimension: (dimensionName: string | undefined) => void;
}) {
  return (
    <button
      type="button"
      aria-label={m.leaderboard_toggle_breakdown({ name: dimensionName ?? "" })}
      onClick={(e) => {
        e.stopPropagation();
        if (dimensionName) toggleComparisonDimension(dimensionName);
      }}
      className="flex items-center"
    >
      <Tooltip
        location="left"
        distance={8}
        content={
          isBeingCompared
            ? m.leaderboard_remove_comparison()
            : m.leaderboard_compare()
        }
      >
        <CompareIcon isColored={isBeingCompared} />
      </Tooltip>
    </button>
  );
}
