// web-common/src/features/dashboards/dimension-table/DimensionValueHeader.svelte
<script lang="ts">
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
  import StickyHeader from "@statsparrot/web-common/components/virtualized-table/core/StickyHeader.svelte";
  import { getContext } from "svelte";
  import Cell from "../../../components/virtualized-table/core/Cell.svelte";
  import type {
    VirtualizedTableColumns,
    VirtualizedTableConfig,
  } from "../../../components/virtualized-table/types";
  import ArrowDown from "@statsparrot/web-common/components/icons/ArrowDown.svelte";
  import { fly } from "svelte/transition";
  import { getStateManagers } from "../state-managers/state-managers";
  import type { VirtualItem } from "@tanstack/svelte-virtual";
  import { makeDimensionHref } from "@statsparrot/web-common/features/dashboards/dashboard-utils";
  import type { DimensionTableRow } from "./dimension-table-types";

  const config: VirtualizedTableConfig = getContext("config");

  export let totalHeight: number;
  export let virtualRowItems: VirtualItem[];
  export let selectedIndex: number[] = [];
  export let column: VirtualizedTableColumns;
  export let rows: DimensionTableRow[];
  export let width = config.indexWidth;
  export let horizontalScrolling: boolean;

  // Cell props
  export let scrolling: boolean;
  export let activeIndex: number;
  export let excludeMode = false;
  export let onSelectItem: (data: {
    index: number;
    meta: boolean;
  }) => void = () => {};
  export let onResizeColumn: (size: number) => void = () => {};
  export let onInspect: (rowIndex: number) => void = () => {};

  const {
    actions: {
      sorting: { sortByDimensionValue },
    },
    selectors: {
      sorting: { sortedByDimensionValue, sortedAscending },
    },
  } = getStateManagers();

  $: atLeastOneSelected = !!selectedIndex?.length;

  const getCellProps = (row: VirtualItem, selectedIndex: number[]) => {
    const value = rows[row.index]?.[column.name];
    return {
      value,
      // NOTE: for this "header" column, we don't use a
      // formatted value, we use the dimension value
      // directly. Thus, we pass `null` as the formatted.
      formattedValue: null,
      type: column?.type,
      suppressTooltip: scrolling,
      barValue: 0,
      rowSelected: selectedIndex.findIndex((tgt) => row?.index === tgt) >= 0,
      href: makeDimensionHref(rows[row.index], column.name, value as string),
    };
  };
</script>

<div
  class="sticky self-start left-6 top-0 z-20"
  style:height="{totalHeight}px"
  style:width="{width}px"
>
  <StickyHeader
    header={{ size: width, start: 0 }}
    enableResize={true}
    position="top-left"
    borderRight={true}
    bgClass="bg-surface-background"
    onClick={sortByDimensionValue}
    onResize={onResizeColumn}
  >
    <div class="flex items-center">
      <span class:font-bold={"px-1 " + $sortedByDimensionValue}
        >{column?.label || column?.name}</span
      >
      {#if $sortedByDimensionValue}
        <div class="text-fg-secondary">
          {#if $sortedAscending}
            <div in:fly|global={{ duration: 200, y: -8 }} style:opacity={1}>
              <ArrowDown size="12px" />
            </div>
          {:else}
            <div in:fly|global={{ duration: 200, y: 8 }} style:opacity={1}>
              <ArrowDown flip size="12px" />
            </div>
          {/if}
        </div>
      {/if}
    </div>
  </StickyHeader>
  {#each virtualRowItems as row (`row-${row.key}`)}
    {@const rowActive = activeIndex === row?.index}
    <StickyHeader
      enableResize={false}
      position="left"
      header={{ size: width, start: row.start }}
      borderRight={horizontalScrolling}
      bgClass="bg-surface-background"
    >
      <Cell
        label={m.dashboard_filter_dimension_value()}
        positionStatic
        {row}
        column={{ start: 0, size: width }}
        {atLeastOneSelected}
        {excludeMode}
        {rowActive}
        {...getCellProps(row, selectedIndex)}
        colSelected={$sortedByDimensionValue}
        {onInspect}
        {onSelectItem}
      />
    </StickyHeader>
  {/each}
</div>

// web-common/src/features/dashboards/dimension-table/react/DimensionValueHeader.tsx
import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
import { makeDimensionHref } from "@statsparrot/web-common/features/dashboards/dashboard-utils";
import type { VirtualizedTableColumns } from "@statsparrot/web-common/components/virtualized-table/types";
import type { DimensionTableRow } from "../dimension-table-types";
import type { VirtualItem } from "./useVirtualizer";
import { StickyHeader } from "./StickyHeader";
import { Cell } from "./Cell";
import { ArrowDown } from "./icons";
import { useDimensionTableConfig } from "./context";

/**
 * React translation of `features/dashboards/dimension-table/DimensionValueHeader.svelte`.
 *
 * Renders the frozen dimension-value column: a resizable/sortable header band
 * plus one sticky cell per virtual row. The `sortByDimensionValue` action and
 * the `sortedByDimensionValue` / `sortedAscending` selectors are Svelte-context
 * values in the source and are threaded in as props here.
 */
export interface DimensionValueHeaderProps {
  totalHeight: number;
  virtualRowItems: VirtualItem[];
  selectedIndex?: number[];
  column: VirtualizedTableColumns;
  rows: DimensionTableRow[];
  width?: number;
  horizontalScrolling?: boolean;
  scrolling?: boolean;
  activeIndex?: number;
  excludeMode?: boolean;
  sortedByDimensionValue?: boolean;
  sortedAscending?: boolean;
  onSortByDimensionValue?: () => void;
  onSelectItem?: (data: { index: number; meta: boolean }) => void;
  onResizeColumn?: (size: number) => void;
  onInspect?: (rowIndex: number) => void;
}

export function DimensionValueHeader({
  totalHeight,
  virtualRowItems,
  selectedIndex = [],
  column,
  rows,
  width,
  horizontalScrolling = false,
  scrolling = false,
  activeIndex,
  excludeMode = false,
  sortedByDimensionValue = false,
  sortedAscending = false,
  onSortByDimensionValue = () => {},
  onSelectItem = () => {},
  onResizeColumn = () => {},
  onInspect = () => {},
}: DimensionValueHeaderProps) {
  const config = useDimensionTableConfig();
  const cellWidth = width ?? config.indexWidth;
  const atLeastOneSelected = !!selectedIndex?.length;

  const getCellProps = (row: VirtualItem) => {
    const value = rows[row.index]?.[column.name];
    return {
      value,
      // NOTE: for this "header" column, we don't use a formatted value, we use
      // the dimension value directly. Thus `null` is passed as the formatted.
      formattedValue: null,
      type: column?.type,
      suppressTooltip: scrolling,
      barValue: 0,
      rowSelected:
        selectedIndex.findIndex((tgt) => row?.index === tgt) >= 0,
      href: makeDimensionHref(
        rows[row.index],
        column.name,
        value as string,
      ),
    };
  };

  return (
    <div
      className="sticky self-start left-6 top-0 z-20"
      style={{ height: `${totalHeight}px`, width: `${cellWidth}px` }}
    >
      <StickyHeader
        header={{ size: cellWidth, start: 0 }}
        enableResize
        position="top-left"
        borderRight
        bgClass="bg-surface-background"
        onClick={onSortByDimensionValue}
        onResize={onResizeColumn}
      >
        <div className="flex items-center">
          <span className={`px-1 ${sortedByDimensionValue ? "font-bold" : ""}`}>
            {column?.label || column?.name}
          </span>
          {sortedByDimensionValue ? (
            <div className="text-fg-secondary">
              {sortedAscending ? (
                <ArrowDown size="12px" />
              ) : (
                <ArrowDown size="12px" flip />
              )}
            </div>
          ) : null}
        </div>
      </StickyHeader>
      {virtualRowItems.map((row) => (
        <StickyHeader
          key={`row-${row.key}`}
          enableResize={false}
          position="left"
          header={{ size: cellWidth, start: row.start }}
          borderRight={horizontalScrolling}
          bgClass="bg-surface-background"
        >
          <Cell
            label={m.dashboard_filter_dimension_value()}
            positionStatic
            row={row}
            column={{ start: 0, size: cellWidth }}
            atLeastOneSelected={atLeastOneSelected}
            excludeMode={excludeMode}
            rowActive={activeIndex === row.index}
            {...getCellProps(row)}
            colSelected={sortedByDimensionValue}
            onInspect={onInspect}
            onSelectItem={onSelectItem}
          />
        </StickyHeader>
      ))}
    </div>
  );
}
