// web-common/src/layout/workspace/WorkspaceEditorContainer.svelte
<script lang="ts">
  import { slide } from "svelte/transition";
  import CancelCircle from "@statsparrot/web-common/components/icons/CancelCircle.svelte";
  import { LIST_SLIDE_DURATION } from "@statsparrot/web-common/layout/config";
  import { createRootCauseErrorQuery } from "@statsparrot/web-common/features/entity-management/error-utils";
  import type {
    V1ParseError,
    V1Resource,
  } from "@statsparrot/web-common/runtime-client";
  import { useRuntimeClient } from "@statsparrot/web-common/runtime-client/v2";
  import ExplainAndFixErrorButton from "@statsparrot/web-common/features/chat/ExplainAndFixErrorButton.svelte";

  // Direct error string (existing API, still supported)
  export let error: string | undefined = undefined;
  export let showError = true;

  // Resource-based error derivation (replaces WorkspaceError wrapper)
  export let resource: V1Resource | undefined = undefined;
  export let parseError: V1ParseError | undefined = undefined;
  export let remoteContent: string | null | undefined = undefined;
  export let filePath: string | undefined = undefined;

  const runtimeClient = useRuntimeClient();

  $: reconcileError = resource?.meta?.reconcileError;
  $: rootCauseQuery = createRootCauseErrorQuery(
    runtimeClient,
    resource,
    reconcileError,
  );
  $: rootCauseReconcileError = reconcileError
    ? ($rootCauseQuery?.data ?? reconcileError)
    : undefined;

  $: derivedError = parseError?.message ?? rootCauseReconcileError;
  $: effectiveError = error ?? derivedError;
  $: effectiveShowError =
    showError && (remoteContent === undefined || !!remoteContent);
</script>

<div
  class="flex flex-col size-full gap-y-1 bg-surface-subtle rounded-[2px] border overflow-hidden"
>
  <div
    class="size-full relative overflow-hidden flex flex-col items-center justify-center"
    class:!border-red-500={effectiveError}
  >
    <slot />
  </div>

  {#if effectiveError && effectiveShowError}
    <div
      role="status"
      transition:slide={{ duration: LIST_SLIDE_DURATION }}
      class="border border-destructive bg-destructive/15 dark:bg-destructive/30 text-fg-primary border-l-4 px-2 py-5 max-h-72 overflow-auto"
    >
      <div class="flex gap-x-2">
        <CancelCircle className="text-destructive flex-shrink-0 mt-0.5" />
        <div class="flex flex-col gap-2 min-w-0">
          <span class="break-words">{effectiveError}</span>
          {#if filePath}
            <ExplainAndFixErrorButton {filePath} />
          {/if}
        </div>
      </div>
    </div>
  {/if}
</div>

// web-common/src/features/workspaces/react/WorkspaceEditorContainer.tsx
// React translation of `layout/workspace/WorkspaceEditorContainer.svelte`. The
// runtime error derivation (`createRootCauseErrorQuery`, `V1Resource`) and the
// ExplainAndFix error button are deferred to the runtime-bound phase; the
// component reproduces the bordered editor surface plus the error banner.
import type { ReactNode } from "react";
import { AlertIcon } from "@statsparrot/web-common/features/file-explorer/react/icons";

export default function WorkspaceEditorContainer({
  error,
  showError = true,
  remoteContent,
  filePath,
  children,
}: {
  error?: string | undefined;
  showError?: boolean;
  remoteContent?: string | null | undefined;
  filePath?: string | undefined;
  children?: ReactNode;
}) {
  const effectiveShowError =
    showError && (remoteContent === undefined || !!remoteContent);

  return (
    <div className="flex flex-col size-full gap-y-1 bg-surface-subtle rounded-[2px] border overflow-hidden">
      <div className="size-full relative overflow-hidden flex flex-col items-center justify-center">
        {children}
      </div>

      {error && effectiveShowError ? (
        <div
          role="status"
          className="border border-destructive bg-destructive/15 text-fg-primary border-l-4 px-2 py-5 max-h-72 overflow-auto"
        >
          <div className="flex gap-x-2">
            <AlertIcon
              className="text-destructive flex-shrink-0 mt-0.5"
              size="16px"
            />
            <div className="flex flex-col gap-2 min-w-0">
              <span className="break-words">{error}</span>
              {filePath ? (
                <span className="text-xs text-fg-muted">
                  Fix the error and re-run reconciliation.
                </span>
              ) : null}
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}
