// web-common/src/components/date-picker/DateInput.svelte
<script lang="ts">
  import { DateTime } from "luxon";
  import * as Tooltip from "@statsparrot/web-common/components/tooltip-v2";
  import AlertTriangle from "../icons/AlertTriangle.svelte";

  const formatsWithoutYear = [
    "M/d", // 7/4 or 07/04
    "MMMM d", // July 4 or July 04
    "MMM d", // Jul 4 or Jul 04
    "M-d", // 7-4 or 07-04
    "d MMMM", // 4 July or 04 July
    "d MMM", // 4 Jul or 04 Jul
    "d.M", // 4.7 or 04.07
  ];

  const formatsWithYear = [
    "M/d/yy", // 7/4/21 or 07/04/21
    "D", // 7/4/2021 or 07/04/2021
    "DDD", // July 4, 2021 or July 04, 2021
    "MMM d, yyyy", // Jul 4, 2021
    "MMM d yyyy", // Jul 4 2021
    "MMMM d yyyy", // July 4 2021 or July 04 2021
    "yyyy-M-d", // July 4, 2021 or July 04, 2021
    "M-d-yyyy", // July 4, 2021 or July 04, 2021
    "M-d-yy", // 7-4-21 or 07-04-21
    "d MMMM yyyy", // 4 July 2021 or 04 July 2021
    "d MMM yyyy", // 05 Jul 2021 or 5 Jul 2021
    "d MMMM, yyyy", // 4 July 2021 or 04 July 2021
    "d MMM, yyyy", // 05 Jul 2021 or 5 Jul 2021
    "d.M.yyyy", // 4.7.2021 or 04.07.2021
  ];

  const formats = [...formatsWithoutYear, ...formatsWithYear];

  const ErrorType = {
    INVALID: "invalid",
    OUT_OF_RANGE: "out-of-range",
  } as const;
  type ErrorType = (typeof ErrorType)[keyof typeof ErrorType];

  export let date: DateTime;
  export let zone: string;
  export let boundary: "start" | "end";
  export let currentYear: number;
  export let minDate: DateTime | undefined = undefined;
  export let maxDate: DateTime | undefined = undefined;
  export let onValidDateInput: (
    date: DateTime,
    boundary: "start" | "end",
  ) => void;
  export let onFocus: () => void;

  let errorType: ErrorType | null = null;
  let inputIsFocused = false;
  let dateString = date.toLocaleString({
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  $: id = boundary + "-date";
  $: label = boundary + " date";

  $: if (!inputIsFocused) {
    dateString = date.toLocaleString({
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  }

  $: if (
    (minDate && date < minDate.startOf("day")) ||
    (maxDate && date >= maxDate)
  ) {
    errorType = ErrorType.OUT_OF_RANGE;
  } else {
    errorType = null;
  }

  function convertToDateTime(dateString: string): DateTime<true> | undefined {
    let potentialDate: DateTime | undefined = undefined;
    let format: string | null = null;

    for (const potentialFormat of formats) {
      potentialDate = DateTime.fromFormat(dateString, potentialFormat, {
        zone,
      });

      if (potentialDate.isValid) {
        format = potentialFormat;

        break;
      }
    }

    if (
      potentialDate &&
      potentialDate.year !== currentYear &&
      format &&
      formatsWithoutYear.includes(format)
    ) {
      potentialDate = potentialDate.set({ year: currentYear });
    }

    if (potentialDate?.isValid) {
      return potentialDate;
    } else {
      return undefined;
    }
  }

  function processInput(value: string) {
    let potentialDate = convertToDateTime(value);

    if (potentialDate) {
      if (boundary === "end") {
        potentialDate = potentialDate?.plus({ day: 1 }).startOf("day");
      }

      onValidDateInput(potentialDate, boundary);
    } else {
      errorType = ErrorType.INVALID;
      return;
    }
  }

  function resetDate() {
    if (boundary === "start") {
      date = minDate ?? DateTime.now().startOf("day");
      onValidDateInput(date, boundary);
    } else {
      date = maxDate ?? DateTime.now().plus({ day: 1 }).startOf("day");
      onValidDateInput(date, boundary);
    }
  }
</script>

<div class="flex flex-col gap-y-1 w-full">
  <label class="capitalize flex items-center" for={id}>
    {label}
  </label>

  <div class="input-wrapper" class:error={errorType === ErrorType.INVALID}>
    <input
      tabindex="0"
      {id}
      class="size-full bg-transparent"
      aria-label={label}
      type="text"
      bind:value={dateString}
      onfocus={() => {
        onFocus();
        inputIsFocused = true;
      }}
      onblur={() => {
        processInput(dateString);
        inputIsFocused = false;
      }}
    />
    {#if errorType === ErrorType.OUT_OF_RANGE || (errorType && !inputIsFocused)}
      <Tooltip.Root>
        <Tooltip.Trigger>
          {#snippet child({ props })}
            <button {...props} onclick={resetDate}>
              <AlertTriangle
                className="size-4 text-{errorType === ErrorType.INVALID
                  ? 'red'
                  : 'yellow'}-500"
              />
            </button>
          {/snippet}
        </Tooltip.Trigger>
        <Tooltip.Content side="top" sideOffset={10} class="shadow-md">
          {#if errorType === ErrorType.OUT_OF_RANGE}
            Date is out of range. Click to reset.
          {:else}
            Date is invalid. Click to reset.
          {/if}
        </Tooltip.Content>
      </Tooltip.Root>
    {/if}
  </div>
</div>

<style lang="postcss">
  .input-wrapper {
    @apply h-8 px-2 w-full rounded-md border flex bg-input;
    @apply items-center justify-between;
  }

  .input-wrapper:focus-within {
    outline: none;
    @apply border-theme-600;
  }

  input:focus {
    outline: none;
  }

  .input-wrapper.error:not(:focus-within) {
    @apply border-destructive text-destructive;
  }

  label {
    @apply font-semibold flex gap-x-1;
  }
</style>

// web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/react/DateInput.tsx
import { useEffect, useState } from "react";
import { DateTime } from "luxon";

const formatsWithoutYear = [
  "M/d",
  "MMMM d",
  "MMM d",
  "M-d",
  "d MMMM",
  "d MMM",
  "d.M",
];

const formatsWithYear = [
  "M/d/yy",
  "D",
  "DDD",
  "MMM d, yyyy",
  "MMM d yyyy",
  "MMMM d yyyy",
  "yyyy-M-d",
  "M-d-yyyy",
  "M-d-yy",
  "d MMMM yyyy",
  "d MMM yyyy",
  "d MMMM, yyyy",
  "d MMM, yyyy",
  "d.M.yyyy",
];

const formats = [...formatsWithoutYear, ...formatsWithYear];

const ErrorType = {
  INVALID: "invalid",
  OUT_OF_RANGE: "out-of-range",
} as const;
type ErrorType = (typeof ErrorType)[keyof typeof ErrorType];

/**
 * React translation of `components/date-picker/DateInput.svelte`. A single bound date
 * text input with the same flex format parsing and invalid/out-of-range feedback.
 */
export interface DateInputProps {
  date: DateTime;
  zone: string;
  boundary: "start" | "end";
  currentYear: number;
  minDate?: DateTime | undefined;
  maxDate?: DateTime | undefined;
  onValidDateInput: (date: DateTime, boundary: "start" | "end") => void;
  onFocus: () => void;
}

export function DateInput({
  date,
  zone,
  boundary,
  currentYear,
  minDate,
  maxDate,
  onValidDateInput,
  onFocus,
}: DateInputProps) {
  const [errorType, setErrorType] = useState<ErrorType | null>(null);
  const [inputIsFocused, setInputIsFocused] = useState(false);
  const [dateString, setDateString] = useState(
    date.toLocaleString({ month: "short", day: "numeric", year: "numeric" }),
  );

  const id = `${boundary}-date`;
  const label = `${boundary} date`;

  useEffect(() => {
    if (!inputIsFocused) {
      setDateString(
        date.toLocaleString({ month: "short", day: "numeric", year: "numeric" }),
      );
    }
  }, [date, inputIsFocused]);

  useEffect(() => {
    if (
      (minDate && date < minDate.startOf("day")) ||
      (maxDate && date >= maxDate)
    ) {
      setErrorType(ErrorType.OUT_OF_RANGE);
    } else {
      setErrorType(null);
    }
  }, [minDate, maxDate, date]);

  function convertToDateTime(value: string): DateTime<true> | undefined {
    let potentialDate: DateTime | undefined = undefined;
    let format: string | null = null;

    for (const potentialFormat of formats) {
      potentialDate = DateTime.fromFormat(value, potentialFormat, { zone });
      if (potentialDate.isValid) {
        format = potentialFormat;
        break;
      }
    }

    if (
      potentialDate &&
      potentialDate.year !== currentYear &&
      format &&
      formatsWithoutYear.includes(format)
    ) {
      potentialDate = potentialDate.set({ year: currentYear });
    }

    return potentialDate?.isValid ? potentialDate : undefined;
  }

  function processInput(value: string) {
    let potentialDate = convertToDateTime(value);

    if (potentialDate) {
      if (boundary === "end") {
        potentialDate = potentialDate?.plus({ day: 1 }).startOf("day");
      }
      onValidDateInput(potentialDate, boundary);
    } else {
      setErrorType(ErrorType.INVALID);
      return;
    }
  }

  function resetDate() {
    if (boundary === "start") {
      const reset = minDate ?? DateTime.now().startOf("day");
      onValidDateInput(reset, boundary);
    } else {
      const reset = maxDate ?? DateTime.now().plus({ day: 1 }).startOf("day");
      onValidDateInput(reset, boundary);
    }
  }

  return (
    <div className="flex flex-col gap-y-1 w-full">
      <label className="capitalize flex items-center font-semibold" htmlFor={id}>
        {label}
      </label>

      <div
        className={`h-8 px-2 w-full rounded-md border flex bg-input items-center justify-between ${
          inputIsFocused ? "border-theme-600" : ""
        } ${
          errorType === ErrorType.INVALID && !inputIsFocused
            ? "border-destructive text-destructive"
            : ""
        }`}
      >
        <input
          tabIndex={0}
          id={id}
          className="size-full bg-transparent outline-none"
          aria-label={label}
          type="text"
          value={dateString}
          onChange={(e) => setDateString(e.target.value)}
          onFocus={() => {
            onFocus();
            setInputIsFocused(true);
          }}
          onBlur={() => {
            processInput(dateString);
            setInputIsFocused(false);
          }}
        />
        {errorType === ErrorType.OUT_OF_RANGE ||
        (errorType && !inputIsFocused) ? (
          <button type="button" onClick={resetDate} aria-label="Reset date">
            <svg
              className={`size-4 ${
                errorType === ErrorType.INVALID ? "text-red-500" : "text-yellow-500"
              }`}
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />
              <path d="M12 9v4" />
              <path d="M12 17h.01" />
            </svg>
          </button>
        ) : null}
      </div>
    </div>
  );
}
