// web-common/src/features/dashboards/time-controls/super-pill/components/RangeDisplay.svelte
<script lang="ts">
  import { prettyFormatTimeRange } from "@statsparrot/web-common/lib/time/ranges/formatter.ts";
  import { V1TimeGrain } from "@statsparrot/web-common/runtime-client";
  import { Interval } from "luxon";

  export let interval: Interval | undefined;
  export let timeGrain: V1TimeGrain = V1TimeGrain.TIME_GRAIN_UNSPECIFIED;
  export let abbreviation: string | undefined = undefined;

  $: formattedInterval = prettyFormatTimeRange(interval, timeGrain);
</script>

<div class="flex gap-x-1 whitespace-nowrap truncate">
  <span class="line-clamp-1 text-left">
    {#if interval?.isValid}
      {formattedInterval}
      {#if abbreviation}
        {abbreviation}
      {/if}
    {:else}
      Invalid Interval
    {/if}
  </span>
</div>

// web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/react/RangeDisplay.tsx
import { prettyFormatTimeRange } from "@statsparrot/web-common/lib/time/ranges/formatter";
import { V1TimeGrain } from "@statsparrot/web-common/runtime-client";
import type { Interval } from "luxon";
import { useMemo } from "react";

/**
 * React translation of `super-pill/components/RangeDisplay.svelte`. Formats a Luxon
 * interval for human-readable display. Reuses `prettyFormatTimeRange` verbatim.
 */
export interface RangeDisplayProps {
  interval: Interval | undefined;
  timeGrain?: V1TimeGrain;
  abbreviation?: string | undefined;
}

export function RangeDisplay({
  interval,
  timeGrain = V1TimeGrain.TIME_GRAIN_UNSPECIFIED,
  abbreviation,
}: RangeDisplayProps) {
  const formattedInterval = useMemo(
    () => prettyFormatTimeRange(interval, timeGrain),
    [interval, timeGrain],
  );

  return (
    <div className="flex gap-x-1 whitespace-nowrap truncate">
      <span className="line-clamp-1 text-left">
        {interval?.isValid ? (
          <>
            {formattedInterval}
            {abbreviation ? abbreviation : null}
          </>
        ) : (
          "Invalid Interval"
        )}
      </span>
    </div>
  );
}
