// web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/TimeRangeOptionGroup.svelte
<script lang="ts">
  import type { ParrotTime } from "../../../url-state/time-ranges/ParrotTime";
  import TimeRangeMenuItem from "../components/TimeRangeMenuItem.svelte";

  export let filter = "";
  export let options: ParrotTime[];
  export let timeString: string | undefined = undefined;
  export let hideDivider = false;

  export let onClick: (range: string) => void;

  $: filtered = options.filter((option) => {
    return (
      option.interval.toString().toLowerCase().includes(filter.toLowerCase()) ||
      option.getLabel().toLowerCase().includes(filter.toLowerCase())
    );
  });
</script>

{#if filtered.length}
  <div class="w-full h-fit px-1">
    {#if hideDivider}
      <div class="h-px w-full bg-border my-1"></div>
    {/if}
    {#each filtered as option, i (i)}
      <TimeRangeMenuItem statsparrotTime={option} {timeString} {onClick} />
    {/each}

    {#if !hideDivider}
      <div class="h-px w-full bg-border my-1"></div>
    {/if}
  </div>
{/if}

// web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/react/TimeRangeOptionGroup.tsx
import { useMemo } from "react";
import type { ParrotTime } from "@statsparrot/web-common/features/dashboards/url-state/time-ranges/ParrotTime";
import { TimeRangeMenuItem } from "./TimeRangeMenuItem";

/**
 * React translation of `super-pill/new-time-dropdown/TimeRangeOptionGroup.svelte`.
 * Filters the given range options by the current search and renders them as menu items
 * separated by a divider line.
 */
export interface TimeRangeOptionGroupProps {
  filter: string;
  options: ParrotTime[];
  timeString?: string | undefined;
  hideDivider?: boolean;
  onClick: (range: string) => void;
}

export function TimeRangeOptionGroup({
  filter,
  options,
  timeString,
  hideDivider = false,
  onClick,
}: TimeRangeOptionGroupProps) {
  const filtered = useMemo(
    () =>
      options.filter((option) => {
        return (
          option.interval
            .toString()
            .toLowerCase()
            .includes(filter.toLowerCase()) ||
          option.getLabel().toLowerCase().includes(filter.toLowerCase())
        );
      }),
    [options, filter],
  );

  if (!filtered.length) return null;

  return (
    <div className="w-full h-fit px-1">
      {hideDivider ? (
        <div className="h-px w-full bg-border my-1"></div>
      ) : null}
      {filtered.map((option, i) => (
        <TimeRangeMenuItem key={i} statsparrotTime={option} timeString={timeString} onClick={onClick} />
      ))}
      {!hideDivider ? <div className="h-px w-full bg-border my-1"></div> : null}
    </div>
  );
}
