// web-common/src/features/dashboards/dimension-table/react/ColumnHeader.tsx
import type { ComponentType } from "react";
import { copyToClipboard } from "@statsparrot/web-common/lib/actions/copy-to-clipboard";
import { SortDirection } from "@statsparrot/web-common/features/dashboards/proto-state/derived-types";
import type { HeaderPosition } from "@statsparrot/web-common/components/virtualized-table/types";
import { Tooltip } from "@statsparrot/web-common/features/dashboards/leaderboard/react/primitives";
import { ArrowDown, Pin } from "./icons";
import { StickyHeader } from "./StickyHeader";
import { useDimensionTableConfig } from "./context";

/**
 * React translation of `components/virtualized-table/core/ColumnHeader.svelte`.
 *
 * Renders a single measure column header: the (sortable) label with the
 * direction arrow, a description tooltip in the dimension table, and the
 * pin-to-right action. The `showDataIcon`/`DataTypeIcon` affordance is not
 * exercised by the dimension table (the section renders `showDataIcon={false}`)
 * and is therefore not transferred.
 */
export interface ColumnHeaderProps {
  name: string | ComponentType;
  type?: string;
  description?: string;
  header: { size: number; start: number };
  position?: HeaderPosition;
  noPin?: boolean;
  showDataIcon?: boolean;
  pinned?: boolean;
  enableResize?: boolean;
  enableSorting?: boolean;
  isSelected?: boolean;
  sorted?: SortDirection | undefined;
  onResizeColumn?: (size: number, name: string) => void;
  onResetColumnWidth?: (name: string) => void;
  onClickColumn?: (name: string) => void;
  onPin?: () => void;
}

export function ColumnHeader({
  name,
  type = "",
  description = "",
  header,
  position = "top",
  noPin = false,
  showDataIcon = false,
  pinned = false,
  enableResize = true,
  enableSorting = true,
  isSelected = false,
  sorted,
  onResizeColumn = () => {},
  onResetColumnWidth = () => {},
  onClickColumn = () => {},
  onPin = () => {},
}: ColumnHeaderProps) {
  const config = useDimensionTableConfig();
  const isDimensionTable = config.table === "DimensionTable";
  const isDimensionColumn =
    isDimensionTable && (type === "VARCHAR" || type === "CODE_STRING");

  const textAlignment = isDimensionColumn ? "text-left pl-1" : "text-right pr-1";
  const columnFontWeight = isSelected ? "" : config.columnHeaderFontWeightClass;

  const labelText = typeof name === "string" ? name : "";

  const tooltipContent = (
    <div className="flex flex-col gap-y-1.5 p-2 max-w-[280px]">
      {!isDimensionTable ? (
        <div className="flex flex-col">
          <span className="font-semibold">{labelText}</span>
          {showDataIcon ? (
            <span className="text-fg-muted truncate">{type}</span>
          ) : null}
        </div>
      ) : null}
      {isDimensionTable && description?.length ? (
        <div className="text-fg-muted truncate">{description}</div>
      ) : null}
      {isDimensionTable ? (
        <div className="text-fg-disabled">
          {enableSorting ? <div>Sort column</div> : null}
          <div>Copy column name to clipboard</div>
        </div>
      ) : null}
    </div>
  );

  return (
    <StickyHeader
      enableResize={enableResize}
      bgClass={config.headerBgColorClass}
      onResetColumnWidth={() => onResetColumnWidth(labelText)}
      onResize={(size) => onResizeColumn(size, labelText)}
      position={position}
      header={header}
      onFocus={() => {
        // `showMore` toggles the pin button; the dimension table always passes
        // `noPin`, so this is only meaningful for non-dimension tables.
      }}
      onBlur={() => {}}
      onClick={() => onClickColumn(labelText)}
      onShiftClick={() =>
        copyToClipboard(labelText, `Copied column name "${labelText}" to clipboard`)
      }
    >
      <div
        className={`flex justify-stretch select-none ${isDimensionTable ? "" : "items-center gap-x-2"}`}
      >
        <Tooltip location="top" alignment="middle" distance={16} content={tooltipContent}>
          <div
            className={`grid items-center cursor-pointer w-full ${!isSelected ? "gap-x-2" : ""}`}
            style={{
              gridTemplateColumns: isDimensionTable
                ? ""
                : `max-content auto ${!noPin ? "max-content" : ""}`,
            }}
          >
            <span
              className={`text-ellipsis ${columnFontWeight} ${isDimensionTable ? `${textAlignment} break-words line-clamp-2` : "overflow-hidden whitespace-nowrap"}`}
            >
              {labelText}
            </span>
          </div>
        </Tooltip>

        {sorted ? (
          <div className="mt-0.5 text-fg-secondary">
            {sorted === SortDirection.DESCENDING ? (
              <ArrowDown size="12px" />
            ) : sorted === SortDirection.ASCENDING ? (
              <ArrowDown size="12px" flip />
            ) : null}
          </div>
        ) : null}

        {!noPin ? (
          <Tooltip
            location="top"
            alignment="middle"
            distance={16}
            content={
              pinned
                ? "unpin this column from the right side of the table"
                : "pin this column to the right side of the table"
            }
          >
            <button
              className={`duration-100 justify-self-end ${pinned ? "text-fg-primary" : "text-fg-secondary"}`}
              onClick={onPin}
            >
              <Pin size="16px" />
            </button>
          </Tooltip>
        ) : null}
      </div>
    </StickyHeader>
  );
}

// web-common/src/components/virtualized-table/core/ColumnHeader.svelte
<script lang="ts">
  import { DataTypeIcon } from "@statsparrot/web-common/components/data-types";
  import ArrowDown from "@statsparrot/web-common/components/icons/ArrowDown.svelte";
  import Pin from "@statsparrot/web-common/components/icons/Pin.svelte";
  import Shortcut from "@statsparrot/web-common/components/tooltip/Shortcut.svelte";
  import StackingWord from "@statsparrot/web-common/components/tooltip/StackingWord.svelte";
  import Tooltip from "@statsparrot/web-common/components/tooltip/Tooltip.svelte";
  import TooltipContent from "@statsparrot/web-common/components/tooltip/TooltipContent.svelte";
  import TooltipShortcutContainer from "@statsparrot/web-common/components/tooltip/TooltipShortcutContainer.svelte";
  import TooltipTitle from "@statsparrot/web-common/components/tooltip/TooltipTitle.svelte";
  import { SortDirection } from "@statsparrot/web-common/features/dashboards/proto-state/derived-types";
  import {
    copyToClipboard,
    isClipboardApiSupported,
  } from "@statsparrot/web-common/lib/actions/copy-to-clipboard";
  import { getContext } from "svelte";
  import { fly } from "svelte/transition";
  import TooltipDescription from "../../tooltip/TooltipDescription.svelte";
  import type { HeaderPosition, VirtualizedTableConfig } from "../types";
  import StickyHeader from "./StickyHeader.svelte";

  export let pinned = false;
  export let noPin = false;
  export let showDataIcon = false;
  export let name;
  export let type: string;
  export let description = "";
  export let header;
  export let position: HeaderPosition = "top";
  export let enableResize = true;
  export let enableSorting = true;
  export let isSelected = false;
  export let sorted: SortDirection | undefined = undefined;
  export let onResizeColumn: (size: number, name: string) => void = () => {};
  export let onResetColumnWidth: (name: string) => void = () => {};
  export let onClickColumn: (name: string) => void;
  export let onPin: () => void;

  const config: VirtualizedTableConfig = getContext("config");

  let showMore = false;

  $: isDimensionTable = config.table === "DimensionTable";
  $: isDimensionColumn =
    isDimensionTable && (type === "VARCHAR" || type === "CODE_STRING");

  $: textAlignment = isDimensionColumn ? "text-left pl-1" : "text-right pr-1";

  $: columnFontWeight = isSelected ? "" : config.columnHeaderFontWeightClass;

  const handleResize = (size: number) => {
    onResizeColumn(size, name);
  };
</script>

<StickyHeader
  {enableResize}
  bgClass={config.headerBgColorClass}
  onResetColumnWidth={() => {
    onResetColumnWidth(name);
  }}
  onResize={handleResize}
  {position}
  {header}
  onFocus={() => {
    showMore = true;
  }}
  onBlur={() => {
    showMore = false;
  }}
  onClick={() => onClickColumn(name)}
  onShiftClick={() => {
    copyToClipboard(name, `Copied column name "${name}" to clipboard`);
  }}
>
  <div
    class=" 
           flex
           justify-stretch
           select-none
           over
           {isDimensionTable ? '' : 'items-center gap-x-2'}
           "
  >
    <Tooltip location="top" alignment="middle" distance={16}>
      <div
        class="
        grid
        items-center cursor-pointer w-full"
        class:gap-x-2={!isSelected}
        style:grid-template-columns={isDimensionTable
          ? ""
          : `max-content auto ${!noPin && showMore ? "max-content" : ""}`}
      >
        {#if showDataIcon}
          <DataTypeIcon suppressTooltip color={"text-fg-secondary"} {type} />
        {/if}
        <span
          class="text-ellipsis
          {columnFontWeight}
          {isDimensionTable
            ? `${textAlignment} break-words line-clamp-2`
            : 'overflow-hidden whitespace-nowrap'}
          "
        >
          {#if typeof name !== "string"}
            <div class="flex justify-end">
              <svelte:component this={name} />
            </div>
          {:else}
            {name}
          {/if}
        </span>
      </div>
      <TooltipContent slot="tooltip-content" maxWidth="280px">
        {#if !isDimensionTable}
          <TooltipTitle>
            <svelte:fragment slot="name">
              {name}
            </svelte:fragment>
            <svelte:fragment slot="description">
              {showDataIcon ? type : ""}
            </svelte:fragment>
          </TooltipTitle>
        {/if}
        {#if isDimensionTable && description?.length}
          <TooltipDescription>
            {description}
          </TooltipDescription>
        {/if}
        {#if isDimensionTable || isClipboardApiSupported()}
          <TooltipShortcutContainer>
            {#if enableSorting}
              <div>Sort column</div>
              <Shortcut>Click</Shortcut>
            {/if}
            {#if isClipboardApiSupported()}
              <div>
                <StackingWord key="shift">Copy</StackingWord>
                column name to clipboard
              </div>
              <Shortcut>
                <span style="font-family: var(--system);">⇧</span> + Click
              </Shortcut>
            {/if}
          </TooltipShortcutContainer>
        {/if}
      </TooltipContent>
    </Tooltip>

    {#if sorted}
      <div class="mt-0.5 text-fg-secondary">
        {#if sorted === SortDirection.DESCENDING}
          <div in:fly|global={{ duration: 200, y: -8 }} style:opacity={1}>
            <ArrowDown size="12px" />
          </div>
        {:else if sorted === SortDirection.ASCENDING}
          <div in:fly|global={{ duration: 200, y: 8 }} style:opacity={1}>
            <ArrowDown flip size="12px" />
          </div>
        {/if}
      </div>
    {/if}

    {#if !noPin && showMore}
      <Tooltip location="top" alignment="middle" distance={16}>
        <button
          transition:fly={{ duration: 200, y: 4 }}
          class:text-fg-primary={pinned}
          class:text-fg-secondary={!pinned}
          class="   duration-100 justify-self-end"
          onclick={onPin}
        >
          <Pin size="16px" />
        </button>
        <TooltipContent slot="tooltip-content">
          {pinned
            ? "unpin this column from the right side of the table"
            : "pin this column to the right side of the table"}
        </TooltipContent>
      </Tooltip>
    {/if}
  </div>
</StickyHeader>
