// web-common/src/features/dashboards/state-managers/StateManagersProvider.svelte
<script lang="ts">
  import { setContext } from "svelte";
  import { createStateManagers, DEFAULT_STORE_KEY } from "./state-managers";
  import { useExploreState } from "../stores/dashboard-stores";
  import { queryClient } from "@statsparrot/web-common/lib/svelte-query/globalQueryClient";
  import { useRuntimeClient } from "@statsparrot/web-common/runtime-client/v2";

  export let metricsViewName: string | undefined;
  export let exploreName: string;
  export let visualEditing = false;

  const client = useRuntimeClient();

  const stateManagers = metricsViewName
    ? createStateManagers({
        queryClient,
        metricsViewName,
        exploreName,
        runtimeClient: client,
      })
    : undefined;

  if (stateManagers) setContext(DEFAULT_STORE_KEY, stateManagers);

  // Our state management was not built around the ability to arbitrarily change the explore or metrics view name
  // This needs to change, but this is a workaround for now
  $: if (visualEditing && stateManagers && metricsViewName) {
    stateManagers?.metricsViewName.set(metricsViewName);
  }

  $: exploreStore = useExploreState(exploreName);

  $: ready = Boolean($exploreStore) && Boolean(stateManagers);
</script>

<slot {ready} />

// web-common/src/features/dashboards/state-managers/react/StateManagersProvider.tsx
import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  type ReactNode,
} from "react";
import { createStateManagers } from "../state-managers";
import type { StateManagers } from "../state-managers";
import { queryClient } from "@statsparrot/web-common/lib/svelte-query/globalQueryClient";
import { useRuntimeClient } from "@statsparrot/web-common/runtime-client/react";

const StateManagersContext = createContext<StateManagers | undefined>(
  undefined,
);

export interface StateManagersProviderProps {
  /** The metrics view (explore) resource name. When undefined the provider is inert. */
  metricsViewName?: string;
  /** The explore resource name used as the store entity key. */
  exploreName: string;
  /** Re-sync `metricsViewName` on change (Parrot uses this for visual editing). */
  visualEditing?: boolean;
  children: ReactNode;
}

/**
 * React translation of `StateManagersProvider.svelte`.
 *
 * Parrot's explore state-management lives in Svelte context (`getStateManagers()`).
 * Svelte context is unavailable in a React host, so this provider builds the same
 * `StateManagers` object via the framework-agnostic `createStateManagers()` factory
 * and exposes it through React context. The selectors/actions/stores it returns are
 * reused verbatim; only the context wire-up differs.
 */
export function StateManagersProvider({
  metricsViewName,
  exploreName,
  visualEditing = false,
  children,
}: StateManagersProviderProps) {
  const runtimeClient = useRuntimeClient();

  const stateManagers = useMemo(() => {
    if (!metricsViewName) return undefined;
    return createStateManagers({
      queryClient,
      metricsViewName,
      exploreName,
      runtimeClient,
    });
  }, [metricsViewName, exploreName, runtimeClient]);

  // Parrot re-syncs the metrics view name when entering visual editing.
  useEffect(() => {
    if (visualEditing && stateManagers && metricsViewName) {
      stateManagers.metricsViewName.set(metricsViewName);
    }
  }, [visualEditing, stateManagers, metricsViewName]);

  return (
    <StateManagersContext.Provider value={stateManagers}>
      {children}
    </StateManagersContext.Provider>
  );
}

export function useStateManagers(): StateManagers {
  const ctx = useContext(StateManagersContext);
  if (!ctx) {
    throw new Error(
      "useStateManagers() must be used within a <StateManagersProvider> with a metricsViewName.",
    );
  }
  return ctx;
}
