// web-common/src/features/dashboards/filters/measure-filters/react/MeasureFilter.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
import type { MetricsViewSpecDimension } from "@statsparrot/web-common/runtime-client";
import type { FilterManager } from "@statsparrot/web-common/features/canvas/stores/filter-manager";
import type { MeasureFilterEntry } from "@statsparrot/web-common/features/dashboards/filters/measure-filters/measure-filter-entry";
import type { MeasureFilterItem } from "@statsparrot/web-common/features/dashboards/state-managers/selectors/measure-filters";
import MeasureFilterBody from "./MeasureFilterBody";
import MeasureFilterForm from "./MeasureFilterForm";
import MeasureChip from "./Chip";

export type MeasureFilterSide = "top" | "right" | "bottom" | "left";

export interface MeasureFilterProps {
  filterData: MeasureFilterItem;
  openOnMount?: boolean;
  allDimensions: MetricsViewSpecDimension[];
  side?: MeasureFilterSide;
  toggleFilterPin?: FilterManager["actions"]["toggleFilterPin"];
  toggleFilterRequired?: FilterManager["actions"]["toggleFilterRequired"];
  onRemove: () => void;
  onApply: (params: {
    dimension: string;
    oldDimension: string;
    filter: MeasureFilterEntry;
  }) => void;
}

/**
 * React translation of `MeasureFilter.svelte`. Renders the interactive measure filter
 * chip and, when open, the threshold / subquery edit form in a popover. The Svelte
 * `Popover.Root` / `Popover.Trigger` / Tooltip wrappers are replaced by a plain
 * absolutely-positioned popover with outside-click + Escape dismissal, matching the
 * approach taken by `DimensionFilter.tsx`.
 */
export default function MeasureFilter({
  filterData,
  openOnMount = false,
  allDimensions,
  side = "bottom",
  toggleFilterPin,
  toggleFilterRequired,
  onRemove,
  onApply,
}: MeasureFilterProps) {
  const { filter, pinned, label, measures, dimensionName, name, required, missingRequired } =
    filterData;

  const [open, setOpen] = useState(
    () => openOnMount && !filterData.filter,
  );
  const [curPinned, setCurPinned] = useState(pinned);
  const [curRequired, setCurRequired] = useState(required);
  const containerRef = useRef<HTMLDivElement>(null);

  const metricsViewNames = useMemo(
    () => (measures ? Array.from(measures.keys()) : []),
    [measures],
  );

  const displayDimensionName =
    allDimensions.find((d) => d.name === dimensionName)?.displayName ?? "";

  const handleOpenChange = useCallback(
    (nextOpen: boolean) => {
      if (nextOpen) {
        if (pinned !== curPinned) {
          toggleFilterPin?.(name, metricsViewNames);
        }
        if (required !== curRequired) {
          toggleFilterRequired?.(name, metricsViewNames);
        }
      }
    },
    [
      pinned,
      curPinned,
      required,
      curRequired,
      toggleFilterPin,
      toggleFilterRequired,
      name,
      metricsViewNames,
    ],
  );

  const toggleOpen = useCallback(() => {
    const nextOpen = !open;
    setOpen(nextOpen);
    handleOpenChange(nextOpen);
  }, [open, handleOpenChange]);

  const closeMenu = useCallback(() => {
    setOpen(false);
  }, []);

  const handleFormApply = useCallback(
    (params: {
      dimension: string;
      oldDimension: string;
      filter: MeasureFilterEntry;
    }) => {
      if (pinned !== curPinned) {
        toggleFilterPin?.(name, metricsViewNames);
      }
      if (required !== curRequired) {
        toggleFilterRequired?.(name, metricsViewNames);
      }
      onApply(params);
    },
    [
      pinned,
      curPinned,
      required,
      curRequired,
      toggleFilterPin,
      toggleFilterRequired,
      name,
      metricsViewNames,
      onApply,
    ],
  );

  // Close on outside click / Escape (Svelte `Popover.Root` + `svelte:window`).
  useEffect(() => {
    if (!open) return;
    function onPointerDown(event: MouseEvent) {
      if (
        containerRef.current &&
        !containerRef.current.contains(event.target as Node)
      ) {
        closeMenu();
      }
    }
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") {
        closeMenu();
      }
    }
    document.addEventListener("mousedown", onPointerDown);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("mousedown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [open, closeMenu]);

  const tooltipBody = missingRequired
    ? m.dashboard_filter_required_set_value()
    : m.dashboard_click_to_edit_values();
  const tooltipTitle = `${name} ${
    required ? m.dashboard_required_measure() : label || ""
  }`;

  return (
    <div className="relative inline-block" ref={containerRef}>
      <MeasureChip
        active={open}
        gray={!filter}
        error={!!missingRequired}
        theme
        label={label}
        title={`${tooltipTitle}: ${tooltipBody}`}
        removable={!curPinned && !required}
        removeTooltipText={m.dashboard_remove_label({ label })}
        onRemove={onRemove}
        onToggleOpen={toggleOpen}
      >
        <MeasureFilterBody
          dimensionName={displayDimensionName}
          filter={filter}
          label={label}
        />
      </MeasureChip>

      {open ? (
        <MeasureFilterForm
          dimensionName={dimensionName}
          name={name}
          label={label}
          filter={filter}
          onApply={handleFormApply}
          onClose={closeMenu}
          allDimensions={allDimensions}
          side={side}
          pinned={curPinned}
          showPinControl={!!toggleFilterPin}
          required={curRequired}
          showRequiredControl={!!toggleFilterRequired}
          onTogglePin={() => setCurPinned((p) => !p)}
          onToggleRequired={() => setCurRequired((r) => !r)}
        />
      ) : null}
    </div>
  );
}

// web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte
<script lang="ts">
  import { fly } from "svelte/transition";
  import { Chip } from "@statsparrot/web-common/components/chip";
  import * as Popover from "@statsparrot/web-common/components/popover/";
  import Tooltip from "@statsparrot/web-common/components/tooltip/Tooltip.svelte";
  import TooltipContent from "@statsparrot/web-common/components/tooltip/TooltipContent.svelte";
  import TooltipTitle from "@statsparrot/web-common/components/tooltip/TooltipTitle.svelte";
  import type { MeasureFilterEntry } from "@statsparrot/web-common/features/dashboards/filters/measure-filters/measure-filter-entry";
  import MeasureFilterBody from "@statsparrot/web-common/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte";
  import type { MetricsViewSpecDimension } from "@statsparrot/web-common/runtime-client";
  import MeasureFilterForm from "./MeasureFilterForm.svelte";
  import type { FilterManager } from "@statsparrot/web-common/features/canvas/stores/filter-manager";
  import type { MeasureFilterItem } from "../../state-managers/selectors/measure-filters";
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";

  export let filterData: MeasureFilterItem;
  export let openOnMount = false;
  export let allDimensions: MetricsViewSpecDimension[];
  export let side: "top" | "right" | "bottom" | "left" = "bottom";
  export let toggleFilterPin:
    | FilterManager["actions"]["toggleFilterPin"]
    | undefined = undefined;
  export let toggleFilterRequired:
    | FilterManager["actions"]["toggleFilterRequired"]
    | undefined = undefined;
  export let onRemove: () => void;
  export let onApply: (params: {
    dimension: string;
    oldDimension: string;
    filter: MeasureFilterEntry;
  }) => void;

  let open = openOnMount && !filterData.filter;
  let curPinned = filterData.pinned;
  let curRequired = filterData.required;

  $: ({
    filter,
    pinned,
    label,
    measures,
    dimensionName,
    name,
    required,
    missingRequired,
  } = filterData);

  $: metricsViewNames = measures ? Array.from(measures.keys()) : [];
</script>

<Popover.Root
  bind:open
  onOpenChange={() => {
    if (open && pinned !== curPinned) {
      toggleFilterPin?.(name, metricsViewNames);
    }
    if (open && required !== curRequired) {
      toggleFilterRequired?.(name, metricsViewNames);
    }
  }}
>
  <Popover.Trigger>
    {#snippet child({ props })}
      <Tooltip
        activeDelay={60}
        alignment="start"
        distance={8}
        location="bottom"
        suppress={open}
      >
        <Chip
          {...props}
          type="measure"
          active={open}
          {label}
          gray={!filter}
          error={!!missingRequired}
          theme
          {onRemove}
          removable={!curPinned && !required}
          removeTooltipText={m.dashboard_remove_label({ label })}
        >
          <MeasureFilterBody
            dimensionName={allDimensions.find((d) => {
              return d.name === dimensionName;
            })?.displayName ?? ""}
            {filter}
            {label}
            slot="body"
          />
        </Chip>
        <div slot="tooltip-content" transition:fly={{ duration: 100, y: 4 }}>
          <TooltipContent maxWidth="400px">
            <TooltipTitle>
              <svelte:fragment slot="name">{name}</svelte:fragment>
              <svelte:fragment slot="description"
                >{required
                  ? m.dashboard_required_measure()
                  : label || ""}</svelte:fragment
              >
            </TooltipTitle>

            {#if missingRequired}
              {m.dashboard_filter_required_set_value()}
            {:else}
              <slot name="body-tooltip-content"
                >{m.dashboard_click_to_edit_values()}</slot
              >
            {/if}
          </TooltipContent>
        </div>
      </Tooltip>
    {/snippet}
  </Popover.Trigger>

  {#if open}
    <MeasureFilterForm
      bind:open
      {name}
      {filter}
      {label}
      {dimensionName}
      {allDimensions}
      onApply={(params) => {
        if (pinned !== curPinned) {
          toggleFilterPin?.(name, metricsViewNames);
        }
        if (required !== curRequired) {
          toggleFilterRequired?.(name, metricsViewNames);
        }
        onApply(params);
      }}
      bind:pinned={curPinned}
      bind:required={curRequired}
      showPinControl={!!toggleFilterPin}
      showRequiredControl={!!toggleFilterRequired}
      {side}
    />
  {/if}
</Popover.Root>
