// web-common/src/features/dashboards/filters/measure-filters/react/MeasureFilterBody.tsx
import { useMemo } from "react";
import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
import type { MeasureFilterEntry } from "@statsparrot/web-common/features/dashboards/filters/measure-filters/measure-filter-entry";
import {
  AllMeasureFilterOperationOptions,
  AllMeasureFilterTypeOptions,
  MeasureFilterOperation,
  MeasureFilterType,
} from "@statsparrot/web-common/features/dashboards/filters/measure-filters/measure-filter-options";

export interface MeasureFilterBodyProps {
  dimensionName: string;
  label?: string;
  filter?: MeasureFilterEntry;
  labelMaxWidth?: string;
  comparisonLabel?: string;
}

/**
 * React translation of `MeasureFilterBody.svelte`. Renders the body content of a
 * measure filter chip: the measure label, the optional "for {dimension}" suffix, the
 * comparison type label, and the short-hand notation of the filter criteria.
 */
export default function MeasureFilterBody({
  dimensionName,
  label,
  filter,
  labelMaxWidth = "320px",
  comparisonLabel = "",
}: MeasureFilterBodyProps) {
  const { typeLabel, shortLabel } = useMemo(() => {
    if (!filter) return { typeLabel: undefined, shortLabel: undefined };

    let typeLabel: string | undefined;
    let shortLabel: string | undefined;

    const typeOption = AllMeasureFilterTypeOptions.find(
      (o) => o.value === filter.type,
    );
    typeLabel = typeOption?.shortLabel;

    if (
      filter.type === MeasureFilterType.AbsoluteChange ||
      filter.type === MeasureFilterType.PercentChange
    ) {
      typeLabel =
        (typeLabel ?? "") +
        " " +
        m.filter_measure_from_comparison({ comparison: comparisonLabel });
    }

    switch (filter.operation) {
      case MeasureFilterOperation.GreaterThan:
      case MeasureFilterOperation.GreaterThanOrEquals:
      case MeasureFilterOperation.LessThan:
      case MeasureFilterOperation.LessThanOrEquals:
      case MeasureFilterOperation.Equals:
      case MeasureFilterOperation.NotEquals:
        shortLabel =
          (AllMeasureFilterOperationOptions.find(
            (o) => o.value === filter.operation,
          )?.shortLabel ?? "") +
          " " +
          filter.value1 +
          (filter.type === MeasureFilterType.PercentChange ? "%" : "");
        break;
      case MeasureFilterOperation.Between:
        shortLabel = `(${filter.value1},${filter.value2})`;
        break;
      case MeasureFilterOperation.NotBetween:
        shortLabel = `!(${filter.value1},${filter.value2})`;
        break;
    }

    return { typeLabel, shortLabel };
  }, [filter, comparisonLabel]);

  return (
    <div className="flex gap-x-2">
      <div
        className="font-bold text-ellipsis overflow-hidden whitespace-nowrap"
        style={{ maxWidth: labelMaxWidth }}
      >
        {label}
        {dimensionName ? (
          <span>
            {m.filter_measure_for_dimension({ dimension: dimensionName })}
          </span>
        ) : null}
        {typeLabel ? <span>{typeLabel}</span> : null}
      </div>
      <div className="flex flex-wrap flex-row items-baseline gap-y-1">
        {shortLabel ? shortLabel : null}
      </div>
    </div>
  );
}

// web-common/src/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte
<!-- @component
  renders the body content of a filter set chip:
  - a label for the current measure
  - a short hand notation of the filter criteria
-->
<script lang="ts">
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
  import type { MeasureFilterEntry } from "@statsparrot/web-common/features/dashboards/filters/measure-filters/measure-filter-entry";
  import {
    AllMeasureFilterOperationOptions,
    AllMeasureFilterTypeOptions,
    MeasureFilterOperation,
    MeasureFilterType,
  } from "@statsparrot/web-common/features/dashboards/filters/measure-filters/measure-filter-options";

  export let dimensionName: string;
  export let label: string | undefined;
  export let filter: MeasureFilterEntry | undefined;
  export let labelMaxWidth = "320px";
  export let comparisonLabel = "";

  let typeLabel: string | undefined;
  let shortLabel: string | undefined;
  $: if (filter) {
    const typeOption = AllMeasureFilterTypeOptions.find(
      (o) => o.value === filter?.type,
    );
    typeLabel = typeOption?.shortLabel;

    if (
      filter.type === MeasureFilterType.AbsoluteChange ||
      filter.type === MeasureFilterType.PercentChange
    ) {
      typeLabel +=
        " " + m.filter_measure_from_comparison({ comparison: comparisonLabel });
    }

    switch (filter.operation) {
      case MeasureFilterOperation.GreaterThan:
      case MeasureFilterOperation.GreaterThanOrEquals:
      case MeasureFilterOperation.LessThan:
      case MeasureFilterOperation.LessThanOrEquals:
      case MeasureFilterOperation.Equals:
      case MeasureFilterOperation.NotEquals:
        shortLabel =
          AllMeasureFilterOperationOptions.find(
            (o) => o.value === filter?.operation,
          )?.shortLabel +
          " " +
          filter.value1 +
          (filter.type === MeasureFilterType.PercentChange ? "%" : "");
        break;
      case MeasureFilterOperation.Between:
        shortLabel = `(${filter.value1},${filter.value2})`;
        break;
      case MeasureFilterOperation.NotBetween:
        shortLabel = `!(${filter.value1},${filter.value2})`;
        break;
    }
  }
</script>

<div class="flex gap-x-2">
  <div
    class="font-bold text-ellipsis overflow-hidden whitespace-nowrap"
    style:max-width={labelMaxWidth}
  >
    {label}
    {#if dimensionName}
      <!-- span needed to make sure the space before the `for` is not removed by prettier -->
      <span>
        {m.filter_measure_for_dimension({ dimension: dimensionName })}</span
      >
    {/if}
    {#if typeLabel}
      <span>{typeLabel}</span>
    {/if}
  </div>
  <div class="flex flex-wrap flex-row items-baseline gap-y-1">
    {#if shortLabel}
      {shortLabel}
    {/if}
  </div>
</div>
