// web-common/src/features/file-explorer/react/FileExplorer.tsx
// React translation of `features/file-explorer/FileExplorer.svelte`. The runtime
// file-tree query (`createRuntimeServiceListFiles`), the rename/duplicate/delete
// actions and the drag-drop handlers are exposed as props (wired in the
// runtime-bound phase), so the shell renders the project header, the collapse-all
// control and the recursive tree from a supplied `Directory`. The loading/error
// states and the force-delete confirmation mirror the Svelte original.
import { useState } from "react";
import { useReadable } from "@statsparrot/web-common/features/components/charts/react/useReadable";
import {
  collectDirectoryPaths,
  findDirectory,
  type Directory,
} from "./transform-file-list";
import { directoryState } from "./directory-state";
import NavDirectory from "./NavDirectory";
import ForceDeleteConfirmationDialog from "./ForceDeleteConfirmationDialog";
import {
  ChevronsDownUpIcon,
  ChevronsUpDownIcon,
} from "./icons";
import type { NavDragData } from "./types";

export interface FileExplorerProps {
  fileTree?: Directory;
  projectTitle?: string;
  hasUnsaved?: boolean;
  isLoading?: boolean;
  isError?: boolean;
  onRename: (filePath: string, isDir: boolean) => void;
  onDuplicate: (filePath: string, isDir: boolean) => void;
  onDelete: (filePath: string, isDir: boolean) => void;
  onMouseDown: (e: MouseEvent, dragData: NavDragData) => void;
  onDropSuccess?: (fromPath: string, toDir: string) => Promise<void>;
  hrefPrefix?: string;
}

export default function FileExplorer({
  fileTree,
  projectTitle = "Untitled Parrot Project",
  hasUnsaved = false,
  isLoading = false,
  isError = false,
  onRename,
  onDuplicate,
  onDelete,
  onMouseDown,
  hrefPrefix = "",
}: FileExplorerProps) {
  const state = useReadable(directoryState) ?? {};
  const directoryPaths = fileTree ? collectDirectoryPaths(fileTree) : [];
  const allDirectoriesCollapsed =
    directoryPaths.length > 0 &&
    directoryPaths.every((path) => state[path] === false);
  const toggleAllLabel = allDirectoriesCollapsed
    ? "Expand all folders"
    : "Collapse all folders";

  // Mirrors the Svelte onDelete: a non-empty directory routes through the
  // force-delete confirmation instead of deleting directly.
  const [showForceDelete, setShowForceDelete] = useState(false);
  const [forceDeletePath, setForceDeletePath] = useState<string | null>(null);

  function handleToggleAll() {
    if (!fileTree) return;
    if (allDirectoriesCollapsed) {
      directoryState.expandAll(directoryPaths);
    } else {
      directoryState.collapseAll(directoryPaths);
    }
  }

  function handleDelete(filePath: string, isDir: boolean) {
    if (isDir && fileTree) {
      const dir = findDirectory(fileTree, filePath);
      if (dir?.directories?.length || dir?.files?.length) {
        setForceDeletePath(filePath);
        setShowForceDelete(true);
        return;
      }
    }
    onDelete(filePath, isDir);
  }

  return (
    <>
      <div className="project-header sticky top-0 z-10 bg-surface-base flex items-center justify-between gap-x-1 h-7 w-full pl-2 pr-1.5">
        <h3
          className="truncate font-semibold text-[10px] uppercase text-fg-muted"
          title={projectTitle}
        >
          {projectTitle}
        </h3>
        {directoryPaths.length ? (
          <button
            type="button"
            className="flex flex-none items-center justify-center size-5 rounded text-fg-secondary hover:bg-surface-hover hover:text-fg-primary"
            aria-label={toggleAllLabel}
            title={toggleAllLabel}
            onClick={handleToggleAll}
            data-testid="file-explorer-collapse-all"
          >
            {allDirectoriesCollapsed ? (
              <ChevronsUpDownIcon size="14px" />
            ) : (
              <ChevronsDownUpIcon size="14px" />
            )}
          </button>
        ) : null}
      </div>

      <ul className="flex flex-col w-full items-start justify-start overflow-auto">
        {fileTree ? (
          <NavDirectory
            directory={fileTree}
            onRename={onRename}
            onDuplicate={onDuplicate}
            onDelete={handleDelete}
            onMouseDown={onMouseDown}
            hrefPrefix={hrefPrefix}
          />
        ) : isLoading ? (
          <div className="flex flex-col gap-y-1.5 w-full px-2 py-2">
            {[0.7, 0.5, 0.8, 0.6, 0.55, 0.65].map((width, i) => (
              <div
                key={i}
                className="h-5 bg-gray-200 animate-pulse rounded"
                style={{ width: `${width * 100}%` }}
              />
            ))}
          </div>
        ) : isError ? (
          <div className="px-2 py-3 text-xs text-fg-muted">
            Failed to load files
          </div>
        ) : null}
      </ul>

      <ForceDeleteConfirmationDialog
        open={showForceDelete}
        filePath={forceDeletePath ?? undefined}
        onClose={() => setShowForceDelete(false)}
        onDelete={() => {
          if (forceDeletePath) onDelete(forceDeletePath, true);
          setShowForceDelete(false);
        }}
      />
    </>
  );
}

// web-common/src/features/file-explorer/FileExplorer.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import RenameAssetModal from "@statsparrot/web-common/features/entity-management/actions/RenameAssetModal.svelte";
  import {
    navigateToFile,
    navigateToHome,
  } from "@statsparrot/web-common/layout/navigation/editor-routing";
  import {
    deleteFileArtifact,
    duplicateFileArtifact,
    renameFileArtifact,
  } from "@statsparrot/web-common/features/entity-management/actions/actions.ts";
  import { removeLeadingSlash } from "@statsparrot/web-common/features/entity-management/entity-mappers";
  import {
    getTopLevelFolder,
    splitFolderAndFileName,
  } from "@statsparrot/web-common/features/entity-management/file-path-utils";
  import ForceDeleteConfirmation from "@statsparrot/web-common/features/file-explorer/ForceDeleteConfirmationDialog.svelte";
  import NavEntryPortal from "@statsparrot/web-common/features/file-explorer/NavEntryPortal.svelte";
  import { navEntryDragDropStore } from "@statsparrot/web-common/features/file-explorer/nav-entry-drag-drop-store";
  import { isCurrentActivePage } from "@statsparrot/web-common/features/file-explorer/utils";
  import { createRuntimeServiceListFiles } from "@statsparrot/web-common/runtime-client";
  import { useRuntimeClient } from "@statsparrot/web-common/runtime-client/v2";
  import { eventBus } from "../../lib/event-bus/event-bus";
  import { fileArtifacts } from "../entity-management/file-artifacts";
  import { useProjectTitle } from "@statsparrot/web-common/features/project/selectors";
  import { createLocalServiceGetMetadata } from "@statsparrot/web-common/runtime-client/local-service";
  import { ChevronsDownUp, ChevronsUpDown } from "lucide-svelte";
  import NavDirectory from "./NavDirectory.svelte";
  import { directoryState } from "./directory-store";
  import {
    collectDirectoryPaths,
    findDirectory,
    transformFileList,
  } from "./transform-file-list";
  import QuickView from "@statsparrot/web-common/features/resource-graph/quick-view/QuickView.svelte";
  import {
    isPinned,
    isProtectedDirectory,
    isManaged,
  } from "@statsparrot/web-common/features/entity-management/actions/protected-files.ts";

  export let hasUnsaved: boolean;

  const runtimeClient = useRuntimeClient();

  $: getFileTree = createRuntimeServiceListFiles(
    runtimeClient,
    {},
    {
      query: {
        select: (data) => {
          if (!data || !data.files?.length) return;

          const files = data.files
            // Sort alphabetically case-insensitive
            .sort(
              (a, b) =>
                a.path?.localeCompare(b.path ?? "", undefined, {
                  sensitivity: "base",
                }) ?? 0,
            )
            // Hide dot directories
            .filter(
              (file) =>
                !(
                  file.isDir &&
                  // Check both the top-level directory and subdirectories
                  (file.path?.startsWith(".") || file.path?.includes("/."))
                ),
            )
            // Hide the `tmp` directory
            .filter((file) => !file.path?.startsWith("/tmp"));

          return transformFileList(files);
        },
      },
    },
  );

  $: ({ data: fileTree } = $getFileTree);

  $: projectTitleQuery = useProjectTitle(runtimeClient);
  $: projectTitle = $projectTitleQuery?.data ?? "Untitled Parrot Project";

  // Scope the persisted expand/collapse state per project. In the cloud the
  // instanceId is unique per project; in Parrot Developer it is always "default",
  // so fall back to the on-disk project path there (GetMetadata is a local-only
  // endpoint that simply errors in the cloud).
  $: ({ instanceId } = runtimeClient);
  $: projectMetadataQuery = createLocalServiceGetMetadata({
    query: { retry: false },
  });
  $: projectScopeId = $projectMetadataQuery.isLoading
    ? undefined
    : ($projectMetadataQuery.data?.projectPath ?? instanceId);
  $: if (projectScopeId) directoryState.setProjectScope(projectScopeId);

  $: directoryPaths = fileTree ? collectDirectoryPaths(fileTree) : [];
  $: allDirectoriesCollapsed =
    directoryPaths.length > 0 &&
    directoryPaths.every((path) => $directoryState[path] === false);
  $: toggleAllDirectoriesLabel = allDirectoriesCollapsed
    ? "Expand all folders"
    : "Collapse all folders";

  function toggleAllDirectories() {
    if (!fileTree) return;
    if (allDirectoriesCollapsed) {
      directoryState.expandAll(directoryPaths);
    } else {
      directoryState.collapseAll(directoryPaths);
    }
  }

  let showRenameModelModal = false;
  let renameFilePath: string;
  let renameIsDir: boolean;

  function onRename(filePath: string, isDir: boolean) {
    showRenameModelModal = true;
    renameFilePath = filePath;
    renameIsDir = isDir;
  }

  async function onDuplicate(filePath: string, isDir: boolean) {
    if (isDir) {
      throw new Error("Copying directories is not supported");
    }

    try {
      const newFilePath = await duplicateFileArtifact(runtimeClient, filePath);
      await navigateToFile(newFilePath);
    } catch {
      eventBus.emit("notification", {
        message: `Failed to copy ${filePath}`,
      });
    }
  }

  let forceDeletePath: string;
  let showForceDelete = false;

  async function onDelete(filePath: string, isDir: boolean) {
    if (!$getFileTree.data) return;

    if (isDir) {
      const dir = findDirectory($getFileTree.data, filePath);
      if (dir?.directories?.length || dir?.files?.length) {
        forceDeletePath = filePath;
        showForceDelete = true;
        return;
      }
    }
    await deleteFileArtifact(runtimeClient, filePath);
    if (isCurrentActivePage(filePath, isDir)) {
      await navigateToHome();
    }
  }

  async function onForceDelete() {
    await deleteFileArtifact(runtimeClient, forceDeletePath, true);
    // onForceDelete is only called on folders, so isDir is always true
    if (isCurrentActivePage(forceDeletePath, true)) {
      await navigateToHome();
    }
  }

  const { dragData, position } = navEntryDragDropStore;

  async function handleDropSuccess(fromPath: string, toDir: string) {
    const isCurrentFile =
      $page.params.file && // handle case when user is on home page
      removeLeadingSlash(fromPath) === removeLeadingSlash($page.params.file);
    const [, srcFile] = splitFolderAndFileName(fromPath);
    const newFilePath = `${toDir === "/" ? toDir : toDir + "/"}${srcFile}`;

    if (fromPath !== newFilePath) {
      const newTopLevelPath = getTopLevelFolder(newFilePath);
      if (isProtectedDirectory(newTopLevelPath)) {
        eventBus.emit("notification", {
          message: "cannot move to restricted directories",
        });
        return;
      }
      if (isPinned(newFilePath) || isManaged(newFilePath)) {
        eventBus.emit("notification", {
          message: "cannot rename to a restricted file",
        });
        return;
      }
      await renameFileArtifact(runtimeClient, fromPath, newFilePath);

      if (isCurrentFile) {
        await navigateToFile(newFilePath);
      }
    }
  }

  async function saveAll(e: KeyboardEvent) {
    if (e.code === "KeyS" && e.metaKey && e.altKey) {
      e.preventDefault();
      await fileArtifacts.saveAll();
    }
  }
</script>

<svelte:window
  onbeforeunload={(event) => {
    if (hasUnsaved) {
      event.preventDefault();
      return confirm(
        "Are you sure you want to leave? Unsaved changes will be lost.",
      );
    }
  }}
  onmousemove={(e) => navEntryDragDropStore.onMouseMove(e)}
  onmouseup={(e) => navEntryDragDropStore.onMouseUp(e, handleDropSuccess)}
  onkeydown={saveAll}
/>

<!-- Project header with a collapse-all control -->
<div class="project-header">
  <h3 class="truncate" title={projectTitle}>{projectTitle}</h3>
  {#if directoryPaths.length}
    <button
      type="button"
      class="collapse-all"
      aria-label={toggleAllDirectoriesLabel}
      title={toggleAllDirectoriesLabel}
      onclick={toggleAllDirectories}
    >
      {#if allDirectoriesCollapsed}
        <ChevronsUpDown size="14px" />
      {:else}
        <ChevronsDownUp size="14px" />
      {/if}
    </button>
  {/if}
</div>

<!-- File tree -->
<ul class="flex flex-col w-full items-start justify-start overflow-auto">
  {#if fileTree}
    <NavDirectory
      directory={fileTree}
      {onRename}
      {onDuplicate}
      {onDelete}
      onMouseDown={(e, dragData) =>
        navEntryDragDropStore.onMouseDown(e, dragData)}
    />
  {:else if $getFileTree.isLoading}
    <div class="flex flex-col gap-y-1.5 w-full px-2 py-2">
      {#each [0.7, 0.5, 0.8, 0.6, 0.55, 0.65] as width}
        <div
          class="h-5 bg-gray-200 animate-pulse rounded"
          style:width="{width * 100}%"
        ></div>
      {/each}
    </div>
  {:else if $getFileTree.isError}
    <div class="px-2 py-3 text-xs text-fg-muted">Failed to load files</div>
  {/if}
</ul>

{#if showRenameModelModal}
  <RenameAssetModal
    closeModal={() => (showRenameModelModal = false)}
    filePath={renameFilePath}
    isDir={renameIsDir}
  />
{/if}

{#if $dragData}
  <NavEntryPortal position={$position} dragData={$dragData} />
{/if}

<ForceDeleteConfirmation bind:open={showForceDelete} onDelete={onForceDelete} />

<QuickView />

<style lang="postcss">
  .project-header {
    @apply sticky top-0 z-10 bg-surface-base;
    @apply flex items-center justify-between gap-x-1;
    @apply h-7 w-full pl-2 pr-1.5;
  }

  h3 {
    @apply truncate font-semibold text-[10px] uppercase text-fg-muted;
  }

  .collapse-all {
    @apply flex flex-none items-center justify-center;
    @apply size-5 rounded text-fg-secondary;
  }

  .collapse-all:hover,
  .collapse-all:focus-visible {
    @apply bg-surface-hover text-fg-primary;
  }
</style>
