// web-common/src/features/file-explorer/react/NavDirectory.tsx
// React translation of `features/file-explorer/NavDirectory.svelte`. Recursively
// renders the directory tree; expansion state comes from the React-safe
// `directoryState` store. The drag/drop hover highlight is deferred to the
// runtime-bound phase (shown here as a no-op), and file/dir handlers are props.
import { useReadable } from "@statsparrot/web-common/features/components/charts/react/useReadable";
import type { Directory } from "./transform-file-list";
import { directoryState } from "./directory-state";
import NavDirectoryEntry from "./NavDirectoryEntry";
import NavFile from "./NavFile";
import type { NavDragData } from "./types";

export interface TreeHandlers {
  onRename: (filePath: string, isDir: boolean) => void;
  onDuplicate: (filePath: string, isDir: boolean) => void;
  onDelete: (filePath: string, isDir: boolean) => void;
  onMouseDown: (e: MouseEvent, dragData: NavDragData) => void;
}

export default function NavDirectory({
  directory,
  onRename,
  onDuplicate,
  onDelete,
  onMouseDown,
  hrefPrefix = "",
}: {
  directory: Directory;
  hrefPrefix?: string;
} & TreeHandlers) {
  const state = useReadable(directoryState) ?? {};
  const expanded = state[directory.path] ?? true;

  return (
    <ul
      id={`nav-${directory.path}`}
      aria-label={directory.path}
      role="directory"
      className="w-full"
    >
      {directory.path !== "/" ? (
        <NavDirectoryEntry
          dir={directory}
          onRename={onRename}
          onDelete={onDelete}
          onMouseDown={onMouseDown}
        />
      ) : null}

      {expanded ? (
        <>
          {directory.directories.map((dir) => (
            <NavDirectory
              key={dir.path}
              directory={dir}
              onRename={onRename}
              onDuplicate={onDuplicate}
              onDelete={onDelete}
              onMouseDown={onMouseDown}
              hrefPrefix={hrefPrefix}
            />
          ))}
          {directory.files.map((file) => {
            const filePath =
              directory.path === "/" ? `/${file}` : `${directory.path}/${file}`;
            return (
              <NavFile
                key={filePath}
                filePath={filePath}
                onRename={onRename}
                onDuplicate={onDuplicate}
                onDelete={onDelete}
                onMouseDown={onMouseDown}
                hrefPrefix={hrefPrefix}
              />
            );
          })}
        </>
      ) : null}
    </ul>
  );
}

// web-common/src/features/file-explorer/NavDirectory.svelte
<script lang="ts">
  import NavDirectoryEntry from "@statsparrot/web-common/features/file-explorer/NavDirectoryEntry.svelte";
  import {
    navEntryDragDropStore,
    type NavDragData,
  } from "@statsparrot/web-common/features/file-explorer/nav-entry-drag-drop-store";
  import NavFile from "./NavFile.svelte";
  import { directoryState } from "./directory-store";
  import type { Directory } from "./transform-file-list";

  export let directory: Directory;
  export let onRename: (filePath: string, isDir: boolean) => void;
  export let onDuplicate: (filePath: string, isDir: boolean) => void;
  export let onDelete: (filePath: string, isDir: boolean) => void;
  export let onMouseDown: (e: MouseEvent, dragData: NavDragData) => void;

  // Directories are expanded by default; only explicitly collapsed ones are false.
  $: expanded = $directoryState[directory.path] ?? true;
  const { dragData, dropDirs } = navEntryDragDropStore;
  $: isDragDropHover =
    $dragData && $dropDirs[$dropDirs.length - 1] === directory.path;
</script>

<ul
  id={`nav-${directory.path}`}
  aria-label={directory.path}
  role="directory"
  class="w-full"
  class:bg-gray-100={isDragDropHover}
  onmouseenter={() => navEntryDragDropStore.onMouseEnter(directory.path)}
  onmouseleave={() => navEntryDragDropStore.onMouseLeave()}
  oncontextmenu={() => navEntryDragDropStore.resetDrag()}
>
  {#if directory.path !== "/"}
    <NavDirectoryEntry dir={directory} {onRename} {onDelete} {onMouseDown} />
  {/if}

  {#if expanded}
    {#if directory?.directories}
      {#each directory.directories as dir (dir.path)}
        <!-- Recursive call to display subdirectories -->
        <svelte:self
          directory={dir}
          {onRename}
          {onDuplicate}
          {onDelete}
          {onMouseDown}
        />
      {/each}
    {/if}

    {#each directory.files as file (file)}
      {@const filePath =
        directory.path === "/" ? `/${file}` : `${directory.path}/${file}`}
      <NavFile {filePath} {onRename} {onDuplicate} {onDelete} {onMouseDown} />
    {/each}
  {/if}
</ul>
