// web-common/src/features/file-explorer/NavEntryPortal.svelte
<script lang="ts">
  import File from "@statsparrot/web-common/components/icons/File.svelte";
  import { resourceIconMapping } from "@statsparrot/web-common/features/entity-management/resource-icon-mapping";
  import type { NavDragData } from "@statsparrot/web-common/features/file-explorer/nav-entry-drag-drop-store";
  import { portal } from "@statsparrot/web-common/lib/actions/portal";
  import { Folder } from "lucide-svelte";

  export let position = { left: 0, top: 0 };
  export let dragData: NavDragData;
</script>

<div
  class="portal-item"
  style:left="{position.left}px"
  style:top="{position.top}px"
  use:portal
>
  <div class="flex flex-row gap-x-1">
    {#if dragData.isDir}
      <Folder className="text-fg-secondary" size="14px" />
    {:else}
      <svelte:component
        this={dragData.kind ? resourceIconMapping[dragData.kind] : File}
        className="text-fg-secondary"
        size="14px"
      />
    {/if}
    <span>{dragData.fileName ?? ""}</span>
  </div>
</div>

<style lang="postcss">
  .portal-item {
    @apply shadow-lg shadow-gray-300;
    @apply z-50;
    @apply absolute pointer-events-none;
  }
</style>

// web-common/src/features/file-explorer/react/NavEntryPortal.tsx
// React translation of `features/file-explorer/NavEntryPortal.svelte` — the ghost
// dragged entry shown while a nav item is dragged. Kept as a fixed-position
// label; the drag/drop wiring is deferred to the runtime-bound phase.
import type { NavDragData } from "./types";

export default function NavEntryPortal({
  position,
  dragData,
}: {
  position: { left: number; top: number };
  dragData: NavDragData;
}) {
  return (
    <div
      className="fixed z-50 pointer-events-none rounded bg-popover text-popover-foreground shadow-lg px-2 py-1 text-xs"
      style={{ left: position.left, top: position.top }}
      data-testid="nav-entry-portal"
    >
      {dragData.fileName ?? dragData.filePath}
    </div>
  );
}
