// web-common/src/layout/navigation/Navigation.svelte
<script lang="ts" context="module">
  export const navigationOpen = (() => {
    const { subscribe, update, set } = writable<boolean | null>(true);
    return {
      toggle: () => update((open) => !open),
      set,
      subscribe,
    };
  })();
</script>

<script lang="ts">
  import CaretDownIcon from "@statsparrot/web-common/components/icons/CaretDownIcon.svelte";
  import { connectorExplorerStore } from "@statsparrot/web-common/features/connectors/explorer/connector-explorer-store";
  import { fileArtifacts } from "@statsparrot/web-common/features/entity-management/file-artifacts";
  import { writable } from "svelte/store";
  import ConnectorExplorer from "../../features/connectors/explorer/ConnectorExplorer.svelte";
  import AddAssetButton from "../../features/entity-management/add/AddAssetButton.svelte";
  import FileExplorer from "../../features/file-explorer/FileExplorer.svelte";
  import Resizer from "../Resizer.svelte";
  import { DEFAULT_NAV_WIDTH, MAX_NAV_WIDTH, MIN_NAV_WIDTH } from "../config";
  import Footer from "./Footer.svelte";
  import SurfaceControlButton from "./SurfaceControlButton.svelte";
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";

  // When false, hides the footer (version info, links, traffic light).
  // Used in cloud editing where the footer isn't relevant.
  export let showFooterLinks = true;

  const DEFAULT_PERCENTAGE = 0.4;

  let width = DEFAULT_NAV_WIDTH;
  let previousWidth: number;
  let resizing = false;
  let resizingConnector = false;
  let connectorHeightPercentage = DEFAULT_PERCENTAGE;
  let contentRect = new DOMRectReadOnly(0, 0, 0, 0);
  let connectorWrapper: HTMLDivElement;

  $: navWrapperHeight = contentRect.height;

  let showConnectors = true;

  $: connectorSectionHeight = navWrapperHeight * connectorHeightPercentage;

  $: ({ unsavedFiles } = fileArtifacts);
  $: ({ size: unsavedFileCount } = $unsavedFiles);

  function handleResize(
    e: UIEvent & {
      currentTarget: EventTarget & Window;
    },
  ) {
    const currentWidth = e.currentTarget.innerWidth;

    const open = $navigationOpen;

    if (open && currentWidth < previousWidth && currentWidth < 768) {
      $navigationOpen = null;
    } else if (open === null && currentWidth > 768) {
      $navigationOpen = true;
    }

    previousWidth = currentWidth;
  }
</script>

<svelte:window
  onresize={handleResize}
  onkeydown={(e) => {
    const isMac = window.navigator.userAgent.includes("Macintosh");

    if (e[isMac ? "metaKey" : "ctrlkey"] && e.key === "b") {
      navigationOpen.toggle();
    }
  }}
/>

<nav
  class="sidebar bg-surface-base"
  class:hide={!$navigationOpen}
  class:resizing
  style:width="{width}px"
>
  <Resizer
    min={MIN_NAV_WIDTH}
    basis={DEFAULT_NAV_WIDTH}
    max={MAX_NAV_WIDTH}
    dimension={width}
    onUpdate={(w) => {
      width = w;
    }}
    bind:resizing
    side="right"
  />
  <div class="inner" style:width="{width}px">
    <div class="p-2 w-full pr-10">
      <AddAssetButton />
    </div>
    <div class="scroll-container">
      <div class="nav-wrapper" bind:contentRect>
        <section class="size-full overflow-y-auto pb-4">
          <FileExplorer hasUnsaved={unsavedFileCount > 0} />
        </section>

        {#if navWrapperHeight}
          <section class="connector-section">
            {#if showConnectors}
              <Resizer
                dimension={connectorSectionHeight}
                onUpdate={(height) => {
                  connectorHeightPercentage = height / navWrapperHeight;
                }}
                direction="NS"
                side="top"
                min={0}
                basis={navWrapperHeight * DEFAULT_PERCENTAGE}
                max={navWrapperHeight * 0.9}
                bind:resizing={resizingConnector}
              />
            {/if}

            <button
              onclick={() => {
                const open = showConnectors;

                if (!open) showConnectors = true;

                connectorWrapper.animate(
                  [
                    {
                      height: `${open ? connectorSectionHeight : 0}px`,
                    },
                    {
                      height: `${open ? 0 : connectorSectionHeight}px`,
                    },
                  ],
                  {
                    duration: 200,
                    easing: "ease-out",
                  },
                ).onfinish = () => {
                  if (open) showConnectors = false;
                };
              }}
            >
              <CaretDownIcon
                size="14px"
                className="text-fg-secondary transition-transform {!showConnectors &&
                  '-rotate-90'}"
              />
              <h3 class="text-fg-muted">{m.nav_data_explorer()}</h3>
            </button>

            <div
              class="connector-wrapper"
              role="region"
              aria-label={m.nav_data_explorer()}
              bind:this={connectorWrapper}
              style:height="{showConnectors ? connectorSectionHeight : 0}px"
            >
              {#if showConnectors}
                <ConnectorExplorer store={connectorExplorerStore} />
              {/if}
            </div>
          </section>
        {/if}
      </div>
    </div>
    {#if showFooterLinks}
      <Footer />
    {/if}
  </div>
</nav>

<SurfaceControlButton
  {resizing}
  navWidth={width}
  navOpen={!!$navigationOpen}
  onClick={navigationOpen.toggle}
/>

<style lang="postcss">
  .sidebar {
    @apply flex flex-col flex-none relative overflow-hidden;
    @apply h-full border-r z-0;
    @apply select-none;
    transition-property: width;
    will-change: width;
  }

  .inner {
    @apply h-full overflow-hidden flex flex-col;
    will-change: width;
  }

  .nav-wrapper {
    @apply flex flex-col size-full;
  }

  .scroll-container {
    @apply overflow-y-auto overflow-x-hidden;
    @apply h-full;
  }

  .sidebar:not(.resizing) {
    transition-duration: 300ms;
    transition-timing-function: ease-in-out;
  }

  .hide {
    width: 0px !important;
  }

  .connector-section {
    @apply flex flex-col flex-none h-fit;
    @apply border-t relative;
  }

  .connector-wrapper {
    @apply overflow-y-auto;
  }

  button {
    @apply flex gap-x-1 items-center w-full;
    @apply pl-2 pr-3.5 py-1.5 cursor-pointer;
    @apply text-fg-secondary;
  }

  button:hover {
    @apply bg-gray-100;
  }

  h3 {
    @apply font-semibold text-[10px] uppercase;
  }
</style>

// web-common/src/layout/react/Navigation.tsx
// React translation of `layout/navigation/Navigation.svelte`. The feature-heavy
// children (AddAssetButton, FileExplorer, ConnectorExplorer, Footer) are exposed
// as props so the shell renders in isolation (and is unit-testable) while the
// features get wired in their own port phases. The `navigationOpen` store
// (`./store`) and the dragged-width / connector-height state mirror the Svelte
// original, including the cmd/ctrl+B toggle and the responsive auto-collapse.
import { useEffect, useRef, useState, type ReactNode } from "react";
import { useReadable } from "@statsparrot/web-common/features/components/charts/react/useReadable";
import {
  DEFAULT_NAV_WIDTH,
  MAX_NAV_WIDTH,
  MIN_NAV_WIDTH,
} from "@statsparrot/web-common/layout/config";
import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
import { navigationOpen } from "./store";
import { Resizer } from "./Resizer";
import Footer from "./Footer";
import SurfaceControlButton from "./SurfaceControlButton";
import { CaretDownIcon } from "./icons";

const DEFAULT_PERCENTAGE = 0.4;

export interface NavigationProps {
  showFooterLinks?: boolean;
  addAsset?: ReactNode;
  fileExplorer?: ReactNode;
  connectorExplorer?: ReactNode;
  dataExplorerTitle?: string;
  footer?: ReactNode;
}

export default function Navigation({
  showFooterLinks = true,
  addAsset,
  fileExplorer,
  connectorExplorer,
  dataExplorerTitle,
  footer,
}: NavigationProps) {
  const open = useReadable(navigationOpen);
  const [width, setWidth] = useState(DEFAULT_NAV_WIDTH);
  const [resizing, setResizing] = useState(false);
  const [resizingConnector, setResizingConnector] = useState(false);
  const [connectorHeightPercentage, setConnectorHeightPercentage] =
    useState(DEFAULT_PERCENTAGE);
  const [navWrapperHeight, setNavWrapperHeight] = useState(0);
  const [showConnectors, setShowConnectors] = useState(true);

  const navWrapperRef = useRef<HTMLDivElement>(null);
  const connectorWrapperRef = useRef<HTMLDivElement>(null);
  const previousWidthRef = useRef<number>(DEFAULT_NAV_WIDTH);

  // Measure the content column so the connector section can be sized relatively.
  useEffect(() => {
    const el = navWrapperRef.current;
    if (!el || typeof ResizeObserver === "undefined") return;
    const observer = new ResizeObserver((entries) => {
      for (const entry of entries) {
        setNavWrapperHeight(entry.contentRect.height);
      }
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  // Responsive collapse + cmd/ctrl+B toggle, mirroring the Svelte window handlers.
  useEffect(() => {
    const handleResize = (e: UIEvent) => {
      const currentWidth = (e.currentTarget as Window).innerWidth;
      const current = navigationOpen;
      // `useReadable` holds the snapshot; read via subscribe for the latest.
      let openState: boolean | null = true;
      const unsub = navigationOpen.subscribe((v) => (openState = v));
      unsub();

      if (openState && currentWidth < previousWidthRef.current && currentWidth < 768) {
        navigationOpen.set(null);
      } else if (openState === null && currentWidth > 768) {
        navigationOpen.set(true);
      }
      previousWidthRef.current = currentWidth;
    };

    const handleKeydown = (e: KeyboardEvent) => {
      const isMac = window.navigator.userAgent.includes("Macintosh");
      const key = isMac ? "metaKey" : "ctrlKey";
      if (e[key] && e.key === "b") {
        e.preventDefault();
        navigationOpen.toggle();
      }
    };

    window.addEventListener("resize", handleResize);
    window.addEventListener("keydown", handleKeydown);
    return () => {
      window.removeEventListener("resize", handleResize);
      window.removeEventListener("keydown", handleKeydown);
    };
  }, []);

  const connectorSectionHeight = navWrapperHeight * connectorHeightPercentage;
  const isOpen = open !== false;

  function handleConnectorToggle() {
    const wasOpen = showConnectors;
    if (!wasOpen) setShowConnectors(true);
    const from = wasOpen ? connectorSectionHeight : 0;
    const to = wasOpen ? 0 : connectorSectionHeight;
    if (connectorWrapperRef.current) {
      const anim = connectorWrapperRef.current.animate(
        [
          { height: `${from}px` },
          { height: `${to}px` },
        ],
        { duration: 200, easing: "ease-out" },
      );
      anim.onfinish = () => {
        if (wasOpen) setShowConnectors(false);
      };
    }
  }

  return (
    <>
      <nav
        className={`sidebar bg-surface-base flex flex-col flex-none relative overflow-hidden h-full border-r z-0 select-none transition-[width] ${resizing ? "" : "duration-300 ease-in-out"} ${isOpen ? "" : "hide"}`}
        style={{ width: isOpen ? `${width}px` : "0px" }}
      >
        <Resizer
          min={MIN_NAV_WIDTH}
          basis={DEFAULT_NAV_WIDTH}
          max={MAX_NAV_WIDTH}
          dimension={width}
          side="right"
          resizing={resizing}
          onUpdate={(w) => setWidth(w)}
        />
        <div className="inner h-full overflow-hidden flex flex-col" style={{ width: `${width}px` }}>
          {addAsset ? (
            <div className="p-2 w-full pr-10">{addAsset}</div>
          ) : null}
          <div className="scroll-container overflow-y-auto overflow-x-hidden h-full">
            <div className="nav-wrapper flex flex-col size-full" ref={navWrapperRef}>
              <section className="size-full overflow-y-auto pb-4">{fileExplorer}</section>

              {navWrapperHeight > 0 ? (
                <section className="connector-section flex flex-col flex-none h-fit border-t relative">
                  {showConnectors ? (
                    <Resizer
                      dimension={connectorSectionHeight}
                      onUpdate={(height) =>
                        setConnectorHeightPercentage(height / navWrapperHeight)
                      }
                      direction="NS"
                      side="top"
                      min={0}
                      basis={navWrapperHeight * DEFAULT_PERCENTAGE}
                      max={navWrapperHeight * 0.9}
                      resizing={resizingConnector}
                    />
                  ) : null}

                  <button
                    type="button"
                    onClick={handleConnectorToggle}
                    className="flex gap-x-1 items-center w-full pl-2 pr-3.5 py-1.5 cursor-pointer text-fg-secondary"
                  >
                    <CaretDownIcon
                      size="14px"
                      className={`text-fg-secondary transition-transform ${showConnectors ? "" : "-rotate-90"}`}
                    />
                    <h3 className="font-semibold text-[10px] uppercase text-fg-muted">
                      {dataExplorerTitle ?? m.nav_data_explorer()}
                    </h3>
                  </button>

                  <div
                    className="connector-wrapper overflow-y-auto"
                    role="region"
                    aria-label={dataExplorerTitle ?? m.nav_data_explorer()}
                    ref={connectorWrapperRef}
                    style={{ height: `${showConnectors ? connectorSectionHeight : 0}px` }}
                  >
                    {showConnectors ? connectorExplorer : null}
                  </div>
                </section>
              ) : null}
            </div>
          </div>
          {showFooterLinks ? footer ?? <Footer /> : null}
        </div>
      </nav>

      <SurfaceControlButton
        resizing={resizing}
        navWidth={width}
        navOpen={isOpen}
        onClick={() => navigationOpen.toggle()}
      />
    </>
  );
}
