// web-common/src/layout/react/Footer.tsx
// React translation of `layout/navigation/Footer.svelte`. The runtime-bound
// bindings are lifted out as props so the component is self-contained and
// unit-testable: `version`/`commitHash` come from the local-service metadata
// query in the Svelte original (`createLocalServiceGetMetadata`); `starButton`
// and `trafficLights` are the GitHub-star and RuntimeTrafficLights features.
import type { ReactNode } from "react";
import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
import {
  Tooltip,
  Shortcut,
} from "@statsparrot/web-common/features/dashboards/leaderboard/react/primitives";
import { GithubIcon, InfoCircleIcon } from "./icons";

export interface FooterProps {
  version?: string | null;
  commitHash?: string | null;
  starButton?: ReactNode;
  trafficLights?: ReactNode;
}

const lineItems = [
  {
    label: m.footer_report_issue(),
    href: "https://github.com/staticlabs/statsparrot/issues/new?assignees=&labels=bug&template=bug_report.md&title=",
  },
];

export default function Footer({
  version,
  commitHash,
  starButton,
  trafficLights,
}: FooterProps) {
  return (
    <div className="flex flex-col pt-3 pb-3 gap-y-1 bg-surface-subtle border-t sticky bottom-0">
      {lineItems.map((lineItem, i) => (
        <a
          key={i}
          href={lineItem.href}
          target="_blank"
          rel="noreferrer noopener"
        >
          <div className="flex flex-row items-center px-4 py-1 gap-x-2 text-fg-secondary font-normal hover:bg-popover-accent">
            <div className="grid place-content-center" style={{ width: "16px", height: "16px" }}>
              <GithubIcon size="14px" className="fill-fg-secondary" />
            </div>
            {lineItem.label}
          </div>
        </a>
      ))}
      {starButton}
      <div
        className="px-4 py-1 text-fg-secondary flex items-center flex-row w-full gap-x-2 truncate line-clamp-1"
        style={{ fontSize: "10px" }}
      >
        <span>
          <Tooltip
            alignment="start"
            distance={16}
            location="top"
            content={
              <div className="rounded p-2 bg-popover text-popover-foreground shadow-lg">
                <div className="font-medium">{m.footer_statsparrot_developer()}</div>
                <div className="flex flex-row items-center gap-x-2">
                  <span>{m.footer_view_documentation()}</span>
                  <Shortcut>{m.footer_shortcut_click()}</Shortcut>
                </div>
              </div>
            }
          >
            <a
              href="https://docs.statsparrot.com"
              target="_blank"
              rel="noreferrer noopener"
              className="text-fg-secondary"
            >
              <InfoCircleIcon size="16px" />
            </a>
          </Tooltip>
        </span>

        <span className="truncate">
          {m.footer_version()} {version ?? m.footer_unknown_version()}
          {commitHash ? ` – ${commitHash}` : ""}
        </span>
        {trafficLights}
      </div>
    </div>
  );
}

// web-common/src/layout/navigation/Footer.svelte
<script lang="ts">
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
  import Github from "@statsparrot/web-common/components/icons/Github.svelte";
  import InfoCircle from "@statsparrot/web-common/components/icons/InfoCircle.svelte";
  import Shortcut from "@statsparrot/web-common/components/tooltip/Shortcut.svelte";
  import Tooltip from "@statsparrot/web-common/components/tooltip/Tooltip.svelte";
  import TooltipContent from "@statsparrot/web-common/components/tooltip/TooltipContent.svelte";
  import TooltipShortcutContainer from "@statsparrot/web-common/components/tooltip/TooltipShortcutContainer.svelte";
  import TooltipTitle from "@statsparrot/web-common/components/tooltip/TooltipTitle.svelte";
  import { fly } from "svelte/transition";
  import { createLocalServiceGetMetadata } from "@statsparrot/web-common/runtime-client/local-service";
  import RuntimeTrafficLights from "@statsparrot/web-common/features/entity-management/RuntimeTrafficLights.svelte";
  import GithubStarButton from "@statsparrot/web-common/features/github-star/GithubStarButton.svelte";

  const metadataQuery = createLocalServiceGetMetadata();

  $: version = $metadataQuery?.data?.version ?? null;
  $: commitHash = $metadataQuery?.data?.buildCommit ?? null;

  const lineItems = [
    {
      icon: Github,
      label: m.footer_report_issue(),
      href: "https://github.com/staticlabs/statsparrot/issues/new?assignees=&labels=bug&template=bug_report.md&title=",
      className: "fill-fg-secondary",
      shrinkIcon: true,
    },
  ];
</script>

<div
  class="flex flex-col pt-3 pb-3 gap-y-1 bg-surface-subtle border-t sticky bottom-0"
>
  {#each lineItems as lineItem, i (i)}
    <a href={lineItem.href} target="_blank" rel="noreferrer noopener"
      ><div
        class="flex flex-row items-center px-4 py-1 gap-x-2 text-fg-secondary font-normal hover:bg-popover-accent"
      >
        <!-- workaround to resize the github and discord icons to match -->
        <div
          class="grid place-content-center"
          style:width="16px"
          style:height="16px"
        >
          <svelte:component
            this={lineItem.icon}
            className={lineItem.className}
            size="14px"
          />
        </div>
        {lineItem.label}
      </div></a
    >
  {/each}
  <GithubStarButton />
  <div
    class="px-4 py-1 text-fg-secondary flex items-center flex-row w-full gap-x-2 truncate line-clamp-1"
    style:font-size="10px"
  >
    <span>
      <Tooltip alignment="start" distance={16} location="top">
        <a
          href="https://docs.statsparrot.com"
          target="_blank"
          rel="noreferrer noopener"
          class="text-fg-secondary"
        >
          <InfoCircle size="16px" />
        </a>
        <div
          slot="tooltip-content"
          transition:fly|global={{ duration: 100, y: 8 }}
        >
          <TooltipContent>
            <TooltipTitle>
              <svelte:fragment slot="name"
                >{m.footer_statsparrot_developer()}</svelte:fragment
              >
            </TooltipTitle>
            <TooltipShortcutContainer>
              <div>{m.footer_view_documentation()}</div>
              <Shortcut>{m.footer_shortcut_click()}</Shortcut>
            </TooltipShortcutContainer>
          </TooltipContent>
        </div>
      </Tooltip>
    </span>

    <span class="truncate">
      {m.footer_version()}
      {version || m.footer_unknown_version()}{commitHash
        ? ` – ${commitHash}`
        : ""}
    </span>
    <RuntimeTrafficLights />
  </div>
</div>
