// web-common/src/features/dashboards/filters/FilterChipsReadOnly.svelte
<!-- @component
The main feature-set component for dashboard filters
 -->
<script lang="ts">
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
  import TimeRangeReadOnly from "@statsparrot/web-common/features/dashboards/filters/TimeRangeReadOnly.svelte";
  import type { DimensionThresholdFilter } from "@statsparrot/web-common/features/dashboards/stores/explore-state";
  import { getMapFromArray } from "@statsparrot/web-common/lib/arrayUtils";
  import type {
    MetricsViewSpecDimension,
    MetricsViewSpecMeasure,
    V1Expression,
    V1TimeRange,
  } from "@statsparrot/web-common/runtime-client";
  import { flip } from "svelte/animate";
  import { getDimensionFilters } from "../state-managers/selectors/dimension-filters";
  import { getMeasureFilters } from "../state-managers/selectors/measure-filters";
  import DimensionFilterReadOnlyChip from "./dimension-filters/DimensionFilterReadOnlyChip.svelte";
  import MeasureFilterReadOnlyChip from "./measure-filters/MeasureFilterReadOnlyChip.svelte";

  export let metricsViewNames: string[];
  export let dimensions: MetricsViewSpecDimension[];
  export let measures: MetricsViewSpecMeasure[];
  export let filters: V1Expression | undefined;
  export let dimensionsWithInlistFilter: string[];
  export let dimensionThresholdFilters: DimensionThresholdFilter[];
  export let displayTimeRange: V1TimeRange | undefined;
  export let displayComparisonTimeRange: V1TimeRange | undefined = undefined;
  // `displayTimeRange` passed to this is usually a relative time range used just for display.
  // But we need resolved start and end based on current time in dimension filters to get query for accurate results.
  export let queryTimeStart: string | undefined = undefined;
  export let queryTimeEnd: string | undefined = undefined;
  export let hasBoldTimeRange: boolean = true;
  export let chipLayout: "wrap" | "scroll" = "wrap";

  let scrollContainer: HTMLDivElement;

  $: dimensionIdMap = getMapFromArray(
    dimensions,
    (dimension) => dimension.name as string,
  );
  $: dimensionFilters = getDimensionFilters(
    dimensionIdMap,
    filters,
    dimensionsWithInlistFilter,
    metricsViewNames[0],
  );

  $: measureIdMap = getMapFromArray(
    measures,
    (measure) => measure.name as string,
  );
  $: measureFilters = getMeasureFilters(
    measureIdMap,
    dimensionThresholdFilters,
  );

  function handleWheel(event: WheelEvent) {
    if (chipLayout === "scroll" && event.deltaY !== 0) {
      scrollContainer.scrollLeft += event.deltaY;
      event.preventDefault();
    }
  }
</script>

<div
  class="relative flex flex-row items-center gap-x-2 gap-y-2 w-full max-w-full"
  class:scrollable-chips={chipLayout === "scroll"}
  class:flex-wrap={chipLayout === "wrap"}
  aria-label={m.dashboard_readonly_filter_chips_aria()}
  bind:this={scrollContainer}
  onwheel={handleWheel}
>
  {#if displayTimeRange}
    <TimeRangeReadOnly
      timeRange={displayTimeRange}
      comparisonTimeRange={displayComparisonTimeRange}
      {hasBoldTimeRange}
    />
  {/if}
  {#if dimensionFilters.length > 0}
    {#each dimensionFilters as filterData (filterData.name)}
      {@const dimension = filterData.dimensions.get(metricsViewNames[0])}
      <!-- <div animate:flip={{ duration: 200 }}> -->
      {#if dimension}
        <DimensionFilterReadOnlyChip
          pinned={filterData.pinned}
          name={filterData.name}
          {metricsViewNames}
          label={dimension.displayName ||
            dimension.name ||
            dimension.column ||
            "Unnamed Dimension"}
          mode={filterData.mode}
          values={filterData.selectedValues ?? []}
          inputText={filterData.inputText}
          isInclude={filterData.isInclude === true}
          timeStart={queryTimeStart}
          timeEnd={queryTimeEnd}
        />
      {/if}
      <!-- </div> -->
    {/each}
  {/if}
  {#if measureFilters.length > 0}
    {#each measureFilters as { name, label, dimensionName, filter } (name)}
      <div animate:flip={{ duration: 200 }}>
        <MeasureFilterReadOnlyChip
          label={label || name}
          {dimensionName}
          {filter}
        />
      </div>
    {/each}
  {/if}
</div>

<style lang="postcss">
  .scrollable-chips {
    @apply overflow-x-auto whitespace-nowrap;
    @apply overscroll-x-contain pr-2;
    scrollbar-width: none;
    -ms-overflow-style: none;
  }
  .scrollable-chips::-webkit-scrollbar {
    @apply hidden;
  }
</style>

// web-common/src/features/dashboards/filters/react/FilterChipsReadOnly.tsx
import { useMemo } from "react";
import type {
  MetricsViewSpecDimension,
  MetricsViewSpecMeasure,
  V1Expression,
  V1TimeRange,
} from "@statsparrot/web-common/runtime-client";
import type { DimensionThresholdFilter } from "@statsparrot/web-common/features/dashboards/stores/explore-state";
import { getMapFromArray } from "@statsparrot/web-common/lib/arrayUtils";
import { getRangeLabel } from "@statsparrot/web-common/features/dashboards/time-controls/new-time-controls";
import { getComparisonLabel } from "@statsparrot/web-common/lib/time/comparisons";
import { getDimensionFilters } from "@statsparrot/web-common/features/dashboards/state-managers/selectors/dimension-filters";
import { getMeasureFilters } from "@statsparrot/web-common/features/dashboards/state-managers/selectors/measure-filters";
import { DimensionFilterMode } from "@statsparrot/web-common/features/dashboards/filters/dimension-filters/constants";

const chipBase =
  "inline-flex items-center gap-x-1.5 h-7 px-2.5 rounded-full border border-border " +
  "bg-bg-secondary text-xs text-fg-primary whitespace-nowrap";

export interface FilterChipsReadOnlyProps {
  metricsViewNames: string[];
  dimensions: MetricsViewSpecDimension[];
  measures: MetricsViewSpecMeasure[];
  filters: V1Expression | undefined;
  dimensionsWithInlistFilter: string[];
  dimensionThresholdFilters: DimensionThresholdFilter[];
  displayTimeRange: V1TimeRange | undefined;
  displayComparisonTimeRange?: V1TimeRange | undefined;
  queryTimeStart?: string | undefined;
  queryTimeEnd?: string | undefined;
  hasBoldTimeRange?: boolean;
  chipLayout?: "wrap" | "scroll";
}

/**
 * React translation of `FilterChipsReadOnly.svelte`. Renders the read-only chip strip
 * used on chart headers: time range + dimension chips + measure chips.
 *
 * Read-only by design (display only). The interactive dimension/measure dropdowns and
 * the `panel/filter-bar` mutations are a later increment; here we render the active
 * filters from the given expression and threshold state.
 */
export default function FilterChipsReadOnly({
  metricsViewNames,
  dimensions,
  measures,
  filters,
  dimensionsWithInlistFilter,
  dimensionThresholdFilters,
  displayTimeRange,
  displayComparisonTimeRange,
  hasBoldTimeRange = false,
  chipLayout = "wrap",
}: FilterChipsReadOnlyProps) {
  const dimensionIdMap = useMemo(
    () => getMapFromArray(dimensions, (d) => d.name as string),
    [dimensions],
  );
  const dimensionFilters = useMemo(
    () =>
      getDimensionFilters(
        dimensionIdMap,
        filters,
        dimensionsWithInlistFilter,
        metricsViewNames[0],
      ),
    [dimensionIdMap, filters, dimensionsWithInlistFilter, metricsViewNames],
  );

  const measureIdMap = useMemo(
    () => getMapFromArray(measures, (m) => m.name as string),
    [measures],
  );
  const measureFilters = useMemo(
    () => getMeasureFilters(measureIdMap, dimensionThresholdFilters),
    [measureIdMap, dimensionThresholdFilters],
  );

  return (
    <div
      className={`relative flex flex-row items-center gap-x-2 gap-y-2 w-full max-w-full ${
        chipLayout === "scroll"
          ? "overflow-x-auto whitespace-nowrap overscroll-x-contain pr-2 scrollbar-none"
          : "flex-wrap"
      }`}
      aria-label="Read only filter chips"
    >
      {displayTimeRange ? (
        <TimeRangeReadOnly
          timeRange={displayTimeRange}
          comparisonTimeRange={displayComparisonTimeRange}
          hasBoldTimeRange={hasBoldTimeRange}
        />
      ) : null}

      {dimensionFilters.map((filterData) => {
        const dimension = filterData.dimensions.get(metricsViewNames[0]);
        if (!dimension) return null;
        const label =
          dimension.displayName ||
          dimension.name ||
          dimension.column ||
          "Unnamed Dimension";
        const values = filterData.selectedValues ?? [];
        const mode =
          filterData.mode === DimensionFilterMode.Contains
            ? `~${filterData.inputText ?? ""}`
            : values.join(", ");
        return (
          <span key={filterData.name} className={chipBase}>
            <span className="text-fg-secondary">{label}:</span>
            {filterData.isInclude === false ? <span className="text-fg-secondary">not</span> : null}
            <span className="max-w-[18rem] truncate">
              {mode || (filterData.isInclude === false ? "" : "…")}
            </span>
          </span>
        );
      })}

      {measureFilters.map(({ name, label, dimensionName }) => (
        <span key={name} className={chipBase}>
          <span className="text-fg-secondary">{label || name}</span>
          {dimensionName ? (
            <span className="text-fg-secondary">
              by {dimensionName}
            </span>
          ) : null}
        </span>
      ))}
    </div>
  );
}

/** React translation of `TimeRangeReadOnly.svelte` (chip + comparison chip). */
export function TimeRangeReadOnly({
  timeRange,
  comparisonTimeRange,
  hasBoldTimeRange = false,
}: {
  timeRange: V1TimeRange;
  comparisonTimeRange?: V1TimeRange | undefined;
  hasBoldTimeRange?: boolean;
}) {
  const selectedLabel = getRangeLabel(timeRange.isoDuration ?? timeRange.expression);
  const showRange =
    selectedLabel === "Custom" ||
    selectedLabel?.startsWith("-") ||
    !isNaN(Number(selectedLabel?.[0]));

  return (
    <span className={chipBase}>
      <span className="font-bold">{showRange ? "Custom" : selectedLabel}</span>
      {comparisonTimeRange ? (
        <span className="text-fg-secondary">
          vs{" "}
          <span className={hasBoldTimeRange ? "font-bold" : ""}>
            {getComparisonLabel(comparisonTimeRange)}
          </span>
        </span>
      ) : null}
    </span>
  );
}
