// web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/react/RangePickerV2.tsx
import { useEffect, useRef, useState } from "react";
import { DateTime, Duration, Interval } from "luxon";
import type {
  ISODurationString,
  NamedRange,
  RangeBuckets,
} from "@statsparrot/web-common/features/dashboards/time-controls/new-time-controls";
import {
  ALL_TIME_RANGE_ALIAS,
  constructAsOfString,
  constructNewString,
  getRangeLabel,
  STATSPARROT_TO_LABEL,
} from "@statsparrot/web-common/features/dashboards/time-controls/new-time-controls";
import { V1TimeGrain } from "@statsparrot/web-common/runtime-client";
import {
  overrideParrotTimeRef,
  parseParrotTime,
} from "@statsparrot/web-common/features/dashboards/url-state/time-ranges/parser";
import {
  ParrotAllTimeInterval,
  ParrotIsoInterval,
  ParrotPeriodToGrainInterval,
  ParrotTimeLabel,
  type ParrotTime,
} from "@statsparrot/web-common/features/dashboards/url-state/time-ranges/ParrotTime";
import {
  getGrainOrder,
  V1TimeGrainToDateTimeUnit,
} from "@statsparrot/web-common/lib/time/new-grains";
import { getTruncationGrain } from "@statsparrot/web-common/lib/time/statsparrot-time-grains";
import { getAbbreviationForIANA } from "@statsparrot/web-common/lib/time/timezone";
import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
import { CaretDownIcon, CalendarIcon, GlobeIcon, CheckIcon } from "./icons";
import { RangeDisplay } from "./RangeDisplay";
import { SyntaxElement } from "./SyntaxElement";
import { TimeRangeSearch } from "./TimeRangeSearch";
import { TimeRangeOptionGroup } from "./TimeRangeOptionGroup";
import { ZoneContent } from "./ZoneContent";
import { CalendarPlusDateInput } from "./CalendarPlusDateInput";
import { TruncationSelector } from "./TruncationSelector";
import { PrimaryRangeTooltip } from "./PrimaryRangeTooltip";

/**
 * React translation of `super-pill/new-time-dropdown/RangePickerV2.svelte`: the SuperPill
 * time-range picker. Renders the trigger chip, the search/list dropdown, the custom date
 * picker, the time-zone picker, the time-axis picker, and the truncation selector.
 *
 * Reuses the framework-agnostic `new-time-controls` utilities, the Parrot time range
 * parser/ParrotTime model, and the grain helpers verbatim. Popover / Tooltip / DropdownMenu
 * Svelte primitives are replaced by React stand-ins.
 */
export interface RangePickerV2Props {
  timeString: string | undefined;
  interval: Interval<true> | undefined;
  timeGrain: V1TimeGrain | undefined;
  zone: string;
  showDefaultItem: boolean;
  context: string;
  minDate: DateTime<true> | undefined;
  maxDate: DateTime<true> | undefined;
  rangeBuckets: RangeBuckets;
  watermark: DateTime | undefined;
  smallestTimeGrain: V1TimeGrain | undefined;
  defaultTimeRange: NamedRange | ISODurationString | undefined;
  allowCustomTimeRange?: boolean;
  maxQueryTimeRange?: Duration | undefined;
  availableTimeZones: string[];
  lockTimeZone?: boolean;
  showFullRange?: boolean;
  timeDimensions: { value: string; label: string; description?: string }[];
  primaryTimeDimension: string | undefined;
  selectedTimeDimension: string | undefined;
  onTimeDimensionSelect?: ((dimension: string) => void) | undefined;
  onSelectTimeZone: (timeZone: string) => void;
  onSelectRange: (range: string) => void;
}

export default function RangePickerV2({
  timeString,
  interval,
  timeGrain,
  zone,
  showDefaultItem,
  context,
  minDate,
  maxDate,
  rangeBuckets,
  watermark,
  smallestTimeGrain,
  defaultTimeRange,
  allowCustomTimeRange = true,
  maxQueryTimeRange = undefined,
  availableTimeZones,
  lockTimeZone = false,
  showFullRange = true,
  timeDimensions,
  primaryTimeDimension,
  selectedTimeDimension,
  onTimeDimensionSelect = undefined,
  onSelectTimeZone,
  onSelectRange,
}: RangePickerV2Props) {
  const [open, setOpen] = useState(false);
  const [filter] = useState("");
  const [searchValue, setSearchValue] = useState<string | undefined>(timeString);
  const [showCalendarPicker, setShowCalendarPicker] = useState(false);
  const [timeZonePickerOpen, setTimeZonePickerOpen] = useState(false);
  const [timeAxisPickerOpen, setTimeAxisPickerOpen] = useState(false);
  const [flexTruncationGrain, setFlexTruncationGrain] = useState<
    V1TimeGrain | undefined
  >();

  const containerRef = useRef<HTMLDivElement>(null);
  const [tooltipOpen, setTooltipOpen] = useState(false);

  // Open/close on the Cmd/Ctrl+K shortcut (Svelte `svelte:window` keydown).
  useEffect(() => {
    function onKeyDown(e: KeyboardEvent) {
      if (e.metaKey && e.key === "k") {
        setOpen((o) => !o);
      }
    }
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  // Reset the search box to the current time string whenever the picker opens
  // (Svelte `onOpenChange` sets `searchValue = timeString` on open).
  useEffect(() => {
    if (open) setSearchValue(timeString);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Close the dropdown on outside click / Escape.
  useEffect(() => {
    if (!open) return;
    function onPointerDown(event: MouseEvent) {
      if (
        containerRef.current &&
        !containerRef.current.contains(event.target as Node)
      ) {
        setOpen(false);
      }
    }
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") setOpen(false);
    }
    document.addEventListener("mousedown", onPointerDown);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("mousedown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [open]);

  const allTimeAllowed = !(
    maxQueryTimeRange && maxQueryTimeRange.as("milliseconds") > 0
  );

  let parsedTime: ParrotTime | undefined = undefined;
  if (timeString) {
    try {
      parsedTime = parseParrotTime(timeString);
    } catch {
      parsedTime = undefined;
    }
  }

  const hideTruncationSelector =
    parsedTime?.interval instanceof ParrotIsoInterval ||
    parsedTime?.interval instanceof ParrotAllTimeInterval;

  const usingLegacyTime = parsedTime?.isOldFormat;
  const hasAsOfClause = !!parsedTime?.asOfLabel;

  const snapToEnd = usingLegacyTime ? true : !!parsedTime?.asOfLabel?.offset;
  const ref = usingLegacyTime ? ParrotTimeLabel.Latest : parsedTime?.asOfLabel?.label;

  const baseTruncationGrain = getTruncationGrain(parsedTime);
  const truncationGrain = flexTruncationGrain ?? baseTruncationGrain;

  const dateTimeAnchor = returnAnchor(ref, zone, maxDate, watermark);

  const selectedLabel = getRangeLabel(timeString);

  const activeTimeDimension = timeDimensions.find(
    ({ value }) => value === (selectedTimeDimension || primaryTimeDimension),
  );

  const zoneAbbreviation = getAbbreviationForIANA(maxDate ?? DateTime.now(), zone);
  const smallestTimeGrainOrder = getGrainOrder(
    smallestTimeGrain || V1TimeGrain.TIME_GRAIN_MINUTE,
  );

  function handleRangeSelect(range: string, ignoreSnap?: boolean) {
    try {
      const parsed = parseParrotTime(range);

      const isPeriodToDate = parsed.interval instanceof ParrotPeriodToGrainInterval;

      const rangeGrainOrder =
        getGrainOrder(parsed.rangeGrain) - (isPeriodToDate ? 1 : 0);

      let activeTruncationGrain = flexTruncationGrain ?? baseTruncationGrain;
      const asOfGrainOrder = getGrainOrder(activeTruncationGrain);

      const shouldAppendAsOfString =
        !parsed.asOfLabel && !(parsed.interval instanceof ParrotIsoInterval);

      if (asOfGrainOrder > rangeGrainOrder && parsed.rangeGrain) {
        activeTruncationGrain = parsed.rangeGrain;
        setFlexTruncationGrain(parsed.rangeGrain);
      }

      if (shouldAppendAsOfString) {
        const isTruncationGrainAllowed =
          getGrainOrder(activeTruncationGrain) >= smallestTimeGrainOrder;
        const newAsOfString = constructAsOfString(
          ref ?? ParrotTimeLabel.Latest,
          ignoreSnap
            ? undefined
            : activeTruncationGrain
              ? isTruncationGrainAllowed
                ? activeTruncationGrain
                : parsed.rangeGrain
              : smallestTimeGrain ?? V1TimeGrain.TIME_GRAIN_MINUTE,
          hasAsOfClause || snapToEnd ? snapToEnd : true,
        );

        overrideParrotTimeRef(parsed, newAsOfString);
      }

      onSelectRange(parsed.toString());
      closeMenu();
    } catch {
      // This function is called in a controlled manner and should not throw
    }
  }

  function onSelectGrain(grain: V1TimeGrain | undefined) {
    if (!timeString) return;

    const newString = constructNewString({
      currentString: timeString,
      truncationGrain: grain === truncationGrain ? undefined : grain,
      snapToEnd: grain === truncationGrain ? false : snapToEnd,
      ref,
    });

    onSelectRange(newString);
  }

  function onSelectAsOfOption(
    asOfRef: ParrotTimeLabel | string | undefined,
    inclusive: boolean,
  ) {
    if (!timeString) return;
    const newString = constructNewString({
      currentString: timeString,
      truncationGrain,
      snapToEnd: asOfRef === "watermark" ? false : inclusive,
      ref: asOfRef,
    });

    onSelectRange(newString);
  }

  function closeMenu() {
    setOpen(false);
  }

  const selectedLabelIsCustom =
    selectedLabel?.startsWith("-") || !isNaN(Number(selectedLabel?.[0]));

  return (
    <div className="relative flex" ref={containerRef}>
      {/* Trigger + tooltip */}
      <span
        className="relative"
        onMouseEnter={() => setTooltipOpen(true)}
        onMouseLeave={() => setTooltipOpen(false)}
      >
        <button
          className="flex gap-x-1.5"
          aria-label={m.dashboard_select_time_range()}
          type="button"
          onClick={() => setOpen((o) => !o)}
        >
          {timeString ? (
            <b className="line-clamp-1 flex-none">
              {selectedLabelIsCustom ? m.dashboard_custom() : selectedLabel}
            </b>
          ) : null}

          {showFullRange ? (
            <>
              <RangeDisplay interval={interval} timeGrain={timeGrain} />

              <div className="font-bold bg-surface-muted rounded-[2px] p-1 py-0 text-fg-secondary text-[11px]">
                {zoneAbbreviation}
              </div>
            </>
          ) : null}

          <span
            className={`flex-none transition-transform ${open ? "-rotate-180" : ""}`}
          >
            <CaretDownIcon />
          </span>
        </button>

        {tooltipOpen && !open && interval ? (
          <div className="absolute z-50 top-full mt-2">
            <PrimaryRangeTooltip
              timeString={timeString}
              interval={interval}
              timeDimensionLabel={activeTimeDimension?.label}
              timeDimensionDescription={activeTimeDimension?.description}
            />
          </div>
        ) : null}
      </span>

      {/* Dropdown content */}
      {open ? (
        <div
          className="absolute top-full left-0 z-50 p-0 w-fit overflow-hidden flex flex-col"
          style={{ marginTop: "0.25rem" }}
        >
          <TimeRangeSearch
            inError={!parsedTime && !!timeString && !usingLegacyTime}
            width={showCalendarPicker ? 456 : 224}
            context={context}
            timeString={timeString}
            searchValue={searchValue ?? ""}
            onSearchValueChange={(v) => {
              setSearchValue(v);
            }}
            onSelectRange={(range) => {
              setOpen(false);
              handleRangeSelect(range);
            }}
          />

          <div
            className={`flex w-56 max-h-fit ${
              showCalendarPicker ? "!w-[456px]" : ""
            }`}
            style={{ height: "470px" }}
          >
            <div className="flex flex-col w-56 overflow-y-auto overflow-x-hidden flex-none py-1">
              <div className="overflow-x-hidden">
                {showDefaultItem && defaultTimeRange ? (
                  <TimeRangeOptionGroup
                    filter={filter}
                    timeString={timeString}
                    options={[parseParrotTime(defaultTimeRange)]}
                    onClick={handleRangeSelect}
                  />
                ) : null}

                <TimeRangeOptionGroup
                  filter={filter}
                  timeString={timeString}
                  options={rangeBuckets.custom}
                  onClick={handleRangeSelect}
                />

                <TimeRangeOptionGroup
                  filter={filter}
                  timeString={timeString}
                  options={rangeBuckets.latest}
                  onClick={handleRangeSelect}
                />

                <TimeRangeOptionGroup
                  filter={filter}
                  timeString={timeString}
                  options={rangeBuckets.periodToDate}
                  onClick={handleRangeSelect}
                />

                <TimeRangeOptionGroup
                  filter={filter}
                  timeString={timeString}
                  options={rangeBuckets.previous}
                  onClick={(r) => handleRangeSelect(r, true)}
                />

                {allTimeAllowed ? (
                  <div className="w-full h-fit px-1">
                    <button
                      type="button"
                      role="menuitem"
                      className="group truncate h-7 p-2 text-popover-foreground justify-between overflow-hidden hover:bg-popover-accent rounded-sm w-full select-none flex items-center"
                      onClick={() => handleRangeSelect("inf")}
                    >
                      <span className={timeString === ALL_TIME_RANGE_ALIAS ? "font-bold" : ""}>
                        {STATSPARROT_TO_LABEL[ALL_TIME_RANGE_ALIAS]}
                      </span>
                    </button>
                  </div>
                ) : null}
              </div>

              {allowCustomTimeRange ? (
                <div className="w-full h-fit px-1">
                  <div className="h-px w-full bg-border my-1"></div>
                  <button
                    type="button"
                    role="menuitem"
                    onClick={() => setShowCalendarPicker((s) => !s)}
                    className="truncate text-fg-primary w-full text-left gap-x-1 pr-1 hover:bg-popover-accent flex items-center flex-shrink pl-2 h-7 rounded-sm"
                  >
                    <CalendarIcon size="14px" />
                    <div className="mr-auto">{m.dashboard_custom()}</div>

                    <CaretDownIcon className="-rotate-90 text-fg-secondary" size="14px" />
                  </button>
                </div>
              ) : null}

              {!lockTimeZone ? (
                <div className="w-full h-fit px-1">
                  <div className="h-px w-full bg-border my-1"></div>

                  <div className="relative">
                    <button
                      type="button"
                      onClick={() => {
                        setShowCalendarPicker(false);
                        setTimeZonePickerOpen((o) => !o);
                      }}
                      className="group h-7 overflow-hidden hover:bg-popover-accent flex-none rounded-sm w-full select-none flex items-center truncate text-left gap-x-1 pr-1 pl-2"
                    >
                      <div className="flex-none">
                        <GlobeIcon size="14px" className="text-fg-primary" />
                      </div>
                      <div className="mr-auto text-fg-primary">{m.dashboard_time_zone()}</div>
                      <div className="sr-only group-hover:not-sr-only">
                        <SyntaxElement range={zoneAbbreviation} />
                      </div>
                      <CaretDownIcon className="-rotate-90 text-fg-secondary" size="14px" />
                    </button>

                    {timeZonePickerOpen ? (
                      <div
                        className="absolute left-full top-0 ml-2 p-1 z-50 rounded-md border bg-popover shadow-md"
                        style={{ minWidth: 224 }}
                      >
                        <ZoneContent
                          context={context}
                          availableTimeZones={availableTimeZones}
                          activeTimeZone={zone}
                          referencePoint={dateTimeAnchor ?? interval?.end ?? DateTime.now()}
                          onSelectTimeZone={(z) => {
                            onSelectTimeZone(z);
                            closeMenu();
                            setTimeZonePickerOpen(false);
                          }}
                        />
                      </div>
                    ) : null}
                  </div>
                </div>
              ) : null}

              {timeDimensions.length > 1 && onTimeDimensionSelect ? (
                <div className="w-full h-fit px-1">
                  <div className="h-px w-full bg-border my-1"></div>

                  <div className="relative">
                    <button
                      type="button"
                      id={`time-axis-trigger-${context}`}
                      onClick={() => {
                        setShowCalendarPicker(false);
                        setTimeAxisPickerOpen((o) => !o);
                      }}
                      aria-label={m.dashboard_select_time_axis()}
                      className="group h-7 overflow-hidden hover:bg-surface-hover flex-none rounded-sm w-full select-none flex items-center truncate text-left gap-x-1 pr-1 pl-2"
                    >
                      <div className="flex-none">
                        <svg width="14px" height="14px" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                          <circle cx="12" cy="12" r="10" />
                          <polyline points="12 6 12 12 16 14" />
                        </svg>
                      </div>
                      <div className="mr-auto">{m.dashboard_time_axis()}</div>
                      {activeTimeDimension ? (
                        <div className="sr-only group-hover:not-sr-only">
                          <SyntaxElement range={activeTimeDimension.label} />
                        </div>
                      ) : null}
                      <CaretDownIcon className="-rotate-90" size="14px" />
                    </button>

                    {timeAxisPickerOpen ? (
                      <div
                        className="absolute left-full top-0 ml-2 p-1 z-50 rounded-md border bg-popover shadow-md"
                        style={{ minWidth: 224 }}
                      >
                        {timeDimensions.map(({ value, label, description }) => (
                          <div key={value}>
                            <button
                              type="button"
                              className="item w-full relative justify-between flex cursor-pointer select-none items-start rounded-sm py-1.5 px-2 gap-x-2 text-xs outline-none hover:bg-surface-hover text-fg-primary"
                              aria-label={m.dashboard_select_time_dimension({ label })}
                              onClick={() => {
                                onTimeDimensionSelect?.(value);
                                closeMenu();
                                setTimeAxisPickerOpen(false);
                              }}
                            >
                              {label}
                              {value === (selectedTimeDimension || primaryTimeDimension) ? (
                                <CheckIcon size={16} className="size-4 text-fg-primary" />
                              ) : null}
                            </button>
                            {description ? (
                              <p className="px-2 pb-1 text-[11px] text-fg-secondary">{description}</p>
                            ) : null}
                          </div>
                        ))}
                      </div>
                    ) : null}
                  </div>
                </div>
              ) : null}
            </div>

            {showCalendarPicker ? (
              <div className="bg-surface-overlay border-l p-3 size-full overflow-y-auto">
                <CalendarPlusDateInput
                  interval={interval}
                  zone={zone}
                  minTimeGrain={
                    V1TimeGrainToDateTimeUnit[smallestTimeGrain ?? V1TimeGrain.TIME_GRAIN_MINUTE]
                  }
                  minDate={minDate}
                  maxDate={maxDate}
                  maxQueryTimeRange={maxQueryTimeRange}
                  onApply={() => {
                    if (searchValue) handleRangeSelect(searchValue);
                  }}
                  updateRange={(string) => setSearchValue(string)}
                  closeMenu={() => setOpen(false)}
                />
              </div>
            ) : null}
          </div>
        </div>
      ) : null}

      {dateTimeAnchor && !hideTruncationSelector ? (
        // The truncation selector is positioned normally (flex sibling after the picker chip).
        <span className="pl-2">
          <TruncationSelector
            dateTimeAnchor={dateTimeAnchor}
            grain={truncationGrain}
            rangeGrain={parsedTime?.rangeGrain ?? truncationGrain}
            isPeriodToDate={parsedTime?.interval instanceof ParrotPeriodToGrainInterval}
            watermark={watermark}
            latest={maxDate}
            smallestTimeGrain={smallestTimeGrain}
            snapToEnd={snapToEnd}
            asOfRef={ref}
            zone={zone}
            onSelectEnding={onSelectGrain}
            onToggleAlignment={(inclusive) => onSelectAsOfOption(ref, inclusive)}
            onSelectAsOfOption={(o) => onSelectAsOfOption(o, snapToEnd)}
          />
        </span>
      ) : null}
    </div>
  );
}

// Zone is taken as a param to make it reactive
function returnAnchor(
  asOf: string | undefined,
  zone: string,
  maxDate: DateTime<true> | undefined,
  watermark: DateTime | undefined,
): DateTime | undefined {
  if (!maxDate) return DateTime.now().setZone(zone);
  if (asOf === "latest") {
    return maxDate.setZone(zone);
  } else if (asOf === "watermark" && watermark) {
    return watermark.setZone(zone);
  } else if (asOf === "now" || !asOf) {
    return DateTime.now().setZone(zone);
  }
  return undefined;
}

// web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/RangePickerV2.svelte
<script lang="ts">
  import CaretDownIcon from "@statsparrot/web-common/components/icons/CaretDownIcon.svelte";
  import { DateTime, Duration, Interval } from "luxon";
  import type {
    ISODurationString,
    NamedRange,
    RangeBuckets,
  } from "../../new-time-controls";
  import {
    ALL_TIME_RANGE_ALIAS,
    getRangeLabel,
    STATSPARROT_TO_LABEL,
  } from "../../new-time-controls";
  import CalendarPlusDateInput from "@statsparrot/web-common/features/dashboards/time-controls/super-pill/components/CalendarPlusDateInput.svelte";
  import { V1TimeGrain } from "@statsparrot/web-common/runtime-client";
  import TimeRangeSearch from "@statsparrot/web-common/features/dashboards/time-controls/super-pill/components/TimeRangeSearch.svelte";
  import { parseParrotTime } from "../../../url-state/time-ranges/parser";
  import {
    ParrotAllTimeInterval,
    ParrotIsoInterval,
    ParrotPeriodToGrainInterval,
    ParrotTimeLabel,
    type ParrotTime,
  } from "../../../url-state/time-ranges/ParrotTime";
  import {
    getGrainOrder,
    V1TimeGrainToDateTimeUnit,
  } from "@statsparrot/web-common/lib/time/new-grains";
  import { getTruncationGrain } from "@statsparrot/web-common/lib/time/statsparrot-time-grains";
  import * as Popover from "@statsparrot/web-common/components/popover";
  import TimeRangeOptionGroup from "./TimeRangeOptionGroup.svelte";
  import RangeDisplay from "../components/RangeDisplay.svelte";
  import TruncationSelector from "./TruncationSelector.svelte";
  import { overrideParrotTimeRef } from "../../../url-state/time-ranges/parser";
  import { getAbbreviationForIANA } from "@statsparrot/web-common/lib/time/timezone";
  import * as Tooltip from "@statsparrot/web-common/components/tooltip-v2";
  import ZoneContent from "../components/ZoneContent.svelte";
  import SyntaxElement from "../components/SyntaxElement.svelte";
  import Globe from "@statsparrot/web-common/components/icons/Globe.svelte";
  import Calendar from "@statsparrot/web-common/components/icons/Calendar.svelte";
  import {
    constructAsOfString,
    constructNewString,
  } from "../../new-time-controls";
  import PrimaryRangeTooltip from "./PrimaryRangeTooltip.svelte";
  import { Clock, Check } from "lucide-svelte";
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";

  export let timeString: string | undefined;
  export let interval: Interval<true> | undefined;
  export let timeGrain: V1TimeGrain | undefined;
  export let zone: string;
  export let showDefaultItem: boolean;
  export let context: string;
  export let minDate: DateTime<true> | undefined;
  export let maxDate: DateTime<true> | undefined;
  export let rangeBuckets: RangeBuckets;
  export let watermark: DateTime | undefined;
  export let smallestTimeGrain: V1TimeGrain | undefined;
  export let defaultTimeRange: NamedRange | ISODurationString | undefined;
  export let allowCustomTimeRange = true;
  export let maxQueryTimeRange: Duration | undefined = undefined;
  export let availableTimeZones: string[];
  export let lockTimeZone = false;
  export let showFullRange = true;
  export let timeDimensions: {
    value: string;
    label: string;
    description?: string;
  }[];
  export let primaryTimeDimension: string | undefined;
  export let selectedTimeDimension: string | undefined;
  export let onTimeDimensionSelect: ((dimension: string) => void) | undefined =
    undefined;
  export let onSelectTimeZone: (timeZone: string) => void;
  export let onSelectRange: (range: string) => void;

  let open = false;
  $: allTimeAllowed = !(
    maxQueryTimeRange && maxQueryTimeRange.as("milliseconds") > 0
  );
  let searchComponent: TimeRangeSearch;
  let filter = "";
  let parsedTime: ParrotTime | undefined = undefined;
  let showCalendarPicker = false;
  let timeZonePickerOpen = false;
  let timeAxisPickerOpen = false;
  let searchValue: string | undefined = timeString;

  $: if (timeString) {
    try {
      parsedTime = parseParrotTime(timeString);
    } catch {
      parsedTime = undefined;
    }
  }

  $: hideTruncationSelector =
    parsedTime?.interval instanceof ParrotIsoInterval ||
    parsedTime?.interval instanceof ParrotAllTimeInterval;

  $: usingLegacyTime = parsedTime?.isOldFormat;

  $: hasAsOfClause = !!parsedTime?.asOfLabel;

  $: snapToEnd = usingLegacyTime ? true : !!parsedTime?.asOfLabel?.offset;
  $: ref = usingLegacyTime
    ? ParrotTimeLabel.Latest
    : parsedTime?.asOfLabel?.label;

  $: truncationGrain = getTruncationGrain(parsedTime);

  $: dateTimeAnchor = returnAnchor(ref, zone);

  $: selectedLabel = getRangeLabel(timeString);

  // Resolve the active time axis to a defined time dimension, if any. When the
  // timeseries points at a raw column this is undefined and the tooltip omits
  // the dimension name and description.
  $: activeTimeDimension = timeDimensions.find(
    ({ value }) => value === (selectedTimeDimension || primaryTimeDimension),
  );

  $: zoneAbbreviation = getAbbreviationForIANA(maxDate ?? DateTime.now(), zone);

  $: smallestTimeGrainOrder = getGrainOrder(
    smallestTimeGrain || V1TimeGrain.TIME_GRAIN_MINUTE,
  );

  function handleRangeSelect(range: string, ignoreSnap?: boolean) {
    try {
      const parsed = parseParrotTime(range);

      const isPeriodToDate =
        parsed.interval instanceof ParrotPeriodToGrainInterval;

      const rangeGrainOrder =
        getGrainOrder(parsed.rangeGrain) - (isPeriodToDate ? 1 : 0);

      const asOfGrainOrder = getGrainOrder(truncationGrain);

      const shouldAppendAsOfString =
        !parsed.asOfLabel && !(parsed.interval instanceof ParrotIsoInterval);

      if (asOfGrainOrder > rangeGrainOrder && parsed.rangeGrain) {
        truncationGrain = parsed.rangeGrain;
      }

      if (shouldAppendAsOfString) {
        const isTruncationGrainAllowed =
          getGrainOrder(truncationGrain) >= smallestTimeGrainOrder;
        const newAsOfString = constructAsOfString(
          ref ?? ParrotTimeLabel.Latest,
          ignoreSnap
            ? undefined
            : truncationGrain
              ? isTruncationGrainAllowed
                ? truncationGrain
                : parsed.rangeGrain
              : (smallestTimeGrain ?? V1TimeGrain.TIME_GRAIN_MINUTE),
          hasAsOfClause || snapToEnd ? snapToEnd : true,
        );

        overrideParrotTimeRef(parsed, newAsOfString);
      }

      onSelectRange(parsed.toString());
      closeMenu();
    } catch {
      // This function is called in a controlled manner and should not throw
    }
  }

  function onSelectGrain(grain: V1TimeGrain | undefined) {
    if (!timeString) return;

    const newString = constructNewString({
      currentString: timeString,
      truncationGrain: grain === truncationGrain ? undefined : grain,
      snapToEnd: grain === truncationGrain ? false : snapToEnd,
      ref: ref,
    });

    onSelectRange(newString);
  }

  function onSelectAsOfOption(
    ref: ParrotTimeLabel | string | undefined,
    inclusive: boolean,
  ) {
    if (!timeString) return;
    const newString = constructNewString({
      currentString: timeString,
      truncationGrain: truncationGrain,
      snapToEnd: ref === "watermark" ? false : inclusive,
      ref,
    });

    onSelectRange(newString);
  }

  // Zone is taken as a param to make it reactive
  function returnAnchor(
    asOf: string | undefined,
    zone: string,
  ): DateTime | undefined {
    if (!maxDate) return DateTime.now().setZone(zone);
    if (asOf === "latest") {
      return maxDate.setZone(zone);
    } else if (asOf === "watermark" && watermark) {
      return watermark.setZone(zone);
    } else if (asOf === "now" || !asOf) {
      return DateTime.now().setZone(zone);
    }
  }

  function closeMenu() {
    open = false;
  }
</script>

<svelte:window
  onkeydown={(e) => {
    if (e.metaKey && e.key === "k") {
      open = !open;
    }
  }}
/>

<Popover.Root
  bind:open
  onOpenChange={(o) => {
    if (o) {
      searchValue = timeString;
    }
  }}
>
  <Tooltip.Root delayDuration={800} ignoreNonKeyboardFocus>
    <Tooltip.Trigger>
      {#snippet child({ props: tooltipProps })}
        <Popover.Trigger>
          {#snippet child({ props: popoverProps })}
            <button
              {...tooltipProps}
              {...popoverProps}
              class="flex gap-x-1.5"
              aria-label={m.dashboard_select_time_range()}
              type="button"
            >
              {#if timeString}
                <b class="line-clamp-1 flex-none">
                  {#if selectedLabel?.startsWith("-") || !isNaN(Number(selectedLabel?.[0]))}
                    {m.dashboard_custom()}
                  {:else}
                    {selectedLabel}
                  {/if}
                </b>
              {/if}

              {#if showFullRange}
                <RangeDisplay {interval} {timeGrain} />

                <div
                  class="font-bold bg-surface-muted rounded-[2px] p-1 py-0 text-fg-secondary text-[11px]"
                >
                  {zoneAbbreviation}
                </div>
              {/if}

              <span
                class="flex-none transition-transform"
                class:-rotate-180={open}
              >
                <CaretDownIcon />
              </span>
            </button>
          {/snippet}
        </Popover.Trigger>
      {/snippet}
    </Tooltip.Trigger>

    <Tooltip.Content side="bottom" sideOffset={8} class="z-50">
      {#if interval}
        <PrimaryRangeTooltip
          {timeString}
          {interval}
          timeDimensionLabel={activeTimeDimension?.label}
          timeDimensionDescription={activeTimeDimension?.description}
        />
      {/if}
    </Tooltip.Content>
  </Tooltip.Root>

  <Popover.Content
    align="start"
    class="p-0 w-fit overflow-hidden flex flex-col"
  >
    <TimeRangeSearch
      inError={!parsedTime && !!timeString && !usingLegacyTime}
      width={showCalendarPicker ? 456 : 224}
      bind:this={searchComponent}
      {context}
      {timeString}
      bind:searchValue
      onSelectRange={(range) => {
        open = false;

        handleRangeSelect(range);
      }}
    />

    <div
      class="flex w-56 max-h-fit"
      class:!w-[456px]={showCalendarPicker}
      style:height="470px"
    >
      <div
        class="flex flex-col w-56 overflow-y-auto overflow-x-hidden flex-none py-1"
      >
        <div class="overflow-x-hidden">
          {#if showDefaultItem && defaultTimeRange}
            <TimeRangeOptionGroup
              {filter}
              {timeString}
              options={[parseParrotTime(defaultTimeRange)]}
              onClick={handleRangeSelect}
            />
          {/if}

          <TimeRangeOptionGroup
            {filter}
            {timeString}
            options={rangeBuckets.custom}
            onClick={handleRangeSelect}
          />

          <TimeRangeOptionGroup
            {filter}
            {timeString}
            options={rangeBuckets.latest}
            onClick={handleRangeSelect}
          />

          <TimeRangeOptionGroup
            {filter}
            {timeString}
            options={rangeBuckets.periodToDate}
            onClick={handleRangeSelect}
          />

          <TimeRangeOptionGroup
            {filter}
            {timeString}
            options={rangeBuckets.previous}
            onClick={(r) => {
              handleRangeSelect(r, true);
            }}
          />

          {#if allTimeAllowed}
            <div class="w-full h-fit px-1">
              <button
                type="button"
                role="menuitem"
                class="group truncate h-7 p-2 text-popover-foreground justify-between overflow-hidden hover:bg-popover-accent rounded-sm w-full select-none flex items-center"
                onclick={() => {
                  handleRangeSelect("inf");
                }}
              >
                <span class:font-bold={timeString === ALL_TIME_RANGE_ALIAS}>
                  {STATSPARROT_TO_LABEL[ALL_TIME_RANGE_ALIAS]}
                </span>
              </button>
            </div>
          {/if}
        </div>

        {#if allowCustomTimeRange}
          <div class="w-full h-fit px-1">
            <div class="h-px w-full bg-border my-1"></div>
            <button
              type="button"
              role="menuitem"
              class:font-bold={false}
              onclick={() => {
                showCalendarPicker = !showCalendarPicker;
              }}
              class="truncate text-fg-primary w-full text-left gap-x-1 pr-1 hover:bg-popover-accent flex items-center flex-shrink pl-2 h-7 rounded-sm"
            >
              <Calendar size="14px" />
              <div class="mr-auto">{m.dashboard_custom()}</div>

              <CaretDownIcon
                className="-rotate-90 text-fg-secondary"
                size="14px"
              />
            </button>
          </div>
        {/if}

        {#if !lockTimeZone}
          <div class="w-full h-fit px-1">
            <div class="h-px w-full bg-border my-1"></div>

            <Popover.Root bind:open={timeZonePickerOpen}>
              <Popover.Trigger
                onclick={() => {
                  showCalendarPicker = false;
                }}
                class="group h-7 overflow-hidden hover:bg-popover-accent flex-none rounded-sm w-full select-none flex items-center truncate text-left gap-x-1 pr-1 pl-2"
              >
                <div class="flex-none">
                  <Globe size="14px" className="text-fg-primary" />
                </div>
                <div class="mr-auto text-fg-primary">
                  {m.dashboard_time_zone()}
                </div>
                <div class="sr-only group-hover:not-sr-only">
                  <SyntaxElement range={zoneAbbreviation} />
                </div>
                <CaretDownIcon
                  className="-rotate-90 text-fg-secondary"
                  size="14px"
                />
              </Popover.Trigger>

              <Popover.Content
                align="center"
                side="right"
                sideOffset={12}
                class="p-1 z-50"
              >
                <ZoneContent
                  {context}
                  {availableTimeZones}
                  activeTimeZone={zone}
                  referencePoint={dateTimeAnchor ??
                    interval?.end ??
                    DateTime.now()}
                  onSelectTimeZone={(z) => {
                    onSelectTimeZone(z);
                    closeMenu();
                    timeZonePickerOpen = false;
                  }}
                />
              </Popover.Content>
            </Popover.Root>
          </div>
        {/if}

        {#if timeDimensions.length > 1 && onTimeDimensionSelect}
          <div class="w-full h-fit px-1">
            <div class="h-px w-full bg-border my-1"></div>

            <Popover.Root bind:open={timeAxisPickerOpen}>
              <Popover.Trigger
                id="time-axis-trigger-{context}"
                onclick={() => {
                  showCalendarPicker = false;
                }}
                aria-label={m.dashboard_select_time_axis()}
                class="group h-7 overflow-hidden hover:bg-surface-hover flex-none rounded-sm w-full select-none flex items-center truncate text-left gap-x-1 pr-1 pl-2"
              >
                <div class="flex-none">
                  <Clock size="14px" />
                </div>
                <div class="mr-auto">{m.dashboard_time_axis()}</div>
                {#if activeTimeDimension}
                  <div class="sr-only group-hover:not-sr-only">
                    <SyntaxElement range={activeTimeDimension.label} />
                  </div>
                {/if}
                <CaretDownIcon className="-rotate-90" size="14px" />
              </Popover.Trigger>

              <Popover.Content
                align="center"
                side="right"
                sideOffset={12}
                class="p-1 z-50"
              >
                {#each timeDimensions as { value, label, description } (value)}
                  <Tooltip.Root>
                    <Tooltip.Trigger>
                      {#snippet child({ props })}
                        <button
                          {...props}
                          class="item"
                          aria-label={m.dashboard_select_time_dimension({
                            label,
                          })}
                          onclick={() => {
                            onTimeDimensionSelect(value);
                            closeMenu();
                            timeAxisPickerOpen = false;
                          }}
                        >
                          {label}
                          {#if value === (selectedTimeDimension || primaryTimeDimension)}
                            <Check class="size-4" color="var(--fg-primary)" />
                          {/if}
                        </button>
                      {/snippet}
                    </Tooltip.Trigger>
                    {#if description}
                      <Tooltip.Content
                        side="right"
                        sideOffset={8}
                        class="max-w-64"
                      >
                        <div class="font-bold text-fg-inverse">{label}</div>
                        <div class="text-fg-inverse/70">{description}</div>
                      </Tooltip.Content>
                    {/if}
                  </Tooltip.Root>
                {/each}
              </Popover.Content>
            </Popover.Root>
          </div>
        {/if}
      </div>

      {#if showCalendarPicker}
        <div class="bg-surface-overlay border-l p-3 size-full overflow-y-auto">
          <CalendarPlusDateInput
            {interval}
            {zone}
            minTimeGrain={V1TimeGrainToDateTimeUnit[
              smallestTimeGrain ?? V1TimeGrain.TIME_GRAIN_MINUTE
            ]}
            {minDate}
            {maxDate}
            {maxQueryTimeRange}
            onApply={() => {
              if (searchValue) handleRangeSelect(searchValue);
            }}
            updateRange={(string) => {
              searchValue = string;
            }}
            closeMenu={() => (open = false)}
          />
        </div>
      {/if}
    </div>
  </Popover.Content>
</Popover.Root>

{#if dateTimeAnchor && !hideTruncationSelector}
  <TruncationSelector
    {dateTimeAnchor}
    grain={truncationGrain}
    rangeGrain={parsedTime?.rangeGrain ?? truncationGrain}
    isPeriodToDate={parsedTime?.interval instanceof ParrotPeriodToGrainInterval}
    {watermark}
    latest={maxDate}
    {smallestTimeGrain}
    {snapToEnd}
    {ref}
    {zone}
    onSelectEnding={onSelectGrain}
    onToggleAlignment={(inclusive) => {
      onSelectAsOfOption(ref, inclusive);
    }}
    onSelectAsOfOption={(o) => {
      onSelectAsOfOption(o, snapToEnd);
    }}
  />
{/if}

<style lang="postcss">
  .item {
    @apply w-full relative justify-between flex cursor-pointer select-none items-start rounded-sm py-1.5 px-2 gap-x-2 text-xs outline-none;
  }

  .item:hover {
    @apply bg-surface-hover text-fg-primary;
  }
</style>
