// web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/react/TimeRangeSearch.tsx
import { useMemo, useRef, useState, type FormEvent } from "react";
import { parseParrotTime } from "@statsparrot/web-common/features/dashboards/url-state/time-ranges/parser";
import { ALL_TIME_RANGE_ALIAS } from "@statsparrot/web-common/features/dashboards/time-controls/new-time-controls";
import { localStorageStore } from "@statsparrot/web-common/lib/store-utils";
import { useReadable } from "@statsparrot/web-common/features/components/charts/react/useReadable";
import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";
import { ClockIcon } from "./icons";
import { SyntaxElement } from "./SyntaxElement";

/**
 * React translation of `super-pill/components/TimeRangeSearch.svelte`. Text input that
 * parses a Parrot time string, remembers recent searches in `localStorage`, and renders
 * recent searches as syntax chips. Uses `useReadable()` to bridge the Svelte
 * `localStorageStore`.
 */
export interface TimeRangeSearchProps {
  context: string;
  width: number;
  inError: boolean;
  timeString?: string | undefined;
  searchValue: string;
  onSearchValueChange: (value: string) => void;
  onSelectRange: (range: string) => void;
}

export function TimeRangeSearch({
  context,
  width,
  inError,
  timeString,
  searchValue,
  onSearchValueChange,
  onSelectRange,
}: TimeRangeSearchProps) {
  const searchElement = useRef<HTMLInputElement>(null);
  const [unableToParse, setUnableToParse] = useState(false);

  const recentSearches = useMemo(
    () =>
      localStorageStore<string[]>(`${context}-recent-searches`, [
        "-7d/d to -3d/d",
        "-1d/d to -1d/d+6h",
        "D3 of M11",
      ]),
    [context],
  );
  const latestNSearches = useReadable(recentSearches) ?? [];

  const formError =
    (inError || unableToParse) && timeString !== ALL_TIME_RANGE_ALIAS;

  function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (searchValue === ALL_TIME_RANGE_ALIAS) {
      onSelectRange(ALL_TIME_RANGE_ALIAS);
      onSearchValueChange("");
      setUnableToParse(false);
      return;
    }

    try {
      parseParrotTime(searchValue);
      setUnableToParse(false);

      recentSearches.update((searches) => {
        return Array.from(new Set([searchValue, ...searches].slice(0, 15)));
      });

      onSelectRange(searchValue);
      onSearchValueChange("");
    } catch (e) {
      console.error(e);
      setUnableToParse(true);
    }
  }

  function updateSearch(value: string) {
    onSearchValueChange(value);
    searchElement.current?.focus();
  }

  return (
    <div
      className="border-b h-fit pt-2.5 py-0 flex p-3 gap-y-2 flex-col overflow-y-auto"
      style={{ width: `${width}px` }}
    >
      <form
        className={`overflow-hidden flex justify-center gap-x-1 items-center pl-2 pr-0.5 bg-input justify-center placeholder-fg-secondary text-fg-secondary border rounded-sm h-7 w-full truncate ${
          formError ? "border-red-500" : "focus-within:border-theme-500"
        }`}
        onSubmit={onSubmit}
      >
        <span
          className="mr-1 flex-none"
          role="presentation"
          onClick={() => searchElement.current?.focus()}
        >
          <ClockIcon size={15} />
        </span>
        <input
          placeholder={m.time_enter_time_range()}
          type="text"
          className="p-0 bg-transparent size-full outline-none border-0 cursor-text"
          value={searchValue}
          onChange={(e) => onSearchValueChange(e.target.value)}
          onKeyDown={() => {
            if (unableToParse) {
              setUnableToParse(false);
            }
          }}
          ref={searchElement}
        />
      </form>

      {unableToParse ? (
        <div className="text-red-500 text-xs">{m.time_unable_to_parse()}</div>
      ) : null}

      <div className="flex gap-x-2 size-full overflow-x-auto pb-2.5">
        {latestNSearches.map((search, i) => (
          <SyntaxElement key={i} range={search} onClick={updateSearch} />
        ))}
      </div>
    </div>
  );
}

// web-common/src/features/dashboards/time-controls/super-pill/components/TimeRangeSearch.svelte
<script lang="ts">
  import SyntaxElement from "./SyntaxElement.svelte";
  import { localStorageStore } from "@statsparrot/web-common/lib/store-utils";
  import { Clock } from "lucide-svelte";
  import { parseParrotTime } from "../../../url-state/time-ranges/parser";
  import { ALL_TIME_RANGE_ALIAS } from "../../new-time-controls";
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";

  export let context: string;
  export let width: number;
  export let inError: boolean;
  export let timeString: string | undefined = undefined;
  export let searchValue = timeString || "";
  export let onSelectRange: (range: string) => void;

  let searchElement: HTMLInputElement;
  let unableToParse = false;

  const latestNSearches = localStorageStore(`${context}-recent-searches`, [
    "-7d/d to -3d/d",
    "-1d/d to -1d/d+6h",
    "D3 of M11",
  ]);

  export function updateSearch(value: string) {
    searchValue = value;
    searchElement.focus();
  }
</script>

<div
  class="border-b h-fit pt-2.5 py-0 flex p-3 gap-y-2 flex-col overflow-y-auto"
  style:width="{width}px"
>
  <form
    class:error={(inError || unableToParse) &&
      timeString !== ALL_TIME_RANGE_ALIAS}
    class=""
    onsubmit={(e) => {
      e.preventDefault();

      if (searchValue === ALL_TIME_RANGE_ALIAS) {
        onSelectRange(ALL_TIME_RANGE_ALIAS);
        searchValue = "";
        unableToParse = false;
        return;
      }

      try {
        parseParrotTime(searchValue);

        unableToParse = false;

        latestNSearches.update((searches) => {
          return Array.from(new Set([searchValue, ...searches].slice(0, 15)));
        });

        onSelectRange(searchValue);

        searchValue = "";
      } catch (e) {
        console.error(e);
        unableToParse = true;
      }
    }}
  >
    <span
      class="mr-1 flex-none"
      role="presentation"
      onclick={() => {
        searchElement.focus();
      }}
    >
      <Clock size={15} />
    </span>
    <input
      placeholder={m.time_enter_time_range()}
      type="text"
      class="h-7 border w-full"
      onkeydown={() => {
        if (unableToParse) {
          unableToParse = false;
        }
      }}
      bind:this={searchElement}
      bind:value={searchValue}
    />
  </form>

  {#if unableToParse}
    <div class="text-red-500 text-xs">{m.time_unable_to_parse()}</div>
  {/if}

  <div class="flex gap-x-2 size-full overflow-x-auto pb-2.5">
    {#each $latestNSearches as search, i (i)}
      <SyntaxElement range={search} onClick={updateSearch} />
    {/each}
  </div>
</div>

<style lang="postcss">
  form {
    @apply overflow-hidden;
    @apply flex justify-center gap-x-1 items-center pl-2 pr-0.5;
    @apply bg-input justify-center placeholder-fg-secondary text-fg-secondary;
    @apply border rounded-sm;
    @apply h-7 w-full truncate;
  }

  form:focus-within {
    @apply border-theme-500;
  }

  form.error {
    @apply border-red-500;
  }

  input {
    @apply p-0 bg-transparent;
    @apply size-full;
    @apply outline-none border-0;
    @apply cursor-text;
    vertical-align: middle;
  }
</style>
