// web-common/src/features/dashboards/filters/react/Filters.tsx
import { useCallback, useMemo, type ReactNode } from "react";
import type { StateManagers } from "@rilldata/web-common/features/dashboards/state-managers/state-managers";
import type { DashboardStateSync } from "@rilldata/web-common/features/dashboards/state-managers/loaders/DashboardStateSync";
import { applyDimensionInListMode as applyDimensionInListModeDirectly } from "@rilldata/web-common/features/dashboards/state-managers/actions/dimension-filters";
import { useTimeControlStore } from "@rilldata/web-common/features/dashboards/time-controls/time-control-store";
import { getMapFromArray } from "@rilldata/web-common/lib/arrayUtils";
import { isExpressionUnsupported } from "@rilldata/web-common/features/dashboards/stores/filter-utils";
import { isUrlTooLong } from "@rilldata/web-common/features/dashboards/url-state/url-length-limits";
import { convertExpressionToFilterParam } from "@rilldata/web-common/features/dashboards/url-state/filters/converters";
import type { MeasureFilterEntry } from "@rilldata/web-common/features/dashboards/filters/measure-filters/measure-filter-entry";
import { useReadable } from "@rilldata/web-common/features/components/charts/react/useReadable";
import type {
  V1ExploreTimeRange,
  V1Expression,
} from "@rilldata/web-common/runtime-client";
import type { RuntimeClient } from "@rilldata/web-common/runtime-client/v2";
import { m } from "@rilldata/web-common/lib/i18n/gen/messages";
import { DimensionFilter } from "../dimension-filters/react";
import { MeasureFilter } from "../measure-filters/react";
import FilterButton from "./FilterButton";

/** the height of a row of chips */
const ROW_HEIGHT = "26px";

export interface FiltersProps {
  readOnly?: boolean;
  timeRanges: V1ExploreTimeRange[];
  metricsViewName: string;
  hasTimeSeries: boolean;
  /**
   * The `StateManagers` object that `Filters.svelte` reads from Svelte context
   * (`getStateManagers()`). Passed as a prop because Svelte context is unavailable in
   * React. The framework-agnostic selectors/actions/stores are reused verbatim.
   */
  stateManagers: StateManagers;
  /** Runtime client; defaults to `stateManagers.runtimeClient`. */
  runtimeClient?: RuntimeClient;
  /** Svelte-context `DashboardStateSync` (optional; guards the URL-too-long check). */
  dashboardStateSync?: DashboardStateSync | null;
  /**
   * The time-controls row (`SuperPill`, `ComparisonPill`, "as of" timestamp). Those
   * Svelte components are not ported to React yet, so the host may inject a rendered
   * node here. When omitted the time-series row is skipped.
   */
  timeControls?: ReactNode;
}

/**
 * React translation of `Filters.svelte` (Phase 2.2b-iii): the dashboard filter bar.
 *
 * Composes the already-ported React `DimensionFilter` / `MeasureFilter` chips, the
 * `FilterButton` add-filter menu, and the clear-all button. Reuses the
 * framework-agnostic state-manager selectors/actions and the `useReadable()` bridge for
 * the Svelte store values. The `isExpressionUnsupported` / URL-too-long guards are
 * copied verbatim from the Svelte source. The time-controls row is deferred to the
 * injected `timeControls` node.
 */
export default function Filters({
  readOnly = false,
  metricsViewName,
  hasTimeSeries,
  stateManagers,
  runtimeClient = stateManagers.runtimeClient,
  dashboardStateSync = null,
  timeControls,
}: FiltersProps) {
  const { actions, selectors } = stateManagers;

  // ── Store subscriptions (Svelte `$:` store reads) ─────────────────────────
  const dashboard = useReadable(stateManagers.dashboardStore);
  const timeControlsStore = useTimeControlStore(stateManagers);
  const timeControlsValue = useReadable(timeControlsStore);

  const { timeStart, timeEnd, ready: timeControlsReady } =
    timeControlsValue ?? {};

  const whereFilter = dashboard?.whereFilter;
  const selectedTimeDimension = dashboard?.selectedTimeDimension;

  // hasFilter only checks for complete filters and excludes temporary ones
  const getDimensionFilterItems = useReadable(
    selectors.dimensionFilters.getDimensionFilterItems,
  );
  const getAllDimensionFilterItems = useReadable(
    selectors.dimensionFilters.getAllDimensionFilterItems,
  );
  const getMeasureFilterItems = useReadable(
    selectors.measureFilters.getMeasureFilterItems,
  );
  const getAllMeasureFilterItems = useReadable(
    selectors.measureFilters.getAllMeasureFilterItems,
  );

  const dimensions = useReadable(selectors.dimensions.allDimensions) ?? [];
  const measures = useReadable(selectors.measures.allMeasures) ?? [];

  const dimensionIdMap = useMemo(
    () =>
      getMapFromArray(
        dimensions,
        (dimension) => (dimension.name || dimension.column) as string,
      ),
    [dimensions],
  );
  const measureIdMap = useMemo(
    () => getMapFromArray(measures, (measure) => measure.name as string),
    [measures],
  );

  const currentDimensionFilters = useMemo(
    () => (getDimensionFilterItems ? getDimensionFilterItems(dimensionIdMap) : []),
    [getDimensionFilterItems, dimensionIdMap],
  );
  const currentMeasureFilters = useMemo(
    () => (getMeasureFilterItems ? getMeasureFilterItems(measureIdMap) : []),
    [getMeasureFilterItems, measureIdMap],
  );

  const allDimensionFilters = useMemo(
    () =>
      getAllDimensionFilterItems
        ? getAllDimensionFilterItems(currentDimensionFilters, dimensionIdMap)
        : [],
    [getAllDimensionFilterItems, currentDimensionFilters, dimensionIdMap],
  );
  const allMeasureFilters = useMemo(
    () =>
      getAllMeasureFilterItems
        ? getAllMeasureFilterItems(currentMeasureFilters, measureIdMap)
        : [],
    [getAllMeasureFilterItems, currentMeasureFilters, measureIdMap],
  );

  const hasFilters =
    currentDimensionFilters.length > 0 || currentMeasureFilters.length > 0;

  const isComplexFilter = whereFilter
    ? isExpressionUnsupported(whereFilter)
    : false;

  const dimensionFilterExpressionMap = useMemo(
    () =>
      new Map<string, V1Expression>(
        whereFilter ? [[metricsViewName, whereFilter]] : [],
      ),
    [metricsViewName, whereFilter],
  );

  const filteredSimpleMeasuresFn = useReadable(
    selectors.measures.filteredSimpleMeasures,
  );
  const filteredSimpleMeasures = filteredSimpleMeasuresFn?.() ?? [];
  const dimensionHasFilter =
    useReadable(selectors.dimensionFilters.dimensionHasFilter) ?? (() => false);
  const measureHasFilter =
    useReadable(selectors.measureFilters.measureHasFilter) ?? (() => false);

  // ── Action wrappers (adapt `StateManagerActions` to the React port props) ──
  const {
    dimensionsFilter,
    measuresFilter,
    filters,
  } = actions;

  const handleRemoveDimensionFilter = useCallback(
    async (name: string, _metricsViewNames: string[]) => {
      dimensionsFilter.removeDimensionFilter(name);
    },
    [dimensionsFilter],
  );
  const handleToggleDimensionFilterMode = useCallback(
    async (name: string, _metricsViewNames: string[]) => {
      dimensionsFilter.toggleDimensionFilterMode(name);
    },
    [dimensionsFilter],
  );
  const handleToggleDimensionValueSelections = useCallback(
    async (
      name: string,
      values: string[],
      _metricsViewNames: string[],
      keepPillVisible?: boolean,
      isExclusiveFilter?: boolean,
      exclude?: boolean,
    ) => {
      dimensionsFilter.toggleMultipleDimensionValueSelections(
        name,
        values,
        keepPillVisible ?? true,
        isExclusiveFilter,
        exclude,
      );
    },
    [dimensionsFilter],
  );
  const handleApplyDimensionInListMode = useCallback(
    async (name: string, values: string[], _metricsViewNames: string[]) => {
      dimensionsFilter.applyDimensionInListMode(name, values);
    },
    [dimensionsFilter],
  );
  const handleApplyDimensionContainsMode = useCallback(
    async (name: string, searchText: string, _metricsViewNames: string[]) => {
      dimensionsFilter.applyDimensionContainsMode(name, searchText);
    },
    [dimensionsFilter],
  );

  const handleMeasureFilterApply = useCallback(
    (
      dimension: string,
      measureName: string,
      oldDimension: string,
      filter: MeasureFilterEntry,
    ) => {
      if (oldDimension && oldDimension !== dimension) {
        measuresFilter.removeMeasureFilter(oldDimension, measureName);
      }
      measuresFilter.setMeasureFilter(dimension, filter);
    },
    [measuresFilter],
  );

  const handleSetTemporaryFilterName = useCallback(
    (name: string) => filters.setTemporaryFilterName(name),
    [filters],
  );
  const handleClearAllFilters = useCallback(
    () => filters.clearAllFilters(),
    [filters],
  );

  const isUrlTooLongAfterInListFilter = useCallback(
    (dimensionName: string, values: string[]) => {
      if (!dashboardStateSync || !dashboard) return false;

      const exploreState = structuredClone(dashboard);
      applyDimensionInListModeDirectly(
        { dashboard: exploreState },
        dimensionName,
        values,
      );
      const url = dashboardStateSync.getUrlForExploreState(exploreState);
      return isUrlTooLong(url);
    },
    [dashboardStateSync, dashboard],
  );

  return (
    <div className="flex flex-col gap-y-2 size-full">
      {hasTimeSeries ? timeControls ?? null : null}

      <div className="relative flex flex-row gap-x-2 gap-y-2 items-start">
        {!readOnly ? (
          <FilterIcon
            size="16px"
            className="text-fg-secondary flex-none mt-[5px]"
          />
        ) : null}

        <div className="relative flex flex-row flex-wrap gap-x-2 gap-y-2">
          {isComplexFilter && whereFilter ? (
            <AdvancedFilterChip advancedFilter={whereFilter} />
          ) : !allDimensionFilters.length && !allMeasureFilters.length ? (
            <div
              className="text-fg-muted grid ml-1 items-center"
              style={{ minHeight: ROW_HEIGHT }}
            >
              {m.dashboard_no_filters_selected()}
            </div>
          ) : (
            <>
              {allDimensionFilters.map((filterData) => (
                <div key={filterData.name}>
                  <DimensionFilter
                    client={runtimeClient}
                    expressionMap={dimensionFilterExpressionMap}
                    filterData={filterData}
                    readOnly={readOnly}
                    timeStart={timeStart}
                    timeEnd={timeEnd}
                    timeDimension={selectedTimeDimension}
                    timeControlsReady={timeControlsReady}
                    removeDimensionFilter={handleRemoveDimensionFilter}
                    toggleDimensionFilterMode={
                      handleToggleDimensionFilterMode
                    }
                    toggleDimensionValueSelections={
                      handleToggleDimensionValueSelections
                    }
                    applyDimensionInListMode={
                      handleApplyDimensionInListMode
                    }
                    applyDimensionContainsMode={
                      handleApplyDimensionContainsMode
                    }
                    isUrlTooLongAfterInListFilter={(values) =>
                      isUrlTooLongAfterInListFilter(filterData.name, values)
                    }
                  />
                </div>
              ))}
              {allMeasureFilters.map((filterData) => (
                <div key={filterData.name}>
                  <MeasureFilter
                    filterData={filterData}
                    allDimensions={dimensions}
                    onRemove={() =>
                      measuresFilter.removeMeasureFilter(
                        filterData.dimensionName,
                        filterData.name,
                      )
                    }
                    onApply={({ dimension, oldDimension, filter }) =>
                      handleMeasureFilterApply(
                        dimension,
                        filterData.name,
                        oldDimension,
                        filter,
                      )
                    }
                  />
                </div>
              ))}
            </>
          )}

          {!readOnly ? (
            <>
              <FilterButton
                allDimensions={dimensions}
                filteredSimpleMeasures={filteredSimpleMeasures}
                dimensionHasFilter={dimensionHasFilter}
                measureHasFilter={measureHasFilter}
                setTemporaryFilterName={handleSetTemporaryFilterName}
              />
              {/* if filters are present, place a chip at the end of the flex container
                  that enables clearing all filters */}
              {hasFilters ? (
                <button
                  type="button"
                  className="flex flex-none text-center items-center justify-center text-xs leading-snug font-normal text-fg-muted p-0 hover:text-primary-700 active:text-primary-800"
                  onClick={handleClearAllFilters}
                >
                  {m.dashboard_clear_filters()}
                </button>
              ) : null}
            </>
          ) : null}
        </div>
      </div>
    </div>
  );
}

/** React translation of `AdvancedFilter.svelte` (complex-filter pill). */
function AdvancedFilterChip({ advancedFilter }: { advancedFilter: V1Expression }) {
  const filterText = convertExpressionToFilterParam(advancedFilter);
  return (
    <div
      className="flex flex-none px-2 py-[3px] max-h-[26px] border bg-surface-subtle border-gray-200 text-fg-primary rounded-2xl"
      title={m.filter_advanced_warning()}
    >
      <span className="font-bold mr-1">{m.filter_advanced_beta()}</span>
      <span>{filterText}</span>
    </div>
  );
}

/** React stand-in for the `Filter.svelte` icon. */
function FilterIcon({
  size = "16px",
  className = "",
}: {
  size?: string;
  className?: string;
}) {
  return (
    <svg
      height={size}
      width={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-label="Filter Icon"
    >
      <path
        d="M9.18756 13.1251L5.37982 8.625H18.6204L14.8126 13.1251V19.8751C14.8126 20.4731 14.3462 20.9621 13.7573 20.998L9.18756 17.6556V13.1251Z"
        fill="currentColor"
      />
      <path
        d="M10.8751 12.507V18.8899L9.18758 17.6556V13.1251L3.26619 6.12713C3.09432 5.924 3 5.66652 3 5.40044V4.12501C3 3.50369 3.50369 3 4.12501 3H19.8752C20.4966 3 21.0002 3.50369 21.0002 4.12501V5.40044C21.0002 5.66652 20.9059 5.924 20.734 6.12713L14.8127 13.1251V19.8752C14.8127 20.4731 14.3462 20.9621 13.7574 20.9981L13.1251 20.5356V12.507L19.3127 5.19438V4.68752H4.68752V5.19438L10.8751 12.507Z"
        fill="currentColor"
      />
    </svg>
  );
}

// web-common/src/features/dashboards/filters/Filters.svelte
<script lang="ts">
  import Button from "@statsparrot/web-common/components/button/Button.svelte";
  import Calendar from "@statsparrot/web-common/components/icons/Calendar.svelte";
  import Filter from "@statsparrot/web-common/components/icons/Filter.svelte";
  import AdvancedFilter from "@statsparrot/web-common/features/dashboards/filters/AdvancedFilter.svelte";
  import MeasureFilter from "@statsparrot/web-common/features/dashboards/filters/measure-filters/MeasureFilter.svelte";
  import type { MeasureFilterEntry } from "@statsparrot/web-common/features/dashboards/filters/measure-filters/measure-filter-entry";
  import { useMetricsViewTimeRange } from "@statsparrot/web-common/features/dashboards/selectors.ts";
  import { DashboardStateSync } from "@statsparrot/web-common/features/dashboards/state-managers/loaders/DashboardStateSync";
  import { isExpressionUnsupported } from "@statsparrot/web-common/features/dashboards/stores/filter-utils";
  import { isUrlTooLong } from "@statsparrot/web-common/features/dashboards/url-state/url-length-limits";
  import { getMapFromArray } from "@statsparrot/web-common/lib/arrayUtils";
  import { queryClient } from "@statsparrot/web-common/lib/svelte-query/globalQueryClient.ts";
  import type { TimeRange } from "@statsparrot/web-common/lib/time/types";
  import {
    TimeComparisonOption,
    TimeRangePreset,
    type DashboardTimeControls,
  } from "@statsparrot/web-common/lib/time/types";
  import {
    V1TimeGrain,
    type V1ExploreTimeRange,
  } from "@statsparrot/web-common/runtime-client";
  import { invalidationForMetricsViewData } from "@statsparrot/web-common/runtime-client/invalidation.ts";
  import { DateTime, Duration, Interval } from "luxon";
  import { flip } from "svelte/animate";
  import { fly } from "svelte/transition";
  import { getStateManagers } from "../state-managers/state-managers";
  import { applyDimensionInListMode as applyDimensionInListModeDirectly } from "../state-managers/actions/dimension-filters";
  import {
    metricsExplorerStore,
    useExploreState,
  } from "../stores/dashboard-stores";
  import ComparisonPill from "../time-controls/comparison-pill/ComparisonPill.svelte";
  import {
    CUSTOM_TIME_RANGE_ALIAS,
    deriveInterval,
  } from "../time-controls/new-time-controls";
  import { allowedGrainsForInterval } from "@statsparrot/web-common/lib/time/new-grains";
  import SuperPill from "../time-controls/super-pill/SuperPill.svelte";
  import { useTimeControlStore } from "../time-controls/time-control-store";
  import FilterButton from "./FilterButton.svelte";
  import DimensionFilter from "./dimension-filters/DimensionFilter.svelte";
  import { featureFlags } from "../../feature-flags";
  import Timestamp from "@statsparrot/web-common/features/dashboards/time-controls/super-pill/components/Timestamp.svelte";
  import { getDefaultTimeGrain } from "@statsparrot/web-common/lib/time/grains";
  import * as Tooltip from "@statsparrot/web-common/components/tooltip-v2";
  import Metadata from "../time-controls/super-pill/components/Metadata.svelte";
  import { getValidComparisonOption } from "../time-controls/time-range-store";
  import { getPinnedTimeZones } from "../url-state/getDefaultExplorePreset";
  import { useRuntimeClient } from "@statsparrot/web-common/runtime-client/v2";
  import { m } from "@statsparrot/web-common/lib/i18n/gen/messages";

  const { statsparrotTime } = featureFlags;

  export let readOnly = false;
  export let timeRanges: V1ExploreTimeRange[];
  export let metricsViewName: string;
  export let hasTimeSeries: boolean;

  /** the height of a row of chips */
  const ROW_HEIGHT = "26px";

  const StateManagers = getStateManagers();
  const {
    exploreName,
    validSpecStore,
    actions: {
      dimensionsFilter: {
        toggleMultipleDimensionValueSelections,
        applyDimensionInListMode,
        applyDimensionContainsMode,
        removeDimensionFilter,
        toggleDimensionFilterMode,
      },

      measuresFilter: { setMeasureFilter, removeMeasureFilter },
      filters: { clearAllFilters, setTemporaryFilterName },
    },
    selectors: {
      dimensions: { allDimensions, timeDimensions },
      dimensionFilters: {
        dimensionHasFilter,
        getDimensionFilterItems,
        getAllDimensionFilterItems,
      },
      measures: { allMeasures, filteredSimpleMeasures },
      measureFilters: {
        getMeasureFilterItems,
        getAllMeasureFilterItems,
        measureHasFilter,
      },
      pivot: { showPivot },
      charts: { canPanLeft, canPanRight, getNewPanRange },
    },
    dashboardStore,
  } = StateManagers;

  const timeControlsStore = useTimeControlStore(StateManagers);

  const dashboardStateSync = DashboardStateSync.getFromContext();

  let showDefaultItem = false;

  const client = useRuntimeClient();

  $: timeRangeQuery = useMetricsViewTimeRange(client, metricsViewName);

  $: timeRangeSummary = $timeRangeQuery.data?.timeRangeSummary;

  $: watermark = timeRangeSummary?.watermark;

  $: maxQueryTimeRangeMillis = Number(
    $timeRangeQuery.data?.maxQueryTimeRangeMillis ?? 0,
  );
  $: maxQueryTimeRange =
    maxQueryTimeRangeMillis > 0
      ? Duration.fromMillis(maxQueryTimeRangeMillis)
      : undefined;

  $: ({
    selectedTimeRange,
    allTimeRange,
    showTimeComparison,
    selectedComparisonTimeRange,
    minTimeGrain,
    timeStart,
    timeEnd,
    ready: timeControlsReady,
  } = $timeControlsStore);

  $: exploreSpec = $validSpecStore.data?.explore ?? {};
  $: metricsViewSpec = $validSpecStore.data?.metricsView ?? {};

  $: exploreState = useExploreState($exploreName);
  $: activeTimeZone = $exploreState?.selectedTimezone;

  $: selectedRangeAlias =
    selectedTimeRange?.name === TimeRangePreset.CUSTOM
      ? `${selectedTimeRange.start.toISOString()},${selectedTimeRange.end.toISOString()}`
      : selectedTimeRange?.name;

  $: activeTimeGrain = selectedTimeRange?.interval;
  $: defaultTimeRange = exploreSpec.defaultPreset?.timeRange;

  $: dimensions = $allDimensions;
  $: dimensionIdMap = getMapFromArray(
    dimensions,
    (dimension) => (dimension.name || dimension.column) as string,
  );

  $: measures = $allMeasures;
  $: measureIdMap = getMapFromArray(measures, (m) => m.name as string);

  $: currentDimensionFilters = $getDimensionFilterItems(dimensionIdMap);
  $: allDimensionFilters = $getAllDimensionFilterItems(
    currentDimensionFilters,
    dimensionIdMap,
  );

  $: currentMeasureFilters = $getMeasureFilterItems(measureIdMap);
  $: allMeasureFilters = $getAllMeasureFilterItems(
    currentMeasureFilters,
    measureIdMap,
  );

  // hasFilter only checks for complete filters and excludes temporary ones
  $: hasFilters =
    currentDimensionFilters.length > 0 || currentMeasureFilters.length > 0;

  $: ({ whereFilter, selectedTimeDimension } = $dashboardStore);

  $: isComplexFilter = isExpressionUnsupported(whereFilter);

  $: availableTimeZones = getPinnedTimeZones(exploreSpec);

  $: allTimeRangeInterval = allTimeRange
    ? Interval.fromDateTimes(allTimeRange.start, allTimeRange.end)
    : Interval.invalid("Invalid interval");

  $: maybeInterval = selectedTimeRange
    ? Interval.fromDateTimes(
        DateTime.fromJSDate(selectedTimeRange.start).setZone(activeTimeZone),
        DateTime.fromJSDate(selectedTimeRange.end).setZone(activeTimeZone),
      )
    : allTimeRange
      ? Interval.fromDateTimes(allTimeRange.start, allTimeRange.end)
      : undefined;

  $: interval = maybeInterval?.isValid ? maybeInterval : undefined;

  $: baseTimeRange = selectedTimeRange?.start &&
    selectedTimeRange?.end && {
      name: selectedTimeRange?.name,
      start: selectedTimeRange.start,
      end: selectedTimeRange.end,
    };

  $: primaryTimeDimension = metricsViewSpec.timeDimension;

  $: timeDimensionOptions = $timeDimensions.map((timeDim) => {
    return {
      value: timeDim.name!,
      label: timeDim.displayName || timeDim.name!,
      description: timeDim.description,
    };
  });

  $: maybeMinDate = allTimeRange?.start
    ? DateTime.fromJSDate(allTimeRange.start)
    : undefined;
  $: maybeMaxDate = allTimeRange?.end
    ? DateTime.fromJSDate(allTimeRange.end)
    : undefined;

  $: minDate = maybeMinDate?.isValid ? maybeMinDate : undefined;
  $: maxDate = maybeMaxDate?.isValid ? maybeMaxDate : undefined;

  function handleMeasureFilterApply(
    dimension: string,
    measureName: string,
    oldDimension: string,
    filter: MeasureFilterEntry,
  ) {
    if (oldDimension && oldDimension !== dimension) {
      removeMeasureFilter(oldDimension, measureName);
    }
    setMeasureFilter(dimension, filter);
  }

  async function onTimeDimensionSelect(column: string) {
    // Capture time range name before any state changes
    const timeRangeName = selectedTimeRange?.name;

    await queryClient.cancelQueries({
      predicate: (query) =>
        invalidationForMetricsViewData(query, metricsViewName),
    });

    metricsExplorerStore.setTimeDimension($exploreName, column);

    // Re-resolve the time range with the new time dimension
    if (!timeRangeName) return;

    const { interval, grain } = await deriveInterval(
      timeRangeName,
      client,
      metricsViewName,
      activeTimeZone,
      column,
    );

    if (interval.isValid) {
      const validInterval = interval as Interval<true>;
      const baseTimeRange: TimeRange = {
        name: timeRangeName,
        start: validInterval.start.toJSDate(),
        end: validInterval.end.toJSDate(),
      };

      selectRange(baseTimeRange, grain);
    }
  }

  function onPan(direction: "left" | "right") {
    const panRange = $getNewPanRange(direction);
    if (!panRange) return;
    const { start, end } = panRange;

    const timeRange = {
      name: CUSTOM_TIME_RANGE_ALIAS,
      start: start,
      end: end,
    };

    const comparisonTimeRange = {
      name: TimeComparisonOption.CONTIGUOUS,
    } as DashboardTimeControls; // FIXME wrong typecasting across application

    if (!activeTimeGrain) return;
    metricsExplorerStore.selectTimeRange(
      $exploreName,
      timeRange as TimeRange,
      activeTimeGrain,
      comparisonTimeRange,
      metricsViewSpec,
    );
  }

  async function onSelectRange(alias: string, tz = activeTimeZone) {
    // If we don't have a valid time range, early return
    if (!allTimeRange?.end) return;

    // This should be returned by the API, but it is not yet implemented
    const includesTimeZoneOffset = alias.includes("tz");

    if (includesTimeZoneOffset) {
      const timeZone = alias.match(/tz (.*)/)?.[1];

      if (timeZone) metricsExplorerStore.setTimeZone($exploreName, timeZone);
    }

    await queryClient.cancelQueries({
      predicate: (query) =>
        invalidationForMetricsViewData(query, metricsViewName),
    });

    const { interval, grain } = await deriveInterval(
      alias,
      client,
      metricsViewName,
      tz,
      selectedTimeDimension,
    );

    const allowedGrains = allowedGrainsForInterval(
      interval,
      minTimeGrain ?? V1TimeGrain.TIME_GRAIN_MINUTE,
    );

    const finalGrain =
      activeTimeGrain && allowedGrains.includes(activeTimeGrain)
        ? activeTimeGrain
        : grain && allowedGrains.includes(grain)
          ? grain
          : allowedGrains[0];

    if (interval.isValid) {
      const validInterval = interval as Interval<true>;
      const baseTimeRange: TimeRange = {
        name: alias,
        start: validInterval.start.toJSDate(),
        end: validInterval.end.toJSDate(),
      };

      selectRange(baseTimeRange, finalGrain);
    }
  }

  function makeTimeSeriesTimeRangeAndUpdateAppState(
    timeRange: TimeRange,
    timeGrain: V1TimeGrain,
    /** we should only reset the comparison range when the user has explicitly chosen a new
     * time range. Otherwise, the current comparison state should continue to be the
     * source of truth.
     */
    comparisonTimeRange: DashboardTimeControls | undefined,
  ) {
    metricsExplorerStore.selectTimeRange(
      $exploreName,
      timeRange,
      timeGrain,
      comparisonTimeRange,
      metricsViewSpec,
    );
  }

  function selectRange(range: TimeRange, grain?: V1TimeGrain) {
    const timeGrain =
      grain ?? getDefaultTimeGrain(range.start, range.end).grain;

    // Get valid option for the new time range
    const validComparison =
      allTimeRange &&
      getValidComparisonOption(
        exploreSpec.timeRanges,
        range,
        $exploreState.selectedComparisonTimeRange?.name as
          | TimeComparisonOption
          | undefined,
        allTimeRange,

        activeTimeZone,
      );

    makeTimeSeriesTimeRangeAndUpdateAppState(range, timeGrain, {
      name: validComparison,
    } as DashboardTimeControls);
  }

  async function onSelectTimeZone(timeZone: string) {
    if (!interval?.isValid) return;

    if (selectedRangeAlias === TimeRangePreset.CUSTOM) {
      selectRange({
        name: TimeRangePreset.CUSTOM,
        start: interval.start
          ?.setZone(timeZone, { keepLocalTime: true })
          .toJSDate(),
        end: interval.end
          ?.setZone(timeZone, { keepLocalTime: true })
          .toJSDate(),
      });
    } else if (selectedRangeAlias) {
      // Trigger range selection so that MetricsViewTimeRanges is called with the new time zone
      await onSelectRange(selectedRangeAlias, timeZone);
    }
    metricsExplorerStore.setTimeZone($exploreName, timeZone);
  }

  $: usingParrotTime =
    !selectedRangeAlias?.startsWith("P") &&
    !selectedRangeAlias?.startsWith("statsparrot-");

  function onTimeGrainSelect(timeGrain: V1TimeGrain) {
    if (usingParrotTime && selectedRangeAlias) {
      metricsExplorerStore.setTimeGrain($exploreName, timeGrain);
    } else if (baseTimeRange) {
      makeTimeSeriesTimeRangeAndUpdateAppState(
        baseTimeRange,
        timeGrain,
        $dashboardStore?.selectedComparisonTimeRange,
      );
    }
  }

  function isUrlTooLongAfterInListFilter(
    dimensionName: string,
    values: string[],
  ) {
    if (!dashboardStateSync) return false;

    const exploreState = structuredClone($dashboardStore);
    applyDimensionInListModeDirectly(
      { dashboard: exploreState },
      dimensionName,
      values,
    );
    const url = dashboardStateSync.getUrlForExploreState(exploreState);
    return isUrlTooLong(url);
  }
</script>

<div class="flex flex-col gap-y-2 size-full">
  {#if hasTimeSeries}
    <div class="flex flex-row flex-wrap gap-x-2 gap-y-1.5 items-center">
      <Tooltip.Root delayDuration={0}>
        <Tooltip.Trigger class="cursor-default text-fg-secondary">
          <Calendar size="16px" />
        </Tooltip.Trigger>
        <Tooltip.Content side="bottom" sideOffset={10}>
          <Metadata
            timeZone={activeTimeZone}
            timeStart={allTimeRange?.start}
            timeEnd={allTimeRange?.end}
          />
        </Tooltip.Content>
      </Tooltip.Root>
      {#if allTimeRange?.start && allTimeRange?.end}
        <SuperPill
          {minDate}
          {maxDate}
          {selectedRangeAlias}
          showPivot={$showPivot}
          {minTimeGrain}
          {defaultTimeRange}
          {availableTimeZones}
          {timeRanges}
          complete={false}
          {interval}
          context={$exploreName}
          {timeStart}
          {timeEnd}
          lockTimeZone={exploreSpec.lockTimeZone}
          allowCustomTimeRange={exploreSpec.allowCustomTimeRange}
          {maxQueryTimeRange}
          {activeTimeGrain}
          {activeTimeZone}
          canPanLeft={$canPanLeft}
          canPanRight={$canPanRight}
          {primaryTimeDimension}
          {selectedTimeDimension}
          {showDefaultItem}
          timeDimensions={timeDimensionOptions}
          watermark={watermark ? DateTime.fromISO(watermark) : undefined}
          applyRange={selectRange}
          {onTimeDimensionSelect}
          {onSelectRange}
          {onTimeGrainSelect}
          {onSelectTimeZone}
          {onPan}
        />
        <ComparisonPill
          {minTimeGrain}
          {allTimeRange}
          {selectedTimeRange}
          showTimeComparison={!!showTimeComparison}
          {selectedComparisonTimeRange}
        />
      {/if}

      {#if !$statsparrotTime && allTimeRangeInterval?.end?.isValid}
        <Tooltip.Root delayDuration={0}>
          <Tooltip.Trigger>
            <span class="text-fg-secondary italic">
              {m.dashboard_as_of()}
              <Timestamp
                id="filter-bar-as-of"
                italic
                suppress
                showDate={false}
                date={allTimeRangeInterval.end}
                zone={activeTimeZone}
              />
            </span>
          </Tooltip.Trigger>
          <Tooltip.Content side="bottom" sideOffset={10}>
            <Metadata
              timeZone={activeTimeZone}
              timeStart={allTimeRange?.start}
              timeEnd={allTimeRange?.end}
            />
          </Tooltip.Content>
        </Tooltip.Root>
      {/if}
    </div>
  {/if}

  <div class="relative flex flex-row gap-x-2 gap-y-2 items-start">
    {#if !readOnly}
      <Filter size="16px" className="text-fg-secondary flex-none mt-[5px]" />
    {/if}
    <div class="relative flex flex-row flex-wrap gap-x-2 gap-y-2">
      {#if isComplexFilter}
        <AdvancedFilter advancedFilter={whereFilter} />
      {:else if !allDimensionFilters.length && !allMeasureFilters.length}
        <div
          in:fly={{ duration: 200, x: 8 }}
          class="text-fg-muted grid ml-1 items-center"
          style:min-height={ROW_HEIGHT}
        >
          {m.dashboard_no_filters_selected()}
        </div>
      {:else}
        {#each allDimensionFilters as filterData (filterData.name)}
          <div animate:flip={{ duration: 200 }}>
            <DimensionFilter
              expressionMap={new Map([
                [metricsViewName, $dashboardStore.whereFilter],
              ])}
              {filterData}
              {readOnly}
              {timeStart}
              {timeEnd}
              timeDimension={selectedTimeDimension}
              {timeControlsReady}
              removeDimensionFilter={async (name) =>
                removeDimensionFilter(name)}
              toggleDimensionFilterMode={async (name) => {
                toggleDimensionFilterMode(name);
              }}
              toggleDimensionValueSelections={async (
                name,
                values,
                _metricsViewNames,
                keepPillVisible,
                isExclusiveFilter,
                exclude,
              ) =>
                toggleMultipleDimensionValueSelections(
                  name,
                  values,
                  keepPillVisible ?? true,
                  isExclusiveFilter,
                  exclude,
                )}
              applyDimensionInListMode={async (name, values) =>
                applyDimensionInListMode(name, values)}
              applyDimensionContainsMode={async (name, searchText) =>
                applyDimensionContainsMode(name, searchText)}
              isUrlTooLongAfterInListFilter={(values) =>
                isUrlTooLongAfterInListFilter(filterData.name, values)}
            />
          </div>
        {/each}
        {#each allMeasureFilters as filterData (filterData.name)}
          <div animate:flip={{ duration: 200 }}>
            <MeasureFilter
              {filterData}
              allDimensions={dimensions}
              onRemove={() =>
                removeMeasureFilter(filterData.dimensionName, filterData.name)}
              onApply={({ dimension, oldDimension, filter }) =>
                handleMeasureFilterApply(
                  dimension,
                  filterData.name,
                  oldDimension,
                  filter,
                )}
            />
          </div>
        {/each}
      {/if}

      {#if !readOnly}
        <FilterButton
          allDimensions={dimensions}
          filteredSimpleMeasures={$filteredSimpleMeasures()}
          dimensionHasFilter={$dimensionHasFilter}
          measureHasFilter={$measureHasFilter}
          {setTemporaryFilterName}
        />
        <!-- if filters are present, place a chip at the end of the flex container 
      that enables clearing all filters -->
        {#if hasFilters}
          <Button type="text" onClick={clearAllFilters}
            >{m.dashboard_clear_filters()}</Button
          >
        {/if}
      {/if}
    </div>
  </div>
</div>
